import {db,secrets,json,error,requireAuth} from '@appdeploy/sdk';
type ProviderStatus={supabaseConfigured:boolean;emailPasswordReady:boolean;phoneOtpReady:boolean;socialFallback:boolean;mfaReady:boolean};type RateRow={count:number;updatedAt:number};type Staff={email:string;role:string;status:string};
async function names(){try{return await secrets.listSecretNames()}catch{return []}}
async function provider():Promise<ProviderStatus>{const n=await names();const supabaseConfigured=n.includes('SUPABASE_URL')&&n.includes('SUPABASE_PUBLISHABLE_KEY');const adapterReady=n.includes('HEART_CONNECT_SUPABASE_AUTH_ACTIVE');return{supabaseConfigured,emailPasswordReady:supabaseConfigured&&adapterReady,phoneOtpReady:supabaseConfigured&&adapterReady&&n.includes('HEART_CONNECT_PHONE_OTP_ACTIVE'),socialFallback:true,mfaReady:supabaseConfigured&&adapterReady&&n.includes('HEART_CONNECT_MFA_ACTIVE')}}
async function digest(v:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('')}
function source(event:any){const h=event?.headers||{};const ip=event?.requestContext?.http?.sourceIp||h['cf-connecting-ip']||h['x-forwarded-for']||'unknown';return String(ip).split(',')[0].trim()}
async function limited(event:any,kind:string,identifier:string,limit:number,windowMs:number){const key=await digest(source(event)+'|'+String(identifier||'').trim().toLowerCase());const bucket=Math.floor(Date.now()/windowMs);const table='auth-rate:'+kind+':'+key+':'+bucket;const cur=(await db.list<RateRow>(table,{limit:1})).items[0];if((cur?.count||0)>=limit)return true;if(cur)await db.update(table,[{id:cur.id,record:{count:(cur.count||0)+1,updatedAt:Date.now()}}]);else await db.add(table,[{count:1,updatedAt:Date.now()}]);return false}
function dobAdult(v:string){const d=new Date(v);if(Number.isNaN(d.getTime()))return false;const n=new Date();let a=n.getUTCFullYear()-d.getUTCFullYear();const m=n.getUTCMonth()-d.getUTCMonth();if(m<0||(m===0&&n.getUTCDate()<d.getUTCDate()))a--;return a>=18}
function providerGate(p:ProviderStatus,feature:'email'|'phone'){if(feature==='email'&&!p.emailPasswordReady)return error(p.supabaseConfigured?'Supabase credentials are detected, but Heart Connect auth activation is intentionally disabled until session binding is completed.':'Heart Connect email/password authentication is prepared but Supabase is not connected yet.',503);if(feature==='phone'&&!p.phoneOtpReady)return error('Phone OTP is not configured. No SMS was sent.',503);return null}
async function admin(email?:string){if(!email)return false;const n=await names();if(!n.includes('HEART_CONNECT_ADMIN_EMAILS'))return false;const raw=await secrets.readSecret('HEART_CONNECT_ADMIN_EMAILS');return raw.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean).includes(email.toLowerCase())}
async function role(email?:string){if(await admin(email))return 'Super Admin';if(!email)return 'User';const rows=await db.list<Staff>('stage7_staff_roles',{limit:200});const s=rows.items.find(x=>x.status==='active'&&x.email?.toLowerCase()===email.toLowerCase());if(!s)return 'User';const r=String(s.role||'').toLowerCase();if(r.includes('moderator')||r.includes('safety'))return 'Moderator';if(r.includes('support'))return 'Support Agent';if(r.includes('admin'))return 'Admin';return 'Support Agent'}
async function securityEvents(uid:string){const r=await db.list<{kind:string;text:string;time:number}>('auth-security-events:'+uid,{limit:20});return r.items.filter(x=>x.kind==='suspicious_login').sort((a,b)=>b.time-a.time).slice(0,10).map(x=>({text:x.text,time:x.time}))}
export const authSystemRoutes={
'GET /api/auth/provider-status':[async()=>json(await provider())],
'POST /api/auth/register/preflight':[async c=>{const b=c.body as {firstName?:string;email?:string;phone?:string;dob?:string;country?:string;city?:string;terms?:boolean;privacy?:boolean;ageConfirm?:boolean;passwordPolicy?:{length?:number;upper?:boolean;lower?:boolean;number?:boolean}};if(await limited(c.event,'register',String(b.email||b.phone||''),5,60*60*1000))return error('Too many registration attempts. Try again later.',429);if(!b.firstName?.trim()||!b.email?.includes('@')||!b.phone?.trim()||!b.city?.trim()||!b.country?.trim())return error('Complete all required registration details.',400);if(!b.dob||!dobAdult(b.dob)||b.ageConfirm!==true)return error('Heart Connect is available only to adults aged 18 or older.',400);if(b.terms!==true||b.privacy!==true)return error('Terms and Privacy Policy acceptance are required.',400);const pw=b.passwordPolicy;if(!pw||Number(pw.length)<8||!pw.upper||!pw.lower||!pw.number)return error('Password policy requirements were not met.',400);const p=await provider();const g=providerGate(p,'email');return g||json({ok:true,provider:'supabase'})}],
'POST /api/auth/login/preflight':[async c=>{const b=c.body as {identifier?:string;channel?:string};const id=String(b.identifier||'').trim();if(await limited(c.event,'login',id,10,15*60*1000))return error('Too many sign-in attempts. Try again later.',429);if(!id)return error('Enter your email or phone number.',400);const p=await provider();const g=providerGate(p,b.channel==='phone'?'phone':'email');return g||error('Credential validation is delegated to Supabase and will be activated with the dedicated Heart Connect project.',501)}],
'POST /api/auth/recovery/request':[async c=>{const id=String((c.body as {identifier?:string})?.identifier||'').trim();if(await limited(c.event,'recovery',id,5,60*60*1000))return error('Too many recovery requests. Try again later.',429);if(!id)return error('Enter an email or phone number.',400);const p=await provider();const g=providerGate(p,'email');return g||error('Recovery provider binding is not active yet.',501)}],
'POST /api/auth/password/reset':[async c=>{if(await limited(c.event,'password-reset','token',8,60*60*1000))return error('Too many reset attempts. Try again later.',429);const p=await provider();const g=providerGate(p,'email');return g||error('Secure reset-token validation will be delegated to Supabase after provider activation.',501)}],
'POST /api/auth/email/resend':[async c=>{const email=String((c.body as {email?:string})?.email||'').trim();if(await limited(c.event,'email-verify',email,5,60*60*1000))return error('Too many verification requests. Try again later.',429);const p=await provider();const g=providerGate(p,'email');return g||error('Email verification delivery is not active yet.',501)}],
'POST /api/auth/phone/otp/request':[async c=>{const phone=String((c.body as {phone?:string})?.phone||'').trim();if(await limited(c.event,'otp-send',phone,5,60*60*1000))return error('Too many OTP requests. Try again later.',429);if(!phone)return error('Enter a phone number.',400);const p=await provider();const g=providerGate(p,'phone');return g||error('OTP provider binding is not active yet.',501)}],
'POST /api/auth/phone/otp/verify':[async c=>{const b=c.body as {phone?:string;code?:string};const phone=String(b.phone||'').trim();const code=String(b.code||'').trim();if(await limited(c.event,'otp-verify',phone,8,15*60*1000))return error('Too many OTP attempts. Request a new code later.',429);if(!/^\d{6}$/.test(code))return error('Enter the 6-digit verification code.',400);const p=await provider();const g=providerGate(p,'phone');return g||error('OTP verification provider binding is not active yet.',501)}],
'GET /api/auth/security':[requireAuth(),async c=>{const p=await provider();const h=c.event?.headers||{};const ua=String(h['user-agent']||h['User-Agent']||'Unknown browser');const device=/mobile|android|iphone/i.test(ua)?'Mobile device':'Desktop device';const browser=/edg/i.test(ua)?'Edge':/chrome/i.test(ua)?'Chrome':/safari/i.test(ua)?'Safari':/firefox/i.test(ua)?'Firefox':'Browser';const country=String(h['cf-ipcountry']||h['cloudfront-viewer-country']||'Approximate location unavailable');return json({role:await role(c.user!.email),email:c.user!.email,provider:p,mfaReady:p.mfaReady,sessions:[{device,browser,approximateLocation:country,lastActive:Date.now(),current:true,expires:'Session expiry is managed by the active identity provider.'}],alerts:await securityEvents(c.user!.userId)})}],
'POST /api/auth/security/logout-all':[requireAuth(),async()=>{const p=await provider();if(!p.emailPasswordReady)return error('Cross-device session revocation requires the dedicated Supabase identity provider.',503);return error('Cross-device revocation binding is not active yet.',501)}],
'POST /api/auth/security/change-password':[requireAuth(),async()=>{const p=await provider();const g=providerGate(p,'email');return g||error('Password update binding is not active yet.',501)}],
'POST /api/auth/security/update-email':[requireAuth(),async()=>{const p=await provider();const g=providerGate(p,'email');return g||error('Email update and re-verification binding is not active yet.',501)}],
'POST /api/auth/security/update-phone':[requireAuth(),async()=>{const p=await provider();const g=providerGate(p,'phone');return g||error('Phone update and OTP binding is not active yet.',501)}],
'POST /api/auth/security/mfa/start':[requireAuth(),async()=>{const p=await provider();if(!p.mfaReady)return error('Two-factor enrollment is not configured yet.',503);return error('MFA enrollment binding is not active yet.',501)}]
};