import {db,secrets,json,error,requireAuth} from '@appdeploy/sdk';
type ProviderStatus={supabaseConfigured:boolean;emailPasswordReady:boolean;emailVerificationReady:boolean;phoneOtpReady:boolean;socialFallback:boolean;mfaReady:boolean};type RateRow={count:number;updatedAt:number};type Staff={email:string;role:string;status:string};type ChannelState={emailHash?:string;emailVerifiedAt?:number;phoneHash?:string;phoneLast4?:string;phoneVerifiedAt?:number;updatedAt?:number};type Challenge={hash:string;salt:string;expiresAt:number;attempts:number;createdAt:number};
async function names(){try{return await secrets.listSecretNames()}catch{return []}}
async function provider():Promise<ProviderStatus>{const n=await names();const supabaseConfigured=n.includes('SUPABASE_URL')&&n.includes('SUPABASE_PUBLISHABLE_KEY');const adapterReady=n.includes('HEART_CONNECT_SUPABASE_AUTH_ACTIVE');const phoneOtpReady=n.includes('TWILIO_ACCOUNT_SID')&&n.includes('TWILIO_AUTH_TOKEN')&&n.includes('TWILIO_VERIFY_SERVICE_SID');return{supabaseConfigured,emailPasswordReady:supabaseConfigured&&adapterReady,emailVerificationReady:n.includes('RESEND_API_KEY'),phoneOtpReady,socialFallback:true,mfaReady:supabaseConfigured&&adapterReady&&n.includes('HEART_CONNECT_MFA_ACTIVE')}}
async function digest(v:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('')}
function source(event:any){const h=event?.headers||{};const ip=event?.requestContext?.http?.sourceIp||h['cf-connecting-ip']||h['x-forwarded-for']||'unknown';return String(ip).split(',')[0].trim()}
async function limited(event:any,kind:string,identifier:string,limit:number,windowMs:number){const key=await digest(source(event)+'|'+String(identifier||'').trim().toLowerCase());const bucket=Math.floor(Date.now()/windowMs);const table='auth-rate:'+kind+':'+key+':'+bucket;const cur=(await db.list<RateRow>(table,{limit:1})).items[0];if((cur?.count||0)>=limit)return true;if(cur)await db.update(table,[{id:cur.id,record:{count:(cur.count||0)+1,updatedAt:Date.now()}}]);else await db.add(table,[{count:1,updatedAt:Date.now()}]);return false}
function dobAdult(v:string){const d=new Date(v);if(Number.isNaN(d.getTime()))return false;const n=new Date();let a=n.getUTCFullYear()-d.getUTCFullYear();const m=n.getUTCMonth()-d.getUTCMonth();if(m<0||(m===0&&n.getUTCDate()<d.getUTCDate()))a--;return a>=18}
function providerGate(p:ProviderStatus,feature:'email'|'phone'){if(feature==='email'&&!p.emailPasswordReady)return error(p.supabaseConfigured?'Supabase credentials are detected, but Heart Connect auth activation is intentionally disabled until session binding is completed.':'Heart Connect email/password authentication is prepared but Supabase is not connected yet.',503);if(feature==='phone'&&!p.phoneOtpReady)return error('Phone OTP is not configured. No SMS was sent.',503);return null}
async function admin(email?:string){if(!email)return false;const n=await names();if(!n.includes('HEART_CONNECT_ADMIN_EMAILS'))return false;const raw=await secrets.readSecret('HEART_CONNECT_ADMIN_EMAILS');return raw.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean).includes(email.toLowerCase())}
async function role(email?:string){if(await admin(email))return 'Super Admin';if(!email)return 'User';const rows=await db.list<Staff>('stage7_staff_roles',{limit:200});const s=rows.items.find(x=>x.status==='active'&&x.email?.toLowerCase()===email.toLowerCase());if(!s)return 'User';const r=String(s.role||'').toLowerCase();if(r.includes('moderator')||r.includes('safety'))return 'Moderator';if(r.includes('support'))return 'Support Agent';if(r.includes('admin'))return 'Admin';return 'Support Agent'}
async function securityEvents(uid:string){const r=await db.list<{kind:string;text:string;time:number}>('auth-security-events:'+uid,{limit:20});return r.items.filter(x=>x.kind==='suspicious_login').sort((a,b)=>b.time-a.time).slice(0,10).map(x=>({text:x.text,time:x.time}))}
async function own(uid:string){return (await db.list<{pid:string}>('owner:'+uid,{limit:1})).items[0]}
async function channelState(uid:string){return (await db.list<ChannelState>('auth-verified-channels:'+uid,{limit:1})).items[0]}
async function saveChannelState(uid:string,patch:Partial<ChannelState>){const table='auth-verified-channels:'+uid,cur=await channelState(uid),record={...(cur||{}),...patch,updatedAt:Date.now()};if(cur)await db.update(table,[{id:cur.id,record}]);else await db.add(table,[record]);return record}
async function setProfileVerification(uid:string,kind:'email'|'phone'){const ref=await own(uid);if(!ref)return;const[p]=await db.get<any>('profiles',[ref.pid]);if(!p)return;const v=p.verification||{phone:false,email:false,face:'not_started',identity:'not_started'};await db.update('profiles',[{id:ref.pid,record:{...p,verification:{...v,[kind]:true},updatedAt:Date.now()}}])}
function randomCode(){const n=new Uint32Array(1);crypto.getRandomValues(n);return String(n[0]%1000000).padStart(6,'0')}
function randomSalt(){const n=new Uint8Array(16);crypto.getRandomValues(n);return Array.from(n).map(x=>x.toString(16).padStart(2,'0')).join('')}
function maskEmail(v:string){const[a,b]=v.split('@');return a&&b?(a.slice(0,2)+'***@'+b):'your email'}
function phoneE164(v:string){const p=String(v||'').trim().replace(/[\s().-]/g,'');return /^\+[1-9]\d{7,14}$/.test(p)?p:''}
async function sendEmailCode(uid:string,email:string){const n=await names();if(!n.includes('RESEND_API_KEY'))return{ok:false as const,message:'Email verification is temporarily unavailable.'};const code=randomCode(),salt=randomSalt(),hash=await digest(salt+'|'+code+'|'+uid),table='auth-email-challenge:'+uid,cur=(await db.list<Challenge>(table,{limit:1})).items[0],record:Challenge={hash,salt,expiresAt:Date.now()+10*60*1000,attempts:0,createdAt:Date.now()};if(cur)await db.update(table,[{id:cur.id,record}]);else await db.add(table,[record]);const apiKey=await secrets.readSecret('RESEND_API_KEY'),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+apiKey,'Content-Type':'application/json','Idempotency-Key':'heart-connect-email-verify-'+uid+'-'+record.createdAt},body:JSON.stringify({from:'Heart Connect <noreply@royal-heart.com>',to:[email],subject:'Your Heart Connect verification code',text:'Your Heart Connect verification code is '+code+'. It expires in 10 minutes. If you did not request this code, you can ignore this email. Never share this code with another person.'}),signal:controller.signal});if(!response.ok)return{ok:false as const,message:'The verification email could not be delivered.'};return{ok:true as const,masked:maskEmail(email),expiresAt:record.expiresAt}}catch{return{ok:false as const,message:'The verification email could not be delivered.'}}finally{clearTimeout(timer)}}
async function verifyEmailCode(uid:string,email:string,code:string){const table='auth-email-challenge:'+uid,cur=(await db.list<Challenge>(table,{limit:1})).items[0];if(!cur)return{ok:false as const,message:'Request a new verification code first.'};if(Date.now()>cur.expiresAt)return{ok:false as const,message:'That verification code has expired. Request a new one.'};if(cur.attempts>=5)return{ok:false as const,message:'Too many incorrect attempts. Request a new code.'};const hash=await digest(cur.salt+'|'+code+'|'+uid);if(hash!==cur.hash){await db.update(table,[{id:cur.id,record:{...cur,attempts:cur.attempts+1}}]);return{ok:false as const,message:'The verification code is incorrect.'}}await saveChannelState(uid,{emailHash:await digest(email.toLowerCase()),emailVerifiedAt:Date.now()});await setProfileVerification(uid,'email');await db.delete(table,[cur.id]);return{ok:true as const}}
async function twilioRequest(phone:string){const p=await provider();if(!p.phoneOtpReady)return{ok:false as const,message:'Phone OTP is not configured. No SMS was sent.'};const sid=await secrets.readSecret('TWILIO_ACCOUNT_SID'),token=await secrets.readSecret('TWILIO_AUTH_TOKEN'),service=await secrets.readSecret('TWILIO_VERIFY_SERVICE_SID'),body=new URLSearchParams({To:phone,Channel:'sms'}),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const r=await fetch('https://verify.twilio.com/v2/Services/'+encodeURIComponent(service)+'/Verifications',{method:'POST',headers:{Authorization:'Basic '+btoa(sid+':'+token),'Content-Type':'application/x-www-form-urlencoded'},body:body.toString(),signal:controller.signal});return r.ok?{ok:true as const}:{ok:false as const,message:'The verification SMS could not be sent.'}}catch{return{ok:false as const,message:'The verification SMS could not be sent.'}}finally{clearTimeout(timer)}}
async function twilioCheck(phone:string,code:string){const p=await provider();if(!p.phoneOtpReady)return{ok:false as const,message:'Phone OTP is not configured.'};const sid=await secrets.readSecret('TWILIO_ACCOUNT_SID'),token=await secrets.readSecret('TWILIO_AUTH_TOKEN'),service=await secrets.readSecret('TWILIO_VERIFY_SERVICE_SID'),body=new URLSearchParams({To:phone,Code:code}),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const r=await fetch('https://verify.twilio.com/v2/Services/'+encodeURIComponent(service)+'/VerificationCheck',{method:'POST',headers:{Authorization:'Basic '+btoa(sid+':'+token),'Content-Type':'application/x-www-form-urlencoded'},body:body.toString(),signal:controller.signal});let data:any={};try{data=await r.json()}catch{}return r.ok&&data.status==='approved'?{ok:true as const}:{ok:false as const,message:'The verification code is invalid or expired.'}}catch{return{ok:false as const,message:'Phone verification is temporarily unavailable.'}}finally{clearTimeout(timer)}}
export const authSystemRoutes={
'GET /api/auth/provider-status':[async()=>json(await provider())],
'POST /api/auth/register/preflight':[async c=>{const b=c.body as {firstName?:string;email?:string;phone?:string;dob?:string;country?:string;city?:string;terms?:boolean;privacy?:boolean;ageConfirm?:boolean;passwordPolicy?:{length?:number;upper?:boolean;lower?:boolean;number?:boolean}};if(await limited(c.event,'register',String(b.email||b.phone||''),5,60*60*1000))return error('Too many registration attempts. Try again later.',429);if(!b.firstName?.trim()||!b.email?.includes('@')||!b.phone?.trim()||!b.city?.trim()||!b.country?.trim())return error('Complete all required registration details.',400);if(!b.dob||!dobAdult(b.dob)||b.ageConfirm!==true)return error('Heart Connect is available only to adults aged 18 or older.',400);if(b.terms!==true||b.privacy!==true)return error('Terms and Privacy Policy acceptance are required.',400);const pw=b.passwordPolicy;if(!pw||Number(pw.length)<8||!pw.upper||!pw.lower||!pw.number)return error('Password policy requirements were not met.',400);const p=await provider();const g=providerGate(p,'email');return g||json({ok:true,provider:'supabase'})}],
'POST /api/auth/login/preflight':[async c=>{const b=c.body as {identifier?:string;channel?:string};const id=String(b.identifier||'').trim();if(await limited(c.event,'login',id,10,15*60*1000))return error('Too many sign-in attempts. Try again later.',429);if(!id)return error('Enter your email or phone number.',400);const p=await provider();const g=providerGate(p,b.channel==='phone'?'phone':'email');return g||error('Credential validation is delegated to Supabase and will be activated with the dedicated Heart Connect project.',501)}],
'POST /api/auth/recovery/request':[async c=>{const id=String((c.body as {identifier?:string})?.identifier||'').trim();if(await limited(c.event,'recovery',id,5,60*60*1000))return error('Too many recovery requests. Try again later.',429);if(!id)return error('Enter an email or phone number.',400);const p=await provider();const g=providerGate(p,'email');return g||error('Recovery provider binding is not active yet.',501)}],
'POST /api/auth/password/reset':[async c=>{if(await limited(c.event,'password-reset','token',8,60*60*1000))return error('Too many reset attempts. Try again later.',429);const p=await provider();const g=providerGate(p,'email');return g||error('Secure reset-token validation will be delegated to Supabase after provider activation.',501)}],
'POST /api/auth/email/resend':[async c=>{const email=String((c.body as {email?:string})?.email||'').trim();if(await limited(c.event,'email-verify',email,5,60*60*1000))return error('Too many verification requests. Try again later.',429);const p=await provider();const g=providerGate(p,'email');return g||error('Email verification delivery is not active yet.',501)}],
'POST /api/auth/phone/otp/request':[async c=>{const phone=String((c.body as {phone?:string})?.phone||'').trim();if(await limited(c.event,'otp-send',phone,5,60*60*1000))return error('Too many OTP requests. Try again later.',429);if(!phone)return error('Enter a phone number.',400);const p=await provider();const g=providerGate(p,'phone');return g||error('OTP provider binding is not active yet.',501)}],
'POST /api/auth/phone/otp/verify':[async c=>{const b=c.body as {phone?:string;code?:string};const phone=String(b.phone||'').trim();const code=String(b.code||'').trim();if(await limited(c.event,'otp-verify',phone,8,15*60*1000))return error('Too many OTP attempts. Request a new code later.',429);if(!/^\d{6}$/.test(code))return error('Enter the 6-digit verification code.',400);const p=await provider();const g=providerGate(p,'phone');return g||error('OTP verification provider binding is not active yet.',501)}],
'GET /api/auth/security':[requireAuth(),async c=>{const p=await provider(),ch=await channelState(c.user!.userId);const h=c.event?.headers||{};const ua=String(h['user-agent']||h['User-Agent']||'Unknown browser');const device=/mobile|android|iphone/i.test(ua)?'Mobile device':'Desktop device';const browser=/edg/i.test(ua)?'Edge':/chrome/i.test(ua)?'Chrome':/safari/i.test(ua)?'Safari':/firefox/i.test(ua)?'Firefox':'Browser';const country=String(h['cf-ipcountry']||h['cloudfront-viewer-country']||'Approximate location unavailable');return json({role:await role(c.user!.email),email:c.user!.email,provider:p,mfaReady:p.mfaReady,channels:{emailVerificationReady:p.emailVerificationReady,emailVerified:!!ch?.emailVerifiedAt,emailVerifiedAt:ch?.emailVerifiedAt||null,phoneOtpReady:p.phoneOtpReady,phoneVerified:!!ch?.phoneVerifiedAt,phoneVerifiedAt:ch?.phoneVerifiedAt||null,phoneLast4:ch?.phoneLast4||''},sessions:[{device,browser,approximateLocation:country,lastActive:Date.now(),current:true,expires:'Session expiry is managed by the active identity provider.'}],alerts:await securityEvents(c.user!.userId)})}],
'POST /api/auth/security/email-code/request':[requireAuth(),async c=>{const email=String(c.user!.email||'').trim().toLowerCase();if(!email)return error('Your current sign-in provider did not supply an email address.',400);if(await limited(c.event,'secure-email-code',email,5,60*60*1000))return error('Too many verification emails. Try again later.',429);const r=await sendEmailCode(c.user!.userId,email);return r.ok?json({ok:true,masked:r.masked,expiresAt:r.expiresAt}):error(r.message,502)}],
'POST /api/auth/security/email-code/verify':[requireAuth(),async c=>{const code=String((c.body as {code?:string})?.code||'').trim(),email=String(c.user!.email||'').trim().toLowerCase();if(!/^\d{6}$/.test(code))return error('Enter the 6-digit verification code.',400);if(!email)return error('Your current sign-in provider did not supply an email address.',400);if(await limited(c.event,'secure-email-code-check',email,10,15*60*1000))return error('Too many verification attempts. Try again later.',429);const r=await verifyEmailCode(c.user!.userId,email,code);return r.ok?json({ok:true,verifiedAt:Date.now()}):error(r.message,400)}],
'POST /api/auth/security/phone-code/request':[requireAuth(),async c=>{const phone=phoneE164(String((c.body as {phone?:string})?.phone||''));if(!phone)return error('Enter a phone number in international format, for example +2547XXXXXXXX.',400);if(await limited(c.event,'secure-phone-code',phone,5,60*60*1000))return error('Too many SMS requests. Try again later.',429);const r=await twilioRequest(phone);if(!r.ok)return error(r.message,503);return json({ok:true,phoneLast4:phone.slice(-4)})}],
'POST /api/auth/security/phone-code/verify':[requireAuth(),async c=>{const b=c.body as {phone?:string;code?:string},phone=phoneE164(String(b.phone||'')),code=String(b.code||'').trim();if(!phone)return error('Enter a valid phone number in international format.',400);if(!/^\d{4,10}$/.test(code))return error('Enter the verification code sent to your phone.',400);if(await limited(c.event,'secure-phone-code-check',phone,10,15*60*1000))return error('Too many verification attempts. Try again later.',429);const r=await twilioCheck(phone,code);if(!r.ok)return error(r.message,400);await saveChannelState(c.user!.userId,{phoneHash:await digest(phone),phoneLast4:phone.slice(-4),phoneVerifiedAt:Date.now()});await setProfileVerification(c.user!.userId,'phone');return json({ok:true,phoneLast4:phone.slice(-4),verifiedAt:Date.now()})}],
'POST /api/auth/security/logout-all':[requireAuth(),async()=>{const p=await provider();if(!p.emailPasswordReady)return error('Cross-device session revocation requires the dedicated Supabase identity provider.',503);return error('Cross-device revocation binding is not active yet.',501)}],
'POST /api/auth/security/change-password':[requireAuth(),async()=>{const p=await provider();const g=providerGate(p,'email');return g||error('Password update binding is not active yet.',501)}],
'POST /api/auth/security/update-email':[requireAuth(),async()=>json({ok:true,next:'Use /api/auth/security/email-code/request to reconfirm the current provider email.'})],
'POST /api/auth/security/update-phone':[requireAuth(),async()=>{const p=await provider();return p.phoneOtpReady?json({ok:true,next:'Use /api/auth/security/phone-code/request with an E.164 phone number.'}):error('Phone verification is prepared, but Twilio Verify credentials are not configured yet.',503)}],
'POST /api/auth/security/mfa/start':[requireAuth(),async()=>{const p=await provider();if(!p.mfaReady)return error('Two-factor enrollment is not configured yet.',503);return error('MFA enrollment binding is not active yet.',501)}]
};