import { secrets } from '@appdeploy/sdk';
export type NormalizedLocation={provider:'mapbox'|'manual'|'legacy';providerPlaceId?:string;countryCode:string;countryName:string;region:string;city:string;locality:string;timezone:string;latitude?:number;longitude?:number;displayName:string;precision:'country'|'region'|'city'|'locality';updatedAt:number};
export type LocationSuggestion={provider:'mapbox';providerPlaceId:string;countryCode:string;countryName:string;region:string;city:string;locality:string;displayName:string;precision:string;query:string};
async function token(){const names=await secrets.listSecretNames();if(!names.includes('MAPBOX_ACCESS_TOKEN'))return '';try{return await secrets.readSecret('MAPBOX_ACCESS_TOKEN')}catch{return ''}}
function pickContext(ctx:any,key:string){if(!ctx)return null;if(Array.isArray(ctx)){const x=ctx.find((v:any)=>String(v?.id||v?.mapbox_id||'').startsWith(key+'.')||v?.feature_type===key);return x||null}return ctx[key]||null}
function normalizeFeature(f:any):NormalizedLocation{const p=f?.properties||{},ctx=p.context||f?.context||{},country=pickContext(ctx,'country'),region=pickContext(ctx,'region'),place=pickContext(ctx,'place'),locality=pickContext(ctx,'locality'),kind=String(p.feature_type||f?.place_type?.[0]||'place'),coords=p.coordinates||{},lon=Number(coords.longitude??f?.geometry?.coordinates?.[0]),lat=Number(coords.latitude??f?.geometry?.coordinates?.[1]),countryName=String(country?.name||country?.text||p.country||''),countryCode=String(country?.country_code||country?.short_code||p.country_code||'').toUpperCase(),regionName=String(region?.name||region?.text||p.region||''),cityName=String(kind==='place'?p.name||f?.text:place?.name||place?.text||p.place||''),localityName=String(kind==='locality'?p.name||f?.text:locality?.name||locality?.text||''),display=String(p.full_address||p.place_formatted||f?.place_name||[localityName,cityName,regionName,countryName].filter(Boolean).join(', ')),precision=(kind==='country'?'country':kind==='region'||kind==='district'?'region':kind==='locality'||kind==='neighborhood'?'locality':'city') as NormalizedLocation['precision'];return {provider:'mapbox',providerPlaceId:String(p.mapbox_id||f?.id||''),countryCode,countryName,region:regionName,city:cityName||localityName||regionName||countryName,locality:localityName,timezone:'',latitude:Number.isFinite(lat)?lat:undefined,longitude:Number.isFinite(lon)?lon:undefined,displayName:display||cityName||countryName,precision,updatedAt:Date.now()}}
async function request(url:string){const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok){const text=await r.text().catch(()=>String(r.status));throw new Error('Location provider request failed: '+r.status+' '+text.slice(0,120))}return await r.json() as any}
export async function locationProviderStatus(){const t=await token();return {provider:t?'mapbox':'manual',configured:!!t,serverSide:true,autocomplete:!!t,reverseGeocoding:!!t,permanentSelectionStorage:!!t,note:t?'Mapbox is configured behind the Heart Connect backend. Exact member coordinates are never returned to other members.':'Mapbox is not configured yet. Manual city/region/country entry remains available and existing locations are preserved.'}}
export async function searchLocations(query:string,countryCode?:string){const t=await token();if(!t)return [] as LocationSuggestion[];const q=query.trim();if(q.length<3)return [];const u=new URL('https://api.mapbox.com/search/geocode/v6/forward');u.searchParams.set('q',q);u.searchParams.set('access_token',t);u.searchParams.set('autocomplete','true');u.searchParams.set('types','place,locality,district,region,country');u.searchParams.set('limit','8');if(countryCode)u.searchParams.set('country',countryCode.toLowerCase());const d=await request(u.toString());return (d.features||[]).slice(0,8).map((f:any)=>{const n=normalizeFeature(f);return {provider:'mapbox' as const,providerPlaceId:n.providerPlaceId||'',countryCode:n.countryCode,countryName:n.countryName,region:n.region,city:n.city,locality:n.locality,displayName:n.displayName,precision:n.precision,query:n.displayName}})}
export async function resolveLocation(query:string,countryCode?:string){const t=await token();if(!t)throw new Error('Location provider is not configured.');const u=new URL('https://api.mapbox.com/search/geocode/v6/forward');u.searchParams.set('q',query.trim());u.searchParams.set('access_token',t);u.searchParams.set('autocomplete','false');u.searchParams.set('permanent','true');u.searchParams.set('types','place,locality,district,region,country');u.searchParams.set('limit','1');if(countryCode)u.searchParams.set('country',countryCode.toLowerCase());const d=await request(u.toString()),f=d.features?.[0];if(!f)throw new Error('Location could not be resolved.');return normalizeFeature(f)}
export async function reverseLocation(latitude:number,longitude:number){const t=await token();if(!t)throw new Error('Location provider is not configured.');const u=new URL('https://api.mapbox.com/search/geocode/v6/reverse');u.searchParams.set('latitude',String(latitude));u.searchParams.set('longitude',String(longitude));u.searchParams.set('access_token',t);u.searchParams.set('permanent','true');u.searchParams.set('types','place,locality,district,region,country');const d=await request(u.toString()),f=d.features?.[0];if(!f)throw new Error('Current location could not be converted to a safe place label.');return normalizeFeature(f)}