import { db,error,json,storage } from '@appdeploy/sdk';
import { requireHeartAuth as requireAuth } from './heart-auth';
import { notifySubscribers } from './realtime-subscribers';import {notificationPreview,privacyFor,verifiedProfile} from './messaging-privacy';
type Profile={owner:string;name:string;verification?:{face?:string;identity?:string};suspendedPermanent?:boolean;suspendedUntil?:number};type Pair={likes:string[];blocked:boolean};type VoiceNote={path:string;contentType:string;size:number;duration:number};type Msg={sender:string;text:string;time:number;clientId?:string;deliveredAt?:number;readAt?:number;reactions?:Record<string,string[]>;deletedAt?:number;voiceNote?:VoiceNote};
async function own(uid:string){return (await db.list<{pid:string}>('owner:'+uid,{limit:1})).items[0]}async function one<T=Record<string,any>>(table:string){return (await db.list<T>(table,{limit:1})).items[0]}
async function mutual(uid:string,targetId:string){const ref=await own(uid);if(!ref)return null;const [[mine],[target]]=await Promise.all([db.get<Profile>('profiles',[ref.pid]),db.get<Profile>('profiles',[targetId])]);if(!mine||!target||target.owner===uid||mine.suspendedPermanent===true||Number(mine.suspendedUntil||0)>Date.now())return null;const key=[ref.pid,targetId].sort().join(':'),state=await one<Pair>('pair:'+key);if(!state||state.blocked||!state.likes.includes(ref.pid)||!state.likes.includes(targetId))return null;return{uid,key,mine:ref.pid,mineProfile:mine,targetId,target,targetOwner:target.owner}}
function clean(v:string){return v.trim().replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80)}function approxBytes(base64:string){return Math.ceil(base64.length*3/4)}function extension(ct:string){return ct.includes('webm')?'webm':ct.includes('mpeg')?'mp3':ct.includes('ogg')?'ogg':'m4a'}
async function exposed(id:string,x:Msg){const voiceNote=x.voiceNote?{contentType:x.voiceNote.contentType,size:x.voiceNote.size,duration:x.voiceNote.duration,messageId:id}:null;return{id,sender:x.sender,text:'',time:Number(x.time)||0,clientId:x.clientId||'',deliveredAt:Number(x.deliveredAt)||0,readAt:Number(x.readAt)||0,reactions:x.reactions||{},deletedAt:Number(x.deletedAt)||0,voiceNote}}
async function rate(uid:string){const bucket=Math.floor(Date.now()/(60*60*1000)),table='voice_rate:'+uid+':'+bucket,cur=await one<{count:number}>(table);if((cur?.count||0)>=40)return false;if(cur)await db.update(table,[{id:cur.id,record:{count:(cur.count||0)+1}}]);else await db.add(table,[{count:1}]);return true}
export const messagingVoiceRoutes={
 'GET /api/messaging/conversations/:id/messages/:messageId/voice-content':[requireAuth(),async c=>{const m=await mutual(c.user!.userId,c.params.id);if(!m)return error('Voice notes are available only to active mutual matches.',403);const[x]=await db.get<Msg>('messages:'+m.key,[c.params.messageId]);if(!x||x.deletedAt||!x.voiceNote?.path)return error('Voice note unavailable.',404);const[f]=await storage.read([x.voiceNote.path]);if(!f?.content)return error('Voice note unavailable.',404);return json({content:f.content,contentType:x.voiceNote.contentType})}],
 'POST /api/messaging/conversations/:id/voice':[requireAuth(),async c=>{if(!(await rate(c.user!.userId)))return error('Voice-note limit reached. Try again later.',429);const m=await mutual(c.user!.userId,c.params.id);if(!m)return error('Voice notes require an active mutual match.',403);if((await privacyFor(m.targetOwner)).verifiedOnlyMessaging&&!verifiedProfile(m.mineProfile))return error('This member accepts voice notes only from verified Heart Connect members.',403);const b=c.body as any,data=String(b.data||''),contentType=String(b.contentType||''),duration=Math.max(0,Number(b.duration)||0),cid=clean(String(b.clientId||''));if(cid.length<8||!data)return error('Invalid voice note.',400);if(!['audio/webm','audio/mp4','audio/mpeg','audio/ogg'].includes(contentType))return error('Unsupported voice-note format.',400);if(duration<=0||duration>120)return error('Voice notes must be 2 minutes or shorter.',400);const size=approxBytes(data);if(size>3_200_000)return error('Voice note is too large. Keep it under about 3 MB.',400);const idem=await one<any>('message_idempotency:'+c.user!.userId+':'+cid);if(idem){if(idem.conversationKey!==m.key)return error('Voice-note retry key belongs to another conversation.',409);const [existing]=await db.get<Msg>('messages:'+m.key,[String(idem.messageId||'')]);if(existing)return json({ok:true,idempotent:true,message:await exposed(String(idem.messageId),existing)})}const path='chat-voice/'+m.key.replaceAll(':','_')+'/'+cid+'.'+extension(contentType);if(!(await storage.write([{path,content:data,contentType}]))[0])return error('Secure voice-note upload failed.',500);const now=Date.now(),voiceNote:VoiceNote={path,contentType,size,duration},item:Msg={sender:m.mine,text:'',time:now,clientId:cid,deliveredAt:0,readAt:0,reactions:{},voiceNote},[id]=await db.add('messages:'+m.key,[item]);if(!id){await storage.delete([path]);return error('Voice note could not be saved.',500)}await db.add('message_idempotency:'+c.user!.userId+':'+cid,[{conversationKey:m.key,messageId:id,createdAt:now}]);const out=await exposed(id,item);await notifySubscribers('conversation',m.key,{kind:'message.created',message:out},String(b.connectionId||'')||undefined);await notifySubscribers('user',m.targetId,{kind:'message',profileId:m.mine,conversationId:m.key,message:out});const n=await notificationPreview(m.targetOwner,m.mineProfile.name,'voice');await db.add('notifications:'+m.targetOwner,[{type:'message',text:n.text,time:now,profileId:m.mine,previewMode:n.previewMode,private:n.private,pushReady:true}]);return json({ok:true,idempotent:false,message:out})}]
};