import {adminHtml as adminHtmlV9} from './admin-ui-v9.js';

export function adminHtml(version){
  const upgrade=`<style>
.hc10-nav-search{margin:8px 4px 10px;position:relative}.hc10-nav-search input{width:100%;border:1px solid #ffffff18;background:#070b12;color:#f4f6fb;border-radius:11px;padding:10px 34px 10px 11px;font-size:12px;outline:none}.hc10-nav-search input:focus{border-color:#ef548060;box-shadow:0 0 0 3px #ef548014}.hc10-nav-search kbd{position:absolute;right:9px;top:8px;border:1px solid #ffffff18;background:#101722;color:#8f9caf;border-radius:6px;padding:2px 5px;font:10px ui-monospace,SFMono-Regular,Menlo,monospace}.hc10-runtime{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin:10px 0 2px}.hc10-runtime span{display:inline-flex;align-items:center;gap:6px;border:1px solid #ffffff13;background:#0a1019;border-radius:999px;padding:6px 9px;color:#aab5c7;font-size:11px}.hc10-runtime i{display:inline-block;width:7px;height:7px;border-radius:50%;background:#657186}.hc10-runtime .ok i{background:#42d392}.hc10-runtime .warn i{background:#ffc861}.hc10-top-meta{display:inline-flex;align-items:center;color:#7f8ca1;font-size:11px;white-space:nowrap}.hc10-command{position:fixed;inset:0;z-index:2200;background:#03060bb8;backdrop-filter:blur(9px);display:none;align-items:flex-start;justify-content:center;padding:12vh 18px 24px}.hc10-command.open{display:flex}.hc10-command-card{width:min(680px,100%);overflow:hidden;border:1px solid #ffffff1e;background:#0e1520;border-radius:18px;box-shadow:0 30px 90px #000b}.hc10-command-head{display:flex;align-items:center;gap:10px;padding:13px;border-bottom:1px solid #ffffff12}.hc10-command-head input{flex:1;border:0;background:transparent;color:#fff;font-size:16px;padding:7px;outline:0}.hc10-command-head kbd{color:#8592a7;border:1px solid #ffffff18;background:#080d15;border-radius:7px;padding:4px 7px;font:11px ui-monospace,SFMono-Regular,Menlo,monospace}.hc10-command-list{max-height:52vh;overflow:auto;padding:8px}.hc10-command-item{width:100%;display:flex;align-items:center;justify-content:space-between;gap:16px;border:1px solid transparent;background:transparent;color:#eef2f8;border-radius:10px;padding:10px 11px;text-align:left;cursor:pointer}.hc10-command-item:hover,.hc10-command-item:focus{background:#ffffff08;border-color:#ffffff0d;outline:0}.hc10-command-item small{color:#7e8aa0}.hc10-command-empty{padding:22px;color:#8995a8;text-align:center}.hc10-toolbar-btn{min-width:42px}.hc10-density-compact .panel{padding:14px}.hc10-density-compact .card{min-height:84px;padding:13px}.hc10-density-compact .row{padding-top:8px;padding-bottom:8px}.hc10-density-compact .main{padding-top:18px}.hc10-shortcut-note{margin:12px 8px 0;color:#66748a;font-size:10px;line-height:1.45}.hc10-skip{position:fixed;left:16px;top:-80px;z-index:3000;background:#fff;color:#111;padding:9px 12px;border-radius:8px;font-weight:800;transition:top .15s}.hc10-skip:focus{top:12px}.hc10-highlight{background:#ef3f7217!important;border-color:#ef3f7230!important}
@media(max-width:1080px){.hc10-nav-search{min-width:210px}.hc10-shortcut-note{display:none}.hc10-runtime{margin-bottom:7px}}
@media(max-width:720px){.hc10-top-meta{display:none}.hc10-command{padding-top:8vh}.hc10-runtime span{font-size:10px}.hc10-nav-search{min-width:180px}}
</style><script>
(()=>{
  const sections=['Overview','Users','Analytics','Moderation','Verification','Security Review','Payments','Markets','Content & CMS','Pages','Content Trash','Notifications','Automation & AI','AI Copilot','Command Center','Reports & Search','Staff & Roles','Settings','Audit Log'];
  const sectionHints={
    'Overview':'Dashboard and activity','Users':'Members and account controls','Analytics':'Operational metrics','Moderation':'Safety reports','Verification':'Identity review','Security Review':'Permissions and launch evidence','Payments':'Payment activity','Markets':'Country rollout controls','Content & CMS':'Posts and publishing','Pages':'Public site pages','Content Trash':'Restore deleted content','Notifications':'Member communications','Automation & AI':'Scheduled operations','AI Copilot':'Advisory AI workspace','Command Center':'Health and readiness','Reports & Search':'Global operational search','Staff & Roles':'Admin access management','Settings':'Platform configuration','Audit Log':'Administrative evidence'
  };
  function byText(name){return [...document.querySelectorAll('#nav button')].find(b=>b.textContent.trim()===name)}
  function go(name){const b=byText(name);if(b){b.click();closeCommand();setTimeout(()=>b.scrollIntoView({block:'nearest'}),80)}}
  function ensureSkip(){if(document.querySelector('.hc10-skip'))return;const a=document.createElement('a');a.className='hc10-skip';a.href='#view';a.textContent='Skip to admin content';document.body.prepend(a);const view=document.getElementById('view');if(view&&!view.hasAttribute('tabindex'))view.tabIndex=-1}
  function ensureNavSearch(){const nav=document.getElementById('nav');if(!nav||document.getElementById('hc10NavSearch'))return;const box=document.createElement('div');box.className='hc10-nav-search';box.innerHTML='<input id="hc10NavSearch" type="search" autocomplete="off" aria-label="Filter admin sections" placeholder="Find a section…"><kbd>⌘K</kbd>';nav.parentNode.insertBefore(box,nav);const note=document.createElement('div');note.className='hc10-shortcut-note';note.textContent='Tip: Ctrl/⌘ + K opens the command menu from anywhere.';nav.insertAdjacentElement('afterend',note);const input=box.querySelector('input');input.oninput=()=>{const q=input.value.trim().toLowerCase();document.querySelectorAll('#nav button').forEach(b=>{b.style.display=!q||b.textContent.toLowerCase().includes(q)?'':''});document.querySelectorAll('#nav .hc9-nav-group').forEach(g=>{let n=g.nextElementSibling,shown=false;while(n&&!n.classList.contains('hc9-nav-group')){if(n.tagName==='BUTTON'&&n.style.display!=='none')shown=true;n=n.nextElementSibling}g.style.display=shown?'':'none'})};input.addEventListener('keydown',e=>{if(e.key==='Enter'){const first=[...document.querySelectorAll('#nav button')].find(b=>b.style.display!=='none');if(first){first.click();input.value='';input.dispatchEvent(new Event('input'))}}})}
  function commandMarkup(){return '<div class="hc10-command" id="hc10Command" aria-hidden="true"><div class="hc10-command-card" role="dialog" aria-modal="true" aria-labelledby="hc10CommandLabel"><div class="hc10-command-head"><input id="hc10CommandInput" aria-label="Command menu search" placeholder="Jump to a section…"><kbd>ESC</kbd></div><div class="hc10-command-list" id="hc10CommandList"></div></div></div>'}
  function renderCommands(q=''){const list=document.getElementById('hc10CommandList');if(!list)return;const available=sections.filter(s=>byText(s)&&(!q||s.toLowerCase().includes(q.toLowerCase())||String(sectionHints[s]||'').toLowerCase().includes(q.toLowerCase())));list.innerHTML=available.length?available.map(s=>'<button class="hc10-command-item" type="button" data-hc10-go="'+s.replace(/"/g,'&quot;')+'"><span><b>'+s+'</b><br><small>'+sectionHints[s]+'</small></span><small>Open</small></button>').join(''):'<div class="hc10-command-empty">No matching admin section.</div>';list.querySelectorAll('[data-hc10-go]').forEach(b=>b.onclick=()=>go(b.dataset.hc10Go))}
  function openCommand(){const el=document.getElementById('hc10Command');if(!el)return;el.classList.add('open');el.setAttribute('aria-hidden','false');renderCommands('');const input=document.getElementById('hc10CommandInput');input.value='';setTimeout(()=>input.focus(),0)}
  function closeCommand(){const el=document.getElementById('hc10Command');if(!el)return;el.classList.remove('open');el.setAttribute('aria-hidden','true')}
  function ensureCommand(){if(document.getElementById('hc10Command'))return;document.body.insertAdjacentHTML('beforeend',commandMarkup());const el=document.getElementById('hc10Command'),input=document.getElementById('hc10CommandInput');el.addEventListener('mousedown',e=>{if(e.target===el)closeCommand()});input.addEventListener('input',()=>renderCommands(input.value));input.addEventListener('keydown',e=>{if(e.key==='Enter'){const b=document.querySelector('#hc10CommandList [data-hc10-go]');if(b)b.click()}});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand()}else if(e.key==='Escape')closeCommand()})}
  async function ensureRuntime(){const actor=document.getElementById('actor');if(!actor||document.getElementById('hc10Runtime'))return;const box=document.createElement('div');box.id='hc10Runtime';box.className='hc10-runtime';box.innerHTML='<span><i></i>Checking secure runtime…</span>';const summary=document.getElementById('hc9SectionSummary');(summary||actor).insertAdjacentElement('afterend',box);try{const r=await fetch('/api/admin/runtime',{credentials:'same-origin',headers:{accept:'application/json'}}),d=await r.json();if(!r.ok)throw new Error();const chip=(label,ok,detail)=>'<span class="'+(ok?'ok':'warn')+'" title="'+detail+'"><i></i>'+label+'</span>';box.innerHTML=chip(d.environment==='live'?'Live environment':'Preview environment',true,'Current deployment environment')+chip('Admin data '+(d.serviceRoleConfigured?'connected':'not configured'),!!d.serviceRoleConfigured,'Server-side Admin data connection')+chip('Owner access '+(d.ownerAllowlistConfigured?'configured':'not configured'),!!d.ownerAllowlistConfigured,'Owner allow-list configuration')+chip('AI '+(d.workersAIConfigured?'available':'optional'),true,d.workersAIConfigured?'Workers AI binding detected':'Workers AI is optional and not required for core Admin operations')}catch{box.innerHTML='<span class="warn"><i></i>Runtime status unavailable</span>'}}
  function ensureTopTools(){const top=document.getElementById('hc9TopActions');if(!top)return;if(!document.getElementById('hc10CommandButton')){const b=document.createElement('button');b.id='hc10CommandButton';b.className='btn hc10-toolbar-btn';b.type='button';b.title='Command menu (Ctrl/⌘ K)';b.setAttribute('aria-label','Open command menu');b.textContent='⌘K';b.onclick=openCommand;top.insertBefore(b,top.firstChild)}if(!document.getElementById('hc10Density')){const b=document.createElement('button');b.id='hc10Density';b.className='btn hc10-toolbar-btn';b.type='button';b.title='Toggle compact layout';b.setAttribute('aria-label','Toggle compact layout');b.textContent='Density';b.onclick=()=>{const compact=document.body.classList.toggle('hc10-density-compact');localStorage.setItem('hc-admin-density',compact?'compact':'comfortable');b.textContent=compact?'Comfort':'Density'};top.insertBefore(b,document.getElementById('hc9Refresh'))}if(!document.getElementById('hc10Updated')){const t=document.createElement('span');t.id='hc10Updated';t.className='hc10-top-meta';t.textContent='Updated now';top.insertBefore(t,document.getElementById('hc9SignOut'))}const compact=localStorage.getItem('hc-admin-density')==='compact';document.body.classList.toggle('hc10-density-compact',compact);const d=document.getElementById('hc10Density');if(d)d.textContent=compact?'Comfort':'Density';const refresh=document.getElementById('hc9Refresh');if(refresh&&!refresh.dataset.hc10){refresh.dataset.hc10='1';refresh.addEventListener('click',()=>setTimeout(()=>{const t=document.getElementById('hc10Updated');if(t)t.textContent='Updated now'},650),true)}}
  function syncTitle(){const h=document.getElementById('title');if(!h)return;const name=h.textContent.trim();document.title='Heart Connect Admin · '+name;const active=byText(name);document.querySelectorAll('#nav button').forEach(b=>b.removeAttribute('aria-current'));if(active)active.setAttribute('aria-current','page')}
  function highlightCritical(){document.querySelectorAll('.notice,.hc9-danger-note').forEach(n=>{if(/required|failed|critical|danger|not configured|access denied/i.test(n.textContent||''))n.classList.add('hc10-highlight')})}
  let init=false;function enhance(){ensureSkip();ensureNavSearch();ensureCommand();ensureTopTools();syncTitle();highlightCritical();if(!init){init=true;ensureRuntime()}}
  const observer=new MutationObserver(()=>requestAnimationFrame(enhance));observer.observe(document.body,{childList:true,subtree:true,characterData:true});enhance();
})();
</script>`;
  return adminHtmlV9(version).replace('</body>',upgrade+'</body>');
}
