import {handleAdmin as handleAdminV6,runPhase6AndPhase5Scheduled} from './admin-api-v6.js';
import {adminHtml} from './admin-ui-v7.js';

export const VERSION='hc-admin-control-plane-v7';
const ACCESS_COOKIE='__Host-hc_cf_access';
const DEFAULT_SUPABASE_URL='https://zzhzkikezjtbntaqiurk.supabase.co';
const DEFAULT_PUBLISHABLE_KEY='sb_publishable_HB0Irz6bxug1hHs518oPZQ_LC83i4qT';
const ALL_ADMIN_ROLES=['owner','super_admin','admin','moderator','senior_moderator','safety_specialist','payment_specialist','support_agent','content_manager','verification_specialist','finance'];
const SECURITY_REVIEW_ROLES=['owner','super_admin'];
const REPORT_ROLES=['owner','super_admin','admin','senior_moderator','safety_specialist','payment_specialist','verification_specialist','finance','content_manager'];
const ROLE_MATRIX={
  owner:['all'],
  super_admin:['all'],
  admin:['overview','users','payments','markets','moderation','verification','cms','notifications','analytics','settings','audit','ai','incidents','reports','exports'],
  moderator:['overview','users:read','moderation'],
  senior_moderator:['overview','users:read','moderation','verification:read','audit:read','incidents','reports:moderation'],
  safety_specialist:['overview','users:read','moderation','verification','audit:read','incidents','reports:moderation'],
  payment_specialist:['overview','users:read','payments','audit:read','incidents:payments','reports:payments'],
  support_agent:['overview','users:read','notifications:read'],
  content_manager:['overview','cms','notifications','analytics:read','reports:content'],
  verification_specialist:['overview','users:read','verification','audit:read','reports:verification'],
  finance:['overview','users:read','payments','analytics:read','audit:read','reports:payments']
};
const EXPORT_ROLES={
  users:['owner','super_admin','admin'],
  moderation:['owner','super_admin','admin','senior_moderator','safety_specialist'],
  verification:['owner','super_admin','admin','verification_specialist','safety_specialist'],
  payments:['owner','super_admin','admin','payment_specialist','finance'],
  notifications:['owner','super_admin','admin','content_manager'],
  audit:['owner','super_admin','admin'],
  incidents:['owner','super_admin','admin','senior_moderator','safety_specialist','payment_specialist']
};
const DATASETS={
  users:{table:'dating_profiles',date:'created_at',order:'created_at.desc',select:'user_id,display_name,country,city,relationship_intention,verification_level,profile_completion,is_discoverable,last_active_at,created_at'},
  moderation:{table:'reports',date:'created_at',order:'created_at.desc',select:'id,reported_user_id,category,status,created_at,reviewed_at,reviewed_by'},
  verification:{table:'verification_requests',date:'submitted_at',order:'submitted_at.desc',select:'id,user_id,verification_type,status,submitted_at,reviewed_at,reviewed_by,rejection_reason'},
  notifications:{table:'hc_notification_delivery_queue',date:'created_at',order:'created_at.desc',select:'id,campaign_id,recipient_user_id,channel,status,provider,attempt_count,error_code,sent_at,created_at,updated_at'},
  audit:{table:'hc_admin_audit_log',date:'created_at',order:'created_at.desc',select:'id,actor_email,actor_role,action,target,reason,created_at'},
  incidents:{table:'hc_admin_incidents',date:'detected_at',order:'detected_at.desc',select:'id,category,severity,status,source,title,summary,detected_at,last_seen_at,acknowledged_at,resolved_at'}
};
const PAYMENT_SAFE_FIELDS=['id','user_id','customer_id','profile_id','provider','kind','type','status','amount','amount_minor','currency','reference','transaction_reference','provider_reference','external_id','created_at','updated_at','paid_at','failed_at','refunded_at'];

function cfg(env){return{url:String(env.SUPABASE_URL||DEFAULT_SUPABASE_URL).replace(/\/+$/,''),publishable:String(env.SUPABASE_PUBLISHABLE_KEY||DEFAULT_PUBLISHABLE_KEY),service:String(env.SUPABASE_SERVICE_ROLE_KEY||'')}}
function cookies(request){const out={};for(const part of String(request.headers.get('cookie')||'').split(';')){const i=part.indexOf('=');if(i>0){const k=part.slice(0,i).trim();try{out[k]=decodeURIComponent(part.slice(i+1).trim())}catch{out[k]=part.slice(i+1).trim()}}}return out}
function j(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-heart-connect-admin':VERSION,...extra}})}
function page(html,status=200){return new Response(html,{status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'same-origin','x-frame-options':'DENY','content-security-policy':"default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'",'x-heart-connect-admin':VERSION}})}
function text(v,n=1000){return String(v??'').trim().slice(0,n)}
function email(v){const s=text(v,320).toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)?s:''}
function emails(v){return String(v||'').split(',').map(email).filter(Boolean)}
function uuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''))}
function clean(v){if(Array.isArray(v))return v.slice(0,100).map(clean);if(v&&typeof v==='object'){const out={};for(const [k,x] of Object.entries(v)){if(/secret|password|token|authorization|api.?key|private.?key|credential|evidence_path|media_path/i.test(k))continue;out[text(k,100)]=clean(x)}return out}if(typeof v==='string')return v.slice(0,5000);if(typeof v==='number'||typeof v==='boolean'||v===null)return v;return String(v??'').slice(0,5000)}
function missing(r){return r?.status===404||/does not exist|relation .* does not exist|PGRST205/i.test(String(r?.data?.message||r?.data?.error||r?.data||''))}
function unsafe(request){return !['GET','HEAD','OPTIONS'].includes(request.method)}
function sameOrigin(request){if(!unsafe(request))return true;const site=request.headers.get('sec-fetch-site');if(site==='cross-site')return false;const origin=request.headers.get('origin');if(!origin)return true;try{return new URL(origin).origin===new URL(request.url).origin}catch{return false}}
async function jsonBody(request,max=50000){const raw=await request.text();if(raw.length>max)throw Object.assign(new Error('Request is too large.'),{status:413});try{return raw?JSON.parse(raw):{}}catch{throw Object.assign(new Error('Valid JSON is required.'),{status:400})}}
async function session(request,env){const c=cfg(env),token=cookies(request)[ACCESS_COOKIE]||'';if(!token)return null;try{const r=await fetch(c.url+'/auth/v1/user',{headers:{apikey:c.publishable,authorization:'Bearer '+token,accept:'application/json'}});if(!r.ok)return null;const u=await r.json();return u?.id?{id:u.id,email:email(u.email)}:null}catch{return null}}
async function svc(env,path,{method='GET',body,headers:extra}={}){const c=cfg(env);if(!c.service)return{ok:false,status:503,data:{message:'Admin data service is not configured.'},headers:new Headers()};const headers=new Headers({apikey:c.service,authorization:'Bearer '+c.service,accept:'application/json',...(extra||{})});if(body!==undefined)headers.set('content-type','application/json');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(c.url+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body),signal:controller.signal});const raw=await r.text();let data=null;try{data=raw?JSON.parse(raw):null}catch{data=raw}return{ok:r.ok,status:r.status,data,headers:r.headers}}catch(e){return{ok:false,status:503,data:{message:e?.name==='AbortError'?'Supabase admin request timed out.':'Supabase admin service is temporarily unavailable.'},headers:new Headers()}}finally{clearTimeout(timer)}}
async function actor(request,env){const u=await session(request,env);if(!u)return null;const owners=[...emails(env.HEART_CONNECT_OWNER_EMAILS),...emails(env.HEART_CONNECT_ADMIN_EMAILS)];if(owners.includes(u.email))return{...u,role:'owner',displayName:'Platform Owner'};const r=await svc(env,'/rest/v1/hc_admin_staff?select=role,status,display_name&user_id=eq.'+encodeURIComponent(u.id)+'&status=eq.active&limit=1'),row=r.ok&&Array.isArray(r.data)?r.data[0]:null;return row?{...u,role:String(row.role||''),displayName:text(row.display_name,100)||u.email}:null}
async function requireRoles(request,env,roles){const a=await actor(request,env);if(!a)return{error:j({error:'Admin access denied.'},403)};if(!roles.includes(a.role))return{error:j({error:'Your admin role does not allow this Phase 7 action.',role:a.role},403),actor:a};return{actor:a}}
async function audit(env,a,action,target='',reason='',metadata={}){if(!a)return;await svc(env,'/rest/v1/hc_admin_audit_log',{method:'POST',body:{actor_user_id:a.id,actor_email:a.email,actor_role:a.role,action:text(action,120),target:text(target,240),reason:text(reason,1000)||null,metadata:clean(metadata),created_at:new Date().toISOString()},headers:{Prefer:'return=minimal'}}).catch(()=>{})}
async function count(env,table,column='id',filter=''){const r=await svc(env,'/rest/v1/'+table+'?select='+encodeURIComponent(column)+'&limit=1'+(filter?'&'+filter:''),{headers:{Prefer:'count=exact',Range:'0-0'}});if(!r.ok)return{ok:false,value:null,missing:missing(r),response:r};const cr=String(r.headers.get('content-range')||''),n=Number(cr.split('/')[1]);return{ok:true,value:Number.isFinite(n)?n:(Array.isArray(r.data)?r.data.length:0),missing:false,response:r}}
async function list(env,table,select,order='created_at.desc',limit=100,filter=''){return svc(env,'/rest/v1/'+table+'?select='+encodeURIComponent(select)+(filter?'&'+filter:'')+'&order='+encodeURIComponent(order)+'&limit='+Math.max(1,Math.min(1000,Number(limit)||100)))}
function safeSearchTerm(v){return text(v,80).replace(/[(),*]/g,' ').replace(/\s+/g,' ').trim()}
function rangeFromUrl(u,dateColumn){const days=Math.max(1,Math.min(365,Number(u.searchParams.get('days'))||30));let from=u.searchParams.get('from'),to=u.searchParams.get('to');const parse=x=>{const d=new Date(String(x||''));return Number.isNaN(d.getTime())?null:d.toISOString()};from=parse(from)||new Date(Date.now()-days*86400000).toISOString();to=parse(to)||new Date().toISOString();if(Date.parse(from)>Date.parse(to)){const t=from;from=to;to=t}return{from,to,filter:`${dateColumn}=gte.${encodeURIComponent(from)}&${dateColumn}=lte.${encodeURIComponent(to)}`}}
function csvCell(v){if(v==null)return'';const s=typeof v==='object'?JSON.stringify(v):String(v);return /[",\n\r]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function csv(rows,fields){return [fields.join(','),...rows.map(row=>fields.map(k=>csvCell(row[k])).join(','))].join('\r\n')}
function project(row,fields){const out={};for(const k of fields)if(Object.prototype.hasOwnProperty.call(row||{},k))out[k]=row[k];return out}

async function phase7Status(request,env){const a=await requireRoles(request,env,ALL_ADMIN_ROLES);if(a.error)return a.error;const [exports,reviews,presets]=await Promise.all([count(env,'hc_admin_export_log'),list(env,'hc_admin_security_reviews','id,review_type,status,findings,note,reviewer_email,reviewer_role,reviewed_at','reviewed_at.desc',20),count(env,'hc_admin_report_presets')]);return j({version:VERSION,actor:a.actor,phase7:{globalSearch:true,advancedReports:true,privacySafeCsvExport:true,roleMatrixReview:true,securityReviewEvidence:true,reportPresets:true,reconciliationGate:true},migrationRequired:exports.missing||reviews.status===404||presets.missing,counts:{exports:exports.value,reportPresets:presets.value},recentSecurityReviews:reviews.ok?(reviews.data||[]):[],safety:{exportsUseExplicitAllowlists:true,privateMessagesNeverExported:true,identityEvidenceNeverExported:true,paymentCredentialsNeverExported:true,exportsAreAudited:true,securityBranchIsNotModifiedByThisPhase:true,productionMainIsNotModifiedByThisPhase:true}})}

async function globalSearch(request,env){const a=await requireRoles(request,env,ALL_ADMIN_ROLES);if(a.error)return a.error;const u=new URL(request.url),q=safeSearchTerm(u.searchParams.get('q')),scope=text(u.searchParams.get('scope')||'all',30);if(q.length<2)return j({error:'Enter at least 2 search characters.'},400);const tasks=[];const add=(type,table,select,orExpr,order='created_at.desc')=>{if(scope!=='all'&&scope!==type)return;tasks.push((async()=>{const filter='or='+encodeURIComponent('('+orExpr+')');const r=await list(env,table,select,order,20,filter);return{type,items:r.ok?(r.data||[]):[],unavailable:!r.ok,reason:!r.ok?text(r.data?.message||'Unavailable',200):null}})())};
  const p=q.replace(/[%]/g,' '),wild='*'+p+'*';
  add('users','dating_profiles','user_id,display_name,country,city,relationship_intention,verification_level,created_at',uuid(q)?`user_id.eq.${q},display_name.ilike.${wild},city.ilike.${wild},country.ilike.${wild}`:`display_name.ilike.${wild},city.ilike.${wild},country.ilike.${wild}`);
  add('cms','hc_cms_posts','id,title,slug,status,updated_at',`title.ilike.${wild},slug.ilike.${wild}`,'updated_at.desc');
  add('incidents','hc_admin_incidents','id,title,category,severity,status,last_seen_at',uuid(q)?`id.eq.${q},title.ilike.${wild},summary.ilike.${wild}`:`title.ilike.${wild},summary.ilike.${wild}`,'last_seen_at.desc');
  if(['owner','super_admin','admin'].includes(a.actor.role))add('audit','hc_admin_audit_log','id,actor_email,actor_role,action,target,created_at',`action.ilike.${wild},target.ilike.${wild},actor_email.ilike.${wild}`,'created_at.desc');
  const groups=await Promise.all(tasks);await audit(env,a.actor,'admin.phase7.search',scope,'',{queryLength:q.length,groups:groups.map(x=>x.type)});return j({query:q,scope,groups,privacy:'Search excludes private messages, identity evidence, private media, credentials and payment secrets.'})}

async function reportSummary(request,env){const a=await requireRoles(request,env,REPORT_ROLES);if(a.error)return a.error;const u=new URL(request.url),days=Math.max(1,Math.min(365,Number(u.searchParams.get('days'))||30)),since=new Date(Date.now()-days*86400000).toISOString(),created='created_at=gte.'+encodeURIComponent(since),submitted='submitted_at=gte.'+encodeURIComponent(since),detected='detected_at=gte.'+encodeURIComponent(since);const [users,reports,openReports,verifications,pendingVerifications,deliveries,failedDeliveries,incidents,openIncidents,auditEvents,exports]=await Promise.all([
    count(env,'dating_profiles','user_id',created),count(env,'reports','id',created),count(env,'reports','id',created+'&status=in.(new,reviewing)'),count(env,'verification_requests','id',submitted),count(env,'verification_requests','id',submitted+'&status=eq.pending'),count(env,'hc_notification_delivery_queue','id',created),count(env,'hc_notification_delivery_queue','id',created+'&status=eq.failed'),count(env,'hc_admin_incidents','id',detected),count(env,'hc_admin_incidents','id','status=in.(open,acknowledged)'),count(env,'hc_admin_audit_log','id',created),count(env,'hc_admin_export_log','id',created)
  ]);await audit(env,a.actor,'admin.phase7.report_summary','', '',{days});return j({days,since,metrics:{newUsers:users.value,reports:reports.value,openReports:openReports.value,verifications:verifications.value,pendingVerifications:pendingVerifications.value,notificationDeliveries:deliveries.value,failedDeliveries:failedDeliveries.value,newIncidents:incidents.value,openIncidents:openIncidents.value,auditEvents:auditEvents.value,exports:exports.value},availability:{users:users.ok,moderation:reports.ok,verification:verifications.ok,notifications:deliveries.ok,incidents:incidents.ok,audit:auditEvents.ok,exports:exports.ok},privacy:'Reports are aggregate counts only; no private message content or identity evidence is included.'})}

async function paymentRows(env,u){const range=rangeFromUrl(u,'created_at');for(const table of ['payment_transactions','hc_payment_transactions']){const r=await list(env,table,'*','created_at.desc',1000,range.filter);if(r.ok)return{ok:true,table,rows:(r.data||[]).map(x=>project(x,PAYMENT_SAFE_FIELDS)),range};if(!missing(r))return{ok:false,response:r}}return{ok:false,missing:true}}
async function exportCsv(request,env){const u=new URL(request.url),dataset=text(u.searchParams.get('dataset'),30),roles=EXPORT_ROLES[dataset];if(!roles)return j({error:'Unsupported export dataset.'},400);const a=await requireRoles(request,env,roles);if(a.error)return a.error;let rows=[],fields=[],range,source=dataset;if(dataset==='payments'){const p=await paymentRows(env,u);if(!p.ok)return j({error:p.missing?'No supported native payment table is available.':text(p.response?.data?.message||'Payment export failed.'),migrationRequired:!!p.missing},p.missing?409:500);rows=p.rows;fields=PAYMENT_SAFE_FIELDS.filter(k=>rows.some(x=>Object.prototype.hasOwnProperty.call(x,k)));range=p.range;source=p.table}else{const c=DATASETS[dataset];range=rangeFromUrl(u,c.date);const r=await list(env,c.table,c.select,c.order,1000,range.filter);if(!r.ok)return j({error:text(r.data?.message||'Export could not be prepared.'),migrationRequired:missing(r)},r.status===503?503:500);rows=(r.data||[]).map(clean);fields=c.select.split(',')}
  const truncated=rows.length>=1000,filename=`heart-connect-${dataset}-${new Date().toISOString().slice(0,10)}.csv`;await svc(env,'/rest/v1/hc_admin_export_log',{method:'POST',body:{actor_user_id:a.actor.id,actor_email:a.actor.email,actor_role:a.actor.role,dataset,format:'csv',row_count:rows.length,filters:{from:range.from,to:range.to,source,truncated},redaction_policy:'phase7_allowlist',created_at:new Date().toISOString()},headers:{Prefer:'return=minimal'}}).catch(()=>{});await audit(env,a.actor,'admin.phase7.export',dataset,'',{rows:rows.length,source,truncated,from:range.from,to:range.to});return new Response(csv(rows,fields),{status:200,headers:{'content-type':'text/csv; charset=utf-8','content-disposition':`attachment; filename="${filename}"`,'cache-control':'no-store','x-content-type-options':'nosniff','x-heart-connect-admin':VERSION,'x-hc-export-truncated':truncated?'true':'false','x-hc-export-redaction':'phase7_allowlist'}})}

async function presets(request,env){const a=await requireRoles(request,env,REPORT_ROLES);if(a.error)return a.error;if(request.method==='GET'){const r=await list(env,'hc_admin_report_presets','id,name,dataset,config,created_by,updated_by,created_at,updated_at','updated_at.desc',100);if(!r.ok)return j({error:text(r.data?.message||'Report presets could not be loaded.'),migrationRequired:missing(r)},r.status===503?503:500);return j({items:r.data||[]})}let b;try{b=await jsonBody(request)}catch(e){return j({error:e.message},e.status||400)}const name=text(b.name,120),dataset=text(b.dataset,30),id=text(b.id,80),allowed=['overview','users','moderation','verification','payments','notifications','audit','incidents'];if(!name||!allowed.includes(dataset)||(id&&!uuid(id)))return j({error:'Provide a valid report name and dataset.'},400);const record={name,dataset,config:clean(b.config||{}),updated_by:a.actor.id,updated_at:new Date().toISOString()};let r;if(id)r=await svc(env,'/rest/v1/hc_admin_report_presets?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:record,headers:{Prefer:'return=representation'}});else r=await svc(env,'/rest/v1/hc_admin_report_presets',{method:'POST',body:{...record,created_by:a.actor.id,created_at:new Date().toISOString()},headers:{Prefer:'return=representation'}});if(!r.ok)return j({error:text(r.data?.message||'Report preset could not be saved.'),migrationRequired:missing(r)},r.status===503?503:500);await audit(env,a.actor,id?'admin.phase7.report_preset.update':'admin.phase7.report_preset.create',id||name);return j({ok:true,item:Array.isArray(r.data)?r.data[0]:r.data})}

async function securityReviewData(request,env){const a=await requireRoles(request,env,['owner','super_admin','admin']);if(a.error)return a.error;const [staff,reviews,exports]=await Promise.all([list(env,'hc_admin_staff','user_id,email,display_name,role,status,created_at,updated_at','updated_at.desc',300),list(env,'hc_admin_security_reviews','id,review_type,status,findings,note,reviewer_email,reviewer_role,reviewed_at','reviewed_at.desc',30),list(env,'hc_admin_export_log','id,actor_email,actor_role,dataset,row_count,filters,redaction_policy,created_at','created_at.desc',30)]);const items=staff.ok?(staff.data||[]):[],unknown=items.filter(x=>!ROLE_MATRIX[x.role]),active=items.filter(x=>x.status==='active'),superAdmins=active.filter(x=>x.role==='super_admin');const findings=[];if(unknown.length)findings.push(`${unknown.length} staff row(s) use an unknown role.`);if(superAdmins.length>3)findings.push(`${superAdmins.length} active super-admins should be reviewed for least privilege.`);if(!active.length)findings.push('No active delegated staff are registered; owner allow-list access may be the only admin path.');return j({actor:a.actor,roleMatrix:ROLE_MATRIX,staff:items,summary:{activeStaff:active.length,unknownRoles:unknown.length,activeSuperAdmins:superAdmins.length},findings,recentReviews:reviews.ok?(reviews.data||[]):[],recentExports:exports.ok?(exports.data||[]):[],exportPolicy:{users:['user_id','display_name','country','city','relationship_intention','verification_level','profile_completion','is_discoverable','last_active_at','created_at'],moderation:['no report details body','no private messages'],verification:['no evidence_path','no identity documents'],payments:PAYMENT_SAFE_FIELDS,global:['no secrets','no credentials','no private media','all exports audited']}})}
async function securityReviewSave(request,env){const a=await requireRoles(request,env,SECURITY_REVIEW_ROLES);if(a.error)return a.error;let b;try{b=await jsonBody(request)}catch(e){return j({error:e.message},e.status||400)}const reviewType=text(b.reviewType,30),status=text(b.status,30),note=text(b.note,3000),confirmation=text(b.confirmation,30),allowedTypes=['permissions','export_privacy','reconciliation'];if(!allowedTypes.includes(reviewType)||!['passed','needs_action','blocked'].includes(status))return j({error:'Provide a valid review type and status.'},400);if(confirmation!=='REVIEWED')return j({error:'Type REVIEWED to record this security review.',confirmation:'REVIEWED'},409);if(note.length<3)return j({error:'Add a short review note or evidence.'},400);const findings=(Array.isArray(b.findings)?b.findings:[]).map(x=>text(x,600)).filter(Boolean).slice(0,50),r=await svc(env,'/rest/v1/hc_admin_security_reviews',{method:'POST',body:{review_type:reviewType,status,findings,note,reviewed_by:a.actor.id,reviewer_email:a.actor.email,reviewer_role:a.actor.role,reviewed_at:new Date().toISOString()},headers:{Prefer:'return=representation'}});if(!r.ok)return j({error:text(r.data?.message||'Security review could not be recorded.'),migrationRequired:missing(r)},r.status===503?503:500);const readinessKey={permissions:'admin_permissions_review',export_privacy:'admin_export_privacy_review',reconciliation:'admin_reconciliation_plan_reviewed'}[reviewType],readinessStatus=status==='passed'?'passed':'blocked';await svc(env,'/rest/v1/hc_admin_readiness_checks?key=eq.'+encodeURIComponent(readinessKey),{method:'PATCH',body:{status:readinessStatus,evidence:note,note:findings.join(' | ')||null,checked_by:a.actor.id,checked_at:new Date().toISOString(),updated_at:new Date().toISOString()},headers:{Prefer:'return=minimal'}}).catch(()=>{});await audit(env,a.actor,'admin.phase7.security_review',reviewType,note,{status,findingsCount:findings.length,readinessKey});return j({ok:true,item:Array.isArray(r.data)?r.data[0]:r.data,readinessKey,readinessStatus,note:'This records review evidence only. It does not merge branches, deploy production, change user accounts, or apply database migrations.'})}

export async function runPhase7AndEarlierScheduled(env){return runPhase6AndPhase5Scheduled(env)}

export async function handleAdmin(request,env){const u=new URL(request.url),p=u.pathname;if(p==='/admin'||p==='/admin/')return page(adminHtml(VERSION));if(!p.startsWith('/api/admin/'))return handleAdminV6(request,env);if(!sameOrigin(request))return j({error:'Cross-site admin request blocked.'},403);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{allow:'GET, POST, HEAD, OPTIONS'}});
  if(p==='/api/admin/phase7/status'&&request.method==='GET')return phase7Status(request,env);
  if(p==='/api/admin/search'&&request.method==='GET')return globalSearch(request,env);
  if(p==='/api/admin/reports/summary'&&request.method==='GET')return reportSummary(request,env);
  if(p==='/api/admin/reports/export'&&request.method==='GET')return exportCsv(request,env);
  if(p==='/api/admin/reports/presets'&&(request.method==='GET'||request.method==='POST'))return presets(request,env);
  if(p==='/api/admin/security/review'&&request.method==='GET')return securityReviewData(request,env);
  if(p==='/api/admin/security/review'&&request.method==='POST')return securityReviewSave(request,env);
  return handleAdminV6(request,env)
}
