import {adminHtml as adminHtmlV31} from './admin-ui-v31.js';

export function adminHtml(version){
  const upgrade=`<style>
.hc32-extra{grid-column:1/-1;border:1px solid #ffffff10;background:#0a1018;border-radius:14px;padding:12px;display:grid;gap:10px}.hc32-row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.hc32-row label{display:grid;gap:5px}.hc32-row span,.hc32-label{font-size:9px;color:#8391a4}.hc32-tags{font-size:9px;color:#7f8da0}.hc32-editorbar{display:flex;gap:7px;flex-wrap:wrap;align-items:center}.hc32-mode{border:1px solid #ffffff15;background:#090e15;color:#aab5c5;border-radius:999px;padding:7px 10px;font-size:9px;font-weight:850;cursor:pointer}.hc32-mode.active{background:#fff;color:#111827;border-color:#fff}.hc32-visual{display:none;min-height:280px;border:1px solid #ffffff14;background:#fff;color:#111;border-radius:11px;padding:14px;overflow:auto;line-height:1.6}.hc32-visual.active{display:block}.hc32-cover{display:grid;grid-template-columns:100px 1fr auto;gap:10px;align-items:center;border:1px solid #ffffff0e;background:#070c13;border-radius:12px;padding:10px}.hc32-cover img{width:100px;height:72px;object-fit:cover;border-radius:9px;background:#111}.hc32-cover b{font-size:10px}.hc32-cover small{display:block;color:#748195;font-size:9px;margin-top:3px}.hc32-seo{grid-column:1/-1;border:1px solid #ffffff0e;background:#fff;border-radius:12px;padding:14px;color:#202124}.hc32-seo small{color:#5f6368}.hc32-seo-title{color:#1a0dab;font-size:18px;line-height:1.3;margin:4px 0}.hc32-seo-url{color:#188038;font-size:12px}.hc32-seo-desc{color:#4d5156;font-size:12px;line-height:1.45;margin-top:4px}.hc32-stats{grid-column:1/-1;display:flex;gap:8px;flex-wrap:wrap}.hc32-stat{border:1px solid #ffffff10;background:#080d14;border-radius:999px;padding:6px 9px;font-size:9px;color:#95a3b6}.hc32-savebar{grid-column:1/-1;display:flex;justify-content:space-between;gap:10px;align-items:center;border-top:1px solid #ffffff0d;padding-top:10px}.hc32-saveactions{display:flex;gap:7px;flex-wrap:wrap}.hc32-save{border:1px solid #ffffff15;background:#0a1018;color:#fff;border-radius:999px;padding:8px 11px;font-size:10px;font-weight:850;cursor:pointer}.hc32-save.primary{border-color:transparent;background:linear-gradient(135deg,#ff4f88,#8b5cff)}.hc32-save.schedule{border-color:#5d9bff45;color:#9dc4ff;background:#4d8fff10}.hc32-saved{font-size:9px;color:#8391a4}.hc32-picker{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.hc32-pick{border:1px solid #ffffff10;background:#080d14;border-radius:12px;overflow:hidden}.hc32-pick img{width:100%;aspect-ratio:4/3;object-fit:cover}.hc32-pick div{padding:9px}.hc32-pick b{font-size:9px}.hc32-pick button{margin-top:7px}
@media(max-width:720px){.hc32-row{grid-template-columns:1fr}.hc32-cover{grid-template-columns:72px 1fr}.hc32-cover img{width:72px;height:60px}.hc32-cover .hc32-save{grid-column:1/-1}.hc32-picker{grid-template-columns:1fr 1fr}.hc32-savebar{display:grid}}@media(max-width:430px){.hc32-picker{grid-template-columns:1fr}}
</style><script>
(()=>{
  window.__hcCmsV32Available=true;
  const q=s=>document.querySelector(s);
  let timer=null,featuredId='',featuredUrl='',postId='',restored=false;
  function esc(v){return String(v==null?'':v).replace(/[&<>\\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[m]))}
  function words(html){const t=document.createElement('div');t.innerHTML=html||'';return (t.textContent||'').trim().split(/\\s+/).filter(Boolean).length}
  function key(){return 'hc-cms-autosave-v32-'+(postId||'new')}
  async function req(url,opt={}){const r=await fetch(url,{credentials:'same-origin',...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Request failed');return d}
  function syncVisualFromHtml(){const visual=q('#hc32Visual'),html=q('#hc31Body');if(visual&&html)visual.innerHTML=html.value||''}
  function syncHtmlFromVisual(){const visual=q('#hc32Visual'),html=q('#hc31Body');if(visual&&html&&visual.classList.contains('active'))html.value=visual.innerHTML}
  function updateStats(){syncHtmlFromVisual();const body=q('#hc31Body'),count=words(body?.value||''),mins=Math.max(1,Math.ceil(count/220));if(q('#hc32Words'))q('#hc32Words').textContent=count+' words';if(q('#hc32Read'))q('#hc32Read').textContent='~'+mins+' min read';updateSeo()}
  function updateSeo(){const title=(q('#hc31SeoTitle')?.value||q('#hc31Title')?.value||'Untitled post').trim(),desc=(q('#hc31SeoDescription')?.value||q('#hc31Excerpt')?.value||'Add an SEO description for this post.').trim(),slug=(q('#hc31Slug')?.value||'post').trim();if(q('#hc32SeoTitle'))q('#hc32SeoTitle').textContent=title.slice(0,70);if(q('#hc32SeoDesc'))q('#hc32SeoDesc').textContent=desc.slice(0,165);if(q('#hc32SeoUrl'))q('#hc32SeoUrl').textContent='heartconnect · /blog/'+slug}
  function updateSchedule(){const status=q('#hc31PostStatus')?.value,wrap=q('#hc31Schedule')?.closest('label'),btn=q('#hc32ScheduleSave');if(wrap)wrap.style.display=status==='scheduled'?'grid':'none';if(btn)btn.style.display=status==='scheduled'?'inline-flex':'none'}
  function draftData(){syncHtmlFromVisual();return{title:q('#hc31Title')?.value||'',slug:q('#hc31Slug')?.value||'',excerpt:q('#hc31Excerpt')?.value||'',body:q('#hc31Body')?.value||'',category:q('#hc32Category')?.value||'',tags:q('#hc32Tags')?.value||'',seoTitle:q('#hc31SeoTitle')?.value||'',seoDescription:q('#hc31SeoDescription')?.value||'',status:q('#hc31PostStatus')?.value||'draft',schedule:q('#hc31Schedule')?.value||'',featuredId,featuredUrl,at:Date.now()}}
  function autosave(){try{localStorage.setItem(key(),JSON.stringify(draftData()));if(q('#hc32Saved'))q('#hc32Saved').textContent='Autosaved locally · '+new Date().toLocaleTimeString()}catch{}}
  function restoreDraft(d){if(!d)return;for(const [id,val] of [['#hc31Title',d.title],['#hc31Slug',d.slug],['#hc31Excerpt',d.excerpt],['#hc31Body',d.body],['#hc32Category',d.category],['#hc32Tags',d.tags],['#hc31SeoTitle',d.seoTitle],['#hc31SeoDescription',d.seoDescription],['#hc31Schedule',d.schedule]]){const el=q(id);if(el&&val!=null)el.value=val}featuredId=d.featuredId||'';featuredUrl=d.featuredUrl||'';if(d.status&&q('#hc31PostStatus'))q('#hc31PostStatus').value=d.status;paintCover();syncVisualFromHtml();updateStats();updateSchedule();if(q('#hc32Saved'))q('#hc32Saved').textContent='Recovered local autosave'}
  function paintCover(){const img=q('#hc32CoverImg'),label=q('#hc32CoverLabel');if(img){img.src=featuredUrl||'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22100%22 height=%2272%22%3E%3Crect width=%22100%25%22 height=%22100%25%22 fill=%22%23131a24%22/%3E%3C/svg%3E'}if(label)label.textContent=featuredId?'Featured image selected':'No featured image selected'}
  async function chooseCover(){const d=await req('/api/admin/cms/media'),items=(d.items||[]).filter(x=>x.media_type==='image'||x.media_type==='thumbnail'||x.media_type==='gallery');const modal=document.createElement('dialog');modal.innerHTML='<div class="modal-head"><b>Choose featured image</b><button type="button">×</button></div><div class="modal-body">'+(items.length?'<div class="hc32-picker">'+items.map(x=>'<article class="hc32-pick"><img src="'+esc(x.public_url||'')+'" alt="'+esc(x.alt_text||'')+'"><div><b>'+esc(x.alt_text||'CMS image')+'</b><button class="hc32-save primary" type="button" data-hc32-cover="'+esc(x.id)+'">Use as cover</button></div></article>').join('')+'</div>':'<div class="hc31-empty"><b>No images available</b><span>Upload an image first, then choose it as the featured image.</span></div>')+'</div>';document.body.appendChild(modal);modal.querySelector('.modal-head button').onclick=()=>{modal.close();modal.remove()};modal.querySelectorAll('[data-hc32-cover]').forEach(b=>b.onclick=()=>{const x=items.find(v=>String(v.id)===b.dataset.hc32Cover);if(x){featuredId=x.id;featuredUrl=x.public_url||'';paintCover();autosave()}modal.close();modal.remove()});modal.showModal()}
  async function loadExistingMeta(){if(!postId)return;try{const d=await req('/api/admin/cms/posts'),x=(d.items||[]).find(v=>String(v.id)===postId);if(!x)return;featuredId=x.featured_media_id||'';if(featuredId){const m=await req('/api/admin/cms/media');const med=(m.items||[]).find(v=>String(v.id)===featuredId);featuredUrl=med?.public_url||''}if(q('#hc32Category'))q('#hc32Category').value=x.category||'';if(q('#hc32Tags'))q('#hc32Tags').value=Array.isArray(x.tags)?x.tags.join(', '):'';paintCover()}catch{}}
  async function save(targetStatus){syncHtmlFromVisual();const title=(q('#hc31Title')?.value||'').trim(),slug=(q('#hc31Slug')?.value||'').trim(),when=q('#hc31Schedule')?.value||'';if(!title||!slug){alert('Title and slug are required.');return}if(targetStatus==='scheduled'&&!when){alert('Choose a future schedule time first.');return}const tags=(q('#hc32Tags')?.value||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,20),payload={id:postId||undefined,title,slug,excerpt:q('#hc31Excerpt')?.value||'',body:q('#hc31Body')?.value||'',status:targetStatus,scheduledFor:targetStatus==='scheduled'?when:'',category:q('#hc32Category')?.value||'',tags,featuredMediaId:featuredId||null,seoTitle:q('#hc31SeoTitle')?.value||'',seoDescription:q('#hc31SeoDescription')?.value||'',publishChannels:{website:true,facebook:q('#hc31Facebook')?.checked===true,tiktok:q('#hc31TikTok')?.checked===true,google_business:q('#hc31Google')?.checked===true}};for(const b of document.querySelectorAll('.hc32-save[data-action]'))b.disabled=true;try{const d=await req('/api/admin/cms/posts',{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify(payload)});postId=d.post?.id||postId;try{localStorage.removeItem(key())}catch{}q('#modal')?.close();if(typeof window.load==='function')window.load('cms');else location.reload()}catch(e){alert(e.message)}finally{for(const b of document.querySelectorAll('.hc32-save[data-action]'))b.disabled=false}}
  function upgradeEditor(){
    const form=q('.hc31-form[data-hc31-post-id]'),body=q('#hc31Body');if(!form||!body||q('#hc32Enhancements'))return;
    postId=form.dataset.hc31PostId||'';
    const extra=document.createElement('section');extra.id='hc32Enhancements';extra.className='hc32-extra';extra.innerHTML='<div class="hc32-row"><label><span>Category</span><select id="hc32Category"><option value="">Choose category</option><option>Dating Advice</option><option>Safety</option><option>Relationships</option><option>Travel</option><option>News</option><option>Stories</option><option>Announcements</option><option>Lifestyle</option></select></label><label><span>Tags</span><input id="hc32Tags" placeholder="dating, safety, relationships"><small class="hc32-tags">Comma-separated · maximum 20 tags</small></label></div><div><div class="hc32-label">Featured image / cover</div><div class="hc32-cover"><img id="hc32CoverImg" alt=""><div><b id="hc32CoverLabel">No featured image selected</b><small>Used for cards, previews and future social sharing.</small></div><button class="hc32-save" id="hc32ChooseCover" type="button">Choose cover image</button></div></div><div><div class="hc32-label">Editor mode</div><div class="hc32-editorbar"><button class="hc32-mode active" id="hc32HtmlMode" type="button">HTML</button><button class="hc32-mode" id="hc32VisualMode" type="button">Visual editor</button><span class="hc32-stat" id="hc32Words">0 words</span><span class="hc32-stat" id="hc32Read">~1 min read</span></div><div id="hc32Visual" class="hc32-visual" contenteditable="true"></div></div><div class="hc32-seo"><small>Search preview</small><div class="hc32-seo-url" id="hc32SeoUrl">heartconnect · /blog/post</div><div class="hc32-seo-title" id="hc32SeoTitle">Untitled post</div><div class="hc32-seo-desc" id="hc32SeoDesc">Add an SEO description for this post.</div></div><div class="hc32-savebar"><span class="hc32-saved" id="hc32Saved">Autosave ready</span><div class="hc32-saveactions"><button class="hc32-save" type="button" data-action="draft" id="hc32DraftSave">Save draft</button><button class="hc32-save schedule" type="button" data-action="scheduled" id="hc32ScheduleSave">Schedule post</button><button class="hc32-save primary" type="button" data-action="published" id="hc32Publish">Publish now</button></div></div>';
    form.insertBefore(extra,form.querySelector('.hc31-ai')||form.querySelector('.hc31-modal-actions')||null);
    const oldSave=q('#hc31Save');if(oldSave)oldSave.style.display='none';
    q('#hc32ChooseCover').onclick=()=>chooseCover().catch(e=>alert(e.message));
    q('#hc32HtmlMode').onclick=()=>{syncHtmlFromVisual();q('#hc32Visual').classList.remove('active');body.style.display='block';q('#hc32HtmlMode').classList.add('active');q('#hc32VisualMode').classList.remove('active');updateStats()};
    q('#hc32VisualMode').onclick=()=>{syncVisualFromHtml();body.style.display='none';q('#hc32Visual').classList.add('active');q('#hc32VisualMode').classList.add('active');q('#hc32HtmlMode').classList.remove('active');updateStats()};
    q('#hc32Visual').oninput=updateStats;
    for(const sel of ['#hc31Title','#hc31Slug','#hc31Excerpt','#hc31Body','#hc31SeoTitle','#hc31SeoDescription','#hc32Category','#hc32Tags']){const el=q(sel);if(el)el.addEventListener('input',updateStats)}
    q('#hc31PostStatus')?.addEventListener('change',updateSchedule);
    q('#hc32DraftSave').onclick=()=>save('draft');q('#hc32ScheduleSave').onclick=()=>save('scheduled');q('#hc32Publish').onclick=()=>{if(confirm('Publish this post to the Heart Connect website now? External social channels remain API-gated.'))save('published')};
    syncVisualFromHtml();updateStats();updateSchedule();paintCover();loadExistingMeta();
    try{const raw=localStorage.getItem(key());if(raw){const d=JSON.parse(raw);const serverUpdated=0;if(d&&d.at>serverUpdated&&!restored){restored=true;if(confirm('A local autosave exists for this editor. Restore it?'))restoreDraft(d)}}}catch{}
    clearInterval(timer);timer=setInterval(()=>{if(q('#hc32Enhancements'))autosave();else clearInterval(timer)},5000)
  }
  new MutationObserver(()=>setTimeout(upgradeEditor,0)).observe(document.body,{childList:true,subtree:true});setTimeout(upgradeEditor,0);setTimeout(upgradeEditor,500);
})();
</script>`;
  return adminHtmlV31(version).replace('</body>',upgrade+'</body>');
}
