import {adminHtml as adminHtmlV24} from './admin-ui-v24.js';

export function adminHtml(version){
  const upgrade=`<style>
.hc25-analytics{display:grid;gap:14px}.hc25-head{border:1px solid #6d7cff2b;background:radial-gradient(circle at 88% 8%,#685bff22,transparent 30%),linear-gradient(135deg,#101722,#0a0f16);border-radius:20px;padding:18px}.hc25-head-row{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.hc25-kicker{font-size:10px;letter-spacing:.13em;text-transform:uppercase;color:#9d95ff;font-weight:900}.hc25-head h2{margin:4px 0 6px;font-size:23px}.hc25-head p{margin:0;color:#8f9caf;font-size:11px;line-height:1.55}.hc25-periods{display:flex;gap:6px;flex-wrap:wrap}.hc25-period{border:1px solid #ffffff15;background:#090e15;color:#aab4c4;border-radius:999px;padding:8px 11px;font-size:10px;font-weight:850;cursor:pointer}.hc25-period.active{background:linear-gradient(135deg,#655bff,#8c5cff);color:#fff;border-color:transparent}.hc25-cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.hc25-card{border:1px solid #ffffff10;background:linear-gradient(180deg,#111722,#0a1018);border-radius:16px;padding:14px}.hc25-card small{display:block;color:#7f8ca0;font-size:9px;text-transform:uppercase;letter-spacing:.08em}.hc25-card strong{display:block;font-size:25px;margin:7px 0 3px}.hc25-card span{font-size:9px;color:#8996a8}.hc25-grid{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(320px,.85fr);gap:14px}.hc25-panel{border:1px solid #ffffff11;background:#0c121a;border-radius:17px;padding:15px}.hc25-panel h3{margin:0;font-size:14px}.hc25-panel p{margin:4px 0 12px;color:#7f8ca0;font-size:10px;line-height:1.5}.hc25-bars{display:grid;gap:10px}.hc25-bar-row{display:grid;grid-template-columns:150px 1fr 56px;gap:10px;align-items:center}.hc25-bar-row label{font-size:10px;color:#aab5c5}.hc25-track{height:10px;background:#ffffff0b;border-radius:999px;overflow:hidden}.hc25-fill{height:100%;background:linear-gradient(90deg,#655bff,#ff5b87);border-radius:999px;min-width:2px}.hc25-bar-row b{text-align:right;font-size:10px}.hc25-ops{display:grid;gap:8px}.hc25-op{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;border:1px solid #ffffff0e;background:#080d14;border-radius:12px;padding:11px}.hc25-op small{display:block;color:#768398;font-size:9px;margin-top:3px}.hc25-op strong{font-size:16px}.hc25-privacy{border:1px solid #38d39f24;background:#38d39f0c;border-radius:14px;padding:12px;color:#9eacbc;font-size:10px;line-height:1.55}.hc25-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.hc25-btn{border:1px solid #ffffff16;background:#0a1018;color:#fff;border-radius:999px;padding:8px 11px;font-size:10px;font-weight:800;cursor:pointer}.hc25-btn.primary{border-color:transparent;background:linear-gradient(135deg,#655bff,#8c5cff)}.hc25-status{font-size:10px;color:#77869a;margin-top:8px}.hc25-loading{padding:22px;text-align:center;color:#8b98aa;border:1px dashed #ffffff16;border-radius:14px}
@media(max-width:1050px){.hc25-grid{grid-template-columns:1fr}.hc25-cards{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.hc25-head-row{display:block}.hc25-periods{margin-top:12px}.hc25-cards{grid-template-columns:1fr}.hc25-bar-row{grid-template-columns:110px 1fr 45px}}
</style><script>
(()=>{
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];let busy=false,currentDays=30;
  function esc(v){return String(v==null?'':v).replace(/[&<>\\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[m]))}
  async function get(url){const r=await fetch(url,{credentials:'same-origin',headers:{accept:'application/json'}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Request failed');return d}
  function n(v){const x=Number(v);return Number.isFinite(x)?x:0}
  function card(label,value,sub){return '<div class="hc25-card"><small>'+esc(label)+'</small><strong>'+esc(value==null?'—':value)+'</strong><span>'+esc(sub)+'</span></div>'}
  function bar(label,value,max){const pct=max?Math.max(0,Math.min(100,Math.round(n(value)/max*100))):0;return '<div class="hc25-bar-row"><label>'+esc(label)+'</label><div class="hc25-track"><div class="hc25-fill" style="width:'+pct+'%"></div></div><b>'+esc(value==null?'—':value)+'</b></div>'}
  function op(label,value,sub){return '<div class="hc25-op"><div><b>'+esc(label)+'</b><small>'+esc(sub)+'</small></div><strong>'+esc(value==null?'—':value)+'</strong></div>'}
  function should(){const t=q('#title'),v=q('#view');return t&&v&&t.textContent.trim()==='Analytics'&&!v.querySelector('.hc25-analytics')&&!v.querySelector('.hc26')&&/Analytics|Loading|Total profiles|New profiles/i.test(v.textContent||'')}
  async function render(days){
    const v=q('#view');if(!v)return;currentDays=days;v.innerHTML='<div class="hc25-loading">Loading privacy-safe analytics…</div>';
    try{
      const [a,r]=await Promise.all([get('/api/admin/analytics?days='+days),get('/api/admin/reports/summary?days='+days).catch(()=>({metrics:{},availability:{}}))]);
      if(q('#title')?.textContent.trim()!=='Analytics')return;
      const m=a.metrics||{},rm=r.metrics||{},max=Math.max(1,n(m.profiles),n(m.matches),n(m.messages),n(m.reports),n(m.verification));
      v.innerHTML='<div class="hc25-analytics"><section class="hc25-head"><div class="hc25-head-row"><div><div class="hc25-kicker">Privacy-safe analytics</div><h2>Platform Analytics</h2><p>Aggregate operational metrics only. Private messages, identity evidence and sensitive profile traits are excluded.</p></div><div class="hc25-periods">'+[7,30,90,365].map(x=>'<button class="hc25-period '+(x===days?'active':'')+'" data-hc25-days="'+x+'" type="button">'+x+' days</button>').join('')+'</div></div></section><div class="hc25-cards">'+card('Total profiles',m.profiles,'All dating profiles')+card('New profiles',m.newProfiles,'Created in selected period')+card('Matches',m.matches,'All matches')+card('New matches',m.newMatches,'Created in selected period')+card('Messages',m.messages,'Aggregate count only')+card('New messages',m.newMessages,'No message content exposed')+card('Open reports',m.openReports,'Needs moderation review')+card('Pending verification',m.pendingVerification,'Awaiting human review')+'</div><div class="hc25-grid"><section class="hc25-panel"><h3>Platform activity</h3><p>Relative scale across key aggregate datasets. These bars are counts, not growth-rate predictions.</p><div class="hc25-bars">'+bar('Profiles',m.profiles,max)+bar('Matches',m.matches,max)+bar('Messages',m.messages,max)+bar('Reports',m.reports,max)+bar('Verification',m.verification,max)+bar('Published posts',m.publishedPosts,max)+'</div><div class="hc25-actions"><button class="hc25-btn" data-hc25-go="users">Open Users</button><button class="hc25-btn" data-hc25-go="moderation">Open Moderation</button><button class="hc25-btn" data-hc25-go="verification">Open Verification</button><button class="hc25-btn primary" data-hc25-go="reports7">Reports & Search</button></div></section><section class="hc25-panel"><h3>Operational activity</h3><p>Aggregate Admin and delivery activity for the same selected period.</p><div class="hc25-ops">'+op('Reports received',rm.reports,'Moderation reports in period')+op('Verification submissions',rm.verifications,'Verification requests in period')+op('Notification deliveries',rm.notificationDeliveries,'Delivery queue records')+op('Failed deliveries',rm.failedDeliveries,'Needs operational review')+op('New incidents',rm.newIncidents,'Operational incidents in period')+op('Audit events',rm.auditEvents,'Administrative actions logged')+op('Exports',rm.exports,'Privacy-safe export events')+'</div></section></div><div class="hc25-privacy">'+esc(a.privacy||'Only aggregate counts are returned.')+' '+esc(r.privacy||'')+'</div><div class="hc25-status">Showing the last '+days+' days. Metrics unavailable from a source are left blank rather than estimated.</div></div>';
      v.querySelectorAll('[data-hc25-days]').forEach(b=>b.onclick=()=>render(Number(b.dataset.hc25Days)||30));
      const labels={users:'Users',moderation:'Moderation',verification:'Verification',reports7:'Reports & Search'};v.querySelectorAll('[data-hc25-go]').forEach(b=>b.onclick=()=>{const key=b.dataset.hc25Go;const nav=q('#nav button[data-tab="'+key+'"]')||qa('#nav button').find(x=>x.textContent.trim()===labels[key]);if(nav)nav.click()});
    }catch(e){v.innerHTML='<div class="hc25-loading"><b>Analytics unavailable</b><div style="margin-top:6px">'+esc(e.message)+'</div></div>'}
  }
  function apply(){if(busy||!should())return;busy=true;render(currentDays).finally(()=>busy=false)}
  new MutationObserver(()=>setTimeout(apply,0)).observe(document.body,{childList:true,subtree:true,characterData:true});setTimeout(apply,0);setTimeout(apply,500);
})();
</script>`;
  return adminHtmlV24(version).replace('</body>',upgrade+'</body>');
}
