import {handleAdmin as handleAdminV3} from './admin-api-v3.js';
import {adminHtml} from './admin-ui-v4.js';

export const VERSION='hc-admin-control-plane-v4';
const ACCESS_COOKIE='__Host-hc_cf_access';
const DEFAULT_SUPABASE_URL='https://zzhzkikezjtbntaqiurk.supabase.co';
const DEFAULT_PUBLISHABLE_KEY='sb_publishable_HB0Irz6bxug1hHs518oPZQ_LC83i4qT';
const CMS_BUCKET='hc-cms-public';
const CONTENT_WRITERS=['owner','super_admin','admin','content_manager'];
const SETTINGS_WRITERS=['owner','super_admin','admin'];
const PURGE_ROLES=['owner','super_admin'];
const ALL_ADMIN_ROLES=['owner','super_admin','admin','moderator','senior_moderator','safety_specialist','payment_specialist','support_agent','content_manager','verification_specialist','finance'];
const ENTITY={
  cms_post:{table:'hc_cms_posts',id:'id',roles:CONTENT_WRITERS,select:'id,title,slug,status,deleted_at,deleted_by,delete_reason,updated_at'},
  cms_media:{table:'hc_cms_media',id:'id',roles:CONTENT_WRITERS,select:'id,post_id,media_type,storage_path,public_url,mime_type,deleted_at,deleted_by,delete_reason,created_at'},
  page:{table:'hc_site_pages',id:'id',roles:CONTENT_WRITERS,select:'id,title,slug,page_type,status,deleted_at,deleted_by,delete_reason,updated_at'},
  setting:{table:'hc_site_settings',id:'key',roles:SETTINGS_WRITERS,select:'key,value,category,deleted_at,deleted_by,delete_reason,updated_at'},
  notification_campaign:{table:'hc_notification_campaigns',id:'id',roles:CONTENT_WRITERS,select:'id,title,status,channels,audience,deleted_at,deleted_by,delete_reason,updated_at'}
};
function cfg(env){return{url:String(env.SUPABASE_URL||DEFAULT_SUPABASE_URL).replace(/\/+$/,''),publishable:String(env.SUPABASE_PUBLISHABLE_KEY||DEFAULT_PUBLISHABLE_KEY),service:String(env.SUPABASE_SERVICE_ROLE_KEY||'')}}
function cookies(request){const out={};for(const part of String(request.headers.get('cookie')||'').split(';')){const i=part.indexOf('=');if(i>0){const k=part.slice(0,i).trim();try{out[k]=decodeURIComponent(part.slice(i+1).trim())}catch{out[k]=part.slice(i+1).trim()}}}return out}
function j(data,status=200,extra={}){const h=new Headers({'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-heart-connect-admin':VERSION,...extra});return new Response(JSON.stringify(data),{status,headers:h})}
function page(html,status=200){return new Response(html,{status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'same-origin','x-frame-options':'DENY','content-security-policy':"default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'",'x-heart-connect-admin':VERSION}})}
function unsafe(request){return !['GET','HEAD','OPTIONS'].includes(request.method)}
function sameOrigin(request){if(!unsafe(request))return true;const site=request.headers.get('sec-fetch-site');if(site==='cross-site')return false;const origin=request.headers.get('origin');if(!origin)return true;try{return new URL(origin).origin===new URL(request.url).origin}catch{return false}}
function text(v,n=1000){return String(v??'').trim().slice(0,n)}
function email(v){const s=text(v,320).toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)?s:''}
function emails(v){return String(v||'').split(',').map(email).filter(Boolean)}
function uuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''))}
function safeSetting(v){return /^[a-z0-9][a-z0-9_.-]{1,119}$/i.test(String(v||''))}
async function body(request,max=50000){const raw=await request.text();if(raw.length>max)throw Object.assign(new Error('Request is too large.'),{status:413});try{return raw?JSON.parse(raw):{}}catch{throw Object.assign(new Error('Valid JSON is required.'),{status:400})}}
async function session(request,env){const c=cfg(env),token=cookies(request)[ACCESS_COOKIE]||'';if(!token)return null;try{const r=await fetch(c.url+'/auth/v1/user',{headers:{apikey:c.publishable,authorization:'Bearer '+token,accept:'application/json'}});if(!r.ok)return null;const u=await r.json();return u?.id?{id:u.id,email:email(u.email)}:null}catch{return null}}
async function svc(env,path,{method='GET',body:payload,headers:extra}={}){const c=cfg(env);if(!c.service)return{ok:false,status:503,data:{message:'Admin data service is not configured.'},headers:new Headers()};const headers=new Headers({apikey:c.service,authorization:'Bearer '+c.service,accept:'application/json',...extra});if(payload!==undefined)headers.set('content-type','application/json');try{const r=await fetch(c.url+path,{method,headers,body:payload===undefined?undefined:JSON.stringify(payload)}),raw=await r.text();let data=null;try{data=raw?JSON.parse(raw):null}catch{data=raw}return{ok:r.ok,status:r.status,data,headers:r.headers}}catch{return{ok:false,status:503,data:{message:'Supabase admin service is temporarily unavailable.'},headers:new Headers()}}}
async function actor(request,env){const u=await session(request,env);if(!u)return null;const owners=[...emails(env.HEART_CONNECT_OWNER_EMAILS),...emails(env.HEART_CONNECT_ADMIN_EMAILS)];if(owners.includes(u.email))return{...u,role:'owner'};const r=await svc(env,'/rest/v1/hc_admin_staff?select=role,status&user_id=eq.'+encodeURIComponent(u.id)+'&status=eq.active&limit=1'),row=r.ok&&Array.isArray(r.data)?r.data[0]:null;return row?{...u,role:String(row.role||'')}:null}
async function requireRoles(request,env,roles){const a=await actor(request,env);if(!a)return{error:j({error:'Admin access denied.'},403)};if(!roles.includes(a.role))return{error:j({error:'Your admin role does not allow this lifecycle action.',role:a.role},403),actor:a};return{actor:a}}
function missing(r){return r?.status===404||/does not exist|PGRST205/i.test(String(r?.data?.message||r?.data||''))}
async function one(env,c,id){const field=c.id,value=String(id);const r=await svc(env,'/rest/v1/'+c.table+'?select='+encodeURIComponent(c.select)+'&'+field+'=eq.'+encodeURIComponent(value)+'&limit=1');return{...r,row:r.ok&&Array.isArray(r.data)?(r.data[0]||null):null}}
async function audit(env,a,action,target='',reason='',metadata={}){await svc(env,'/rest/v1/hc_admin_audit_log',{method:'POST',body:{actor_user_id:a.id,actor_email:a.email,actor_role:a.role,action:text(action,120),target:text(target,240),reason:text(reason,1000)||null,metadata,created_at:new Date().toISOString()},headers:{Prefer:'return=minimal'}}).catch(()=>{})}
async function trashEvent(env,a,type,id,action,reason,metadata={}){await svc(env,'/rest/v1/hc_admin_trash_events',{method:'POST',body:{entity_type:type,entity_id:String(id),action,reason:text(reason,1500)||null,actor_user_id:a.id,actor_email:a.email,actor_role:a.role,metadata,created_at:new Date().toISOString()},headers:{Prefer:'return=minimal'}}).catch(()=>{})}
function validEntityId(type,id){return type==='setting'?safeSetting(id):uuid(id)}

async function filteredList(request,env,kind){const a=await requireRoles(request,env,ALL_ADMIN_ROLES);if(a.error)return a.error;const map={cms_posts:{table:'hc_cms_posts',select:'id,title,slug,excerpt,body,status,featured_media_id,seo_title,seo_description,publish_channels,channel_results,scheduled_for,published_at,created_at,updated_at,deleted_at',order:'updated_at.desc'},cms_media:{table:'hc_cms_media',select:'id,post_id,media_type,storage_path,public_url,mime_type,width,height,duration_seconds,alt_text,created_at,deleted_at',order:'created_at.desc'},pages:{table:'hc_site_pages',select:'id,slug,title,page_type,status,content,seo_title,seo_description,published_at,created_at,updated_at,deleted_at',order:'updated_at.desc'},settings:{table:'hc_site_settings',select:'key,value,category,is_sensitive,updated_by,updated_at,deleted_at',order:'updated_at.desc'},campaigns:{table:'hc_notification_campaigns',select:'id,title,message,audience,channels,status,scheduled_for,sent_at,result_summary,created_by,created_at,updated_at,cancelled_at,cancellation_reason,deleted_at',order:'updated_at.desc'}}[kind];if(!map)return j({error:'Unsupported list.'},400);const r=await svc(env,'/rest/v1/'+map.table+'?select='+encodeURIComponent(map.select)+'&deleted_at=is.null&order='+encodeURIComponent(map.order)+'&limit=150');if(!r.ok)return j({error:text(r.data?.message||'Admin records could not be loaded.'),migrationRequired:missing(r)},r.status===503?503:500);if(kind==='campaigns')return j({items:r.data||[],deliveryAdapters:{in_app:false,email:false,push:false},note:'Campaigns can be drafted, scheduled and queued. Queueing is not proof of delivery.'});if(kind==='cms_posts')return j({items:r.data||[],socialPublishing:'External Facebook/TikTok/Google Business publishing remains API-gated and is not simulated.'});if(kind==='settings'){const providers={facebook:{credentialConfigured:!!env.FACEBOOK_PAGE_ACCESS_TOKEN},tiktok:{credentialConfigured:!!env.TIKTOK_ACCESS_TOKEN},google_business:{credentialConfigured:!!env.GOOGLE_BUSINESS_ACCESS_TOKEN}};return j({settings:r.data||[],social:[],providerReadiness:providers,rule:'Secrets/tokens are never readable or writable through the admin browser. Configure them as Cloudflare secrets.'})}return j({items:r.data||[]})}

async function trashList(request,env){const a=await requireRoles(request,env,ALL_ADMIN_ROLES);if(a.error)return a.error;const types=Object.entries(ENTITY),items=[];for(const [type,c] of types){const r=await svc(env,'/rest/v1/'+c.table+'?select='+encodeURIComponent(c.select)+'&deleted_at=not.is.null&order=deleted_at.desc&limit=100');if(r.ok)for(const x of (r.data||[]))items.push({entityType:type,entityId:String(x[c.id]),record:x});else if(!missing(r))return j({error:text(r.data?.message||'Trash could not be loaded.')},r.status===503?503:500)}items.sort((a,b)=>String(b.record.deleted_at||'').localeCompare(String(a.record.deleted_at||'')));const events=await svc(env,'/rest/v1/hc_admin_trash_events?select=id,entity_type,entity_id,action,reason,actor_email,actor_role,metadata,created_at&order=created_at.desc&limit=80');return j({items,events:events.ok?events.data:[],policy:{coolingPeriodDays:7,purgeRoles:PURGE_ROLES,neverPurge:['payments','audit','reports','verification','user_action_history','notification_delivery_history'],notificationCampaigns:'trash/restore only'}})}
async function lifecycle(request,env,type,id){const c=ENTITY[type];if(!c||!validEntityId(type,id))return j({error:'Invalid lifecycle target.'},400);const auth=await requireRoles(request,env,c.roles);if(auth.error)return auth.error;let b;try{b=await body(request)}catch(e){return j({error:e.message},e.status||400)}const action=text(b.action,20),reason=text(b.reason,1500);if(!['trash','restore','purge'].includes(action))return j({error:'Choose trash, restore, or purge.'},400);const cur=await one(env,c,id);if(!cur.ok)return j({error:text(cur.data?.message||'Record could not be loaded.'),migrationRequired:missing(cur)},cur.status===503?503:500);if(!cur.row)return j({error:'Record not found.'},404);if(action==='trash'){if(reason.length<3)return j({error:'Give a reason for moving this record to trash.'},400);if(cur.row.deleted_at)return j({error:'This record is already in trash.'},409);const now=new Date().toISOString(),r=await svc(env,'/rest/v1/'+c.table+'?'+c.id+'=eq.'+encodeURIComponent(id),{method:'PATCH',body:{deleted_at:now,deleted_by:auth.actor.id,delete_reason:reason,updated_at:now},headers:{Prefer:'return=representation'}});if(!r.ok)return j({error:text(r.data?.message||'Record could not be moved to trash.')},r.status===503?503:500);await trashEvent(env,auth.actor,type,id,'trash',reason);await audit(env,auth.actor,'admin.trash.'+type,id,reason);return j({ok:true,action:'trash',item:Array.isArray(r.data)?r.data[0]:r.data,permanent:false})}
if(action==='restore'){if(!cur.row.deleted_at)return j({error:'This record is not in trash.'},409);const now=new Date().toISOString(),r=await svc(env,'/rest/v1/'+c.table+'?'+c.id+'=eq.'+encodeURIComponent(id),{method:'PATCH',body:{deleted_at:null,deleted_by:null,delete_reason:null,updated_at:now},headers:{Prefer:'return=representation'}});if(!r.ok)return j({error:text(r.data?.message||'Record could not be restored.')},r.status===503?503:500);await trashEvent(env,auth.actor,type,id,'restore',reason);await audit(env,auth.actor,'admin.restore.'+type,id,reason);return j({ok:true,action:'restore',item:Array.isArray(r.data)?r.data[0]:r.data})}
if(!PURGE_ROLES.includes(auth.actor.role))return j({error:'Only the platform owner or super-admin can permanently purge eligible content.'},403);if(type==='notification_campaign')return j({error:'Notification campaigns cannot be permanently purged because delivery and operational history must remain reviewable. Archive or leave the campaign in trash.'},409);if(text(b.confirmation,20)!=='PURGE')return j({error:'Type PURGE to permanently delete this eligible content record.',confirmation:'PURGE'},409);if(!cur.row.deleted_at)return j({error:'Move the record to trash before permanent purge.'},409);const deletedAt=new Date(cur.row.deleted_at).getTime(),cool=7*86400000;if(!Number.isFinite(deletedAt)||Date.now()-deletedAt<cool)return j({error:'Permanent purge is available only after the 7-day cooling period.',eligibleAt:Number.isFinite(deletedAt)?new Date(deletedAt+cool).toISOString():null},409);if(type==='cms_media'&&cur.row.storage_path){const cc=cfg(env);let sr;try{sr=await fetch(cc.url+'/storage/v1/object/'+CMS_BUCKET+'/'+String(cur.row.storage_path).split('/').map(encodeURIComponent).join('/'),{method:'DELETE',headers:{apikey:cc.service,authorization:'Bearer '+cc.service}})}catch{return j({error:'Media storage could not be reached; nothing was purged.'},503)}if(!sr.ok&&sr.status!==404)return j({error:'Media storage deletion failed; database record was preserved.'},503)}const r=await svc(env,'/rest/v1/'+c.table+'?'+c.id+'=eq.'+encodeURIComponent(id),{method:'DELETE',headers:{Prefer:'return=representation'}});if(!r.ok)return j({error:text(r.data?.message||'Permanent purge failed.')},r.status===503?503:500);await trashEvent(env,auth.actor,type,id,'purge',reason,{coolingPeriodDays:7});await audit(env,auth.actor,'admin.purge.'+type,id,reason);return j({ok:true,action:'purge',permanent:true,note:'The append-only trash and admin audit events remain even after eligible content is purged.'})}

export async function handleAdmin(request,env){const u=new URL(request.url),p=u.pathname;if(p==='/admin'||p==='/admin/')return page(adminHtml(VERSION));if(!p.startsWith('/api/admin/'))return handleAdminV3(request,env);if(!sameOrigin(request))return j({error:'Cross-site admin request blocked.'},403);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{allow:'GET, POST, HEAD, OPTIONS'}});
  if(p==='/api/admin/trash'&&request.method==='GET')return trashList(request,env);
  let m=p.match(/^\/api\/admin\/lifecycle\/([^/]+)\/([^/]+)$/);if(m&&request.method==='POST')return lifecycle(request,env,m[1],decodeURIComponent(m[2]));
  if(p==='/api/admin/cms/posts'&&request.method==='GET')return filteredList(request,env,'cms_posts');
  if(p==='/api/admin/cms/media'&&request.method==='GET')return filteredList(request,env,'cms_media');
  if(p==='/api/admin/pages'&&request.method==='GET')return filteredList(request,env,'pages');
  if(p==='/api/admin/settings'&&request.method==='GET')return filteredList(request,env,'settings');
  if(p==='/api/admin/notifications/campaigns'&&request.method==='GET')return filteredList(request,env,'campaigns');
  return handleAdminV3(request,env)
}
