import {adminHtml as adminHtmlV18} from './admin-ui-v18.js';

export function adminHtml(version){
  const upgrade=`<style>
.hc19-photo-box{border:1px solid #ef5f8d38;background:linear-gradient(180deg,#17101a,#0a1119);border-radius:14px;padding:14px;margin:12px 0}.hc19-photo-box h3{margin:0}.hc19-photo-box p{margin:5px 0 10px;color:#94a1b5;font-size:12px;line-height:1.5}.hc19-photo-picker{border:1px dashed #ffffff26;background:#080d15;border-radius:12px;padding:14px}.hc19-photo-picker input{width:100%}.hc19-photo-preview{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:10px}.hc19-photo-preview figure{margin:0;border:1px solid #ffffff12;background:#05090f;border-radius:10px;padding:6px}.hc19-photo-preview img{width:100%;height:120px;object-fit:cover;border-radius:7px}.hc19-photo-preview figcaption{font-size:10px;color:#8c99ab;margin-top:5px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.hc19-select{width:100%;background:#080d15;border:1px solid #ffffff18;color:#fff;border-radius:10px;padding:10px 11px}.hc19-select[multiple]{min-height:132px}.hc19-place-note{font-size:11px;color:#8391a7;margin-top:5px;line-height:1.45}.hc19-place-loading{opacity:.65}.hc19-inline-status{font-size:11px;color:#9da9ba;margin-top:6px}.hc19-photo-badge{display:inline-flex;border:1px solid #ef5f8d42;background:#ef5f8d13;color:#ff91b3;border-radius:999px;padding:5px 8px;font-size:10px;font-weight:800;letter-spacing:.05em;text-transform:uppercase}
@media(max-width:650px){.hc19-photo-preview{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style><script>
(()=>{
  let countriesCache=null,activeUserId='';
  const cityCache=new Map();
  function h(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]})}
  async function rq(url,opt){const r=await fetch(url,Object.assign({credentials:'same-origin'},opt||{}));let d={};try{d=await r.json()}catch(e){}if(!r.ok){const er=new Error(d.error||'Request failed.');er.data=d;throw er}return d}
  function post(url,b){return rq(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)})}
  function multiValues(el){return el?[...el.selectedOptions].map(function(o){return o.value}).filter(Boolean):[]}
  function optionHtml(items,current,placeholder){let out=placeholder?'<option value="">'+h(placeholder)+'</option>':'';const set=new Set(items||[]);if(current&&!set.has(current))out+='<option value="'+h(current)+'" selected>'+h(current)+'</option>';for(const x of items||[])out+='<option value="'+h(x)+'"'+(x===current?' selected':'')+'>'+h(x)+'</option>';return out}
  function replaceInput(id,kind){const old=document.getElementById(id);if(!old||old.tagName==='SELECT')return old;const value=old.value||'',sel=document.createElement('select');sel.id=id;sel.className='hc19-select';sel.dataset.current=value;if(kind==='multi')sel.multiple=true;sel.innerHTML='<option value="">Loading places…</option>';old.replaceWith(sel);return sel}
  async function countries(){if(countriesCache)return countriesCache;const d=await rq('/api/admin/locations/countries');countriesCache=d.items||[];return countriesCache}
  async function fillCountries(sel,current,multiple){if(!sel)return;sel.classList.add('hc19-place-loading');try{const items=await countries();sel.innerHTML=multiple?items.map(function(x){return '<option value="'+h(x)+'">'+h(x)+'</option>'}).join(''):optionHtml(items,current,'Select country / region');if(multiple&&current){const values=Array.isArray(current)?current:String(current).split(',').map(function(x){return x.trim()}).filter(Boolean);for(const o of sel.options)o.selected=values.includes(o.value)}}catch(e){sel.innerHTML='<option value="">Location directory unavailable</option>'}finally{sel.classList.remove('hc19-place-loading')}}
  async function fillCities(sel,country,current){if(!sel)return;sel.disabled=true;sel.classList.add('hc19-place-loading');if(!country){sel.innerHTML='<option value="">Choose country first</option>';sel.classList.remove('hc19-place-loading');return}try{let items=cityCache.get(country);if(!items){const d=await rq('/api/admin/locations/cities?country='+encodeURIComponent(country));items=d.items||[];cityCache.set(country,items)}sel.innerHTML=optionHtml(items,current,items.length?'Select city / town':'No listed cities available');sel.disabled=!items.length}catch(e){sel.innerHTML='<option value="">City directory unavailable</option>';sel.disabled=true}finally{sel.classList.remove('hc19-place-loading')}}
  function photoFiles(){const el=document.getElementById('hc19AddPhotos');return el?[...el.files].slice(0,6):[]}
  function renderPhotoPreview(){const host=document.getElementById('hc19PhotoPreview');if(!host)return;const files=photoFiles();host.innerHTML=files.map(function(f){return '<figure><img src="'+h(URL.createObjectURL(f))+'" alt="Selected profile photo"><figcaption>'+h(f.name)+'</figcaption></figure>'}).join('')}
  function addPhotoBox(){const body=document.getElementById('modalBody');if(!body||!document.getElementById('hc16AddEmail')||document.getElementById('hc19PhotoBox'))return;const box=document.createElement('section');box.id='hc19PhotoBox';box.className='hc19-photo-box';box.innerHTML='<div style="display:flex;justify-content:space-between;gap:10px;align-items:flex-start"><div><h3>Profile photos</h3><p>Select up to 6 real photos for an existing member you are onboarding. Photos upload only after the real Heart Connect account is confirmed.</p></div><span class="hc19-photo-badge">Upload</span></div><div class="hc19-photo-picker"><input id="hc19AddPhotos" type="file" accept="image/jpeg,image/png,image/webp" multiple><div class="hc19-place-note">JPG, PNG or WebP. Each photo stays pending until human approval before it can qualify the profile for Discover.</div><div class="hc19-photo-preview" id="hc19PhotoPreview"></div></div><div class="hc19-inline-status" id="hc19PhotoState"></div>';const consent=document.getElementById('hc16Consent')?.closest('label');if(consent)consent.parentNode.insertBefore(box,consent);else body.appendChild(box);document.getElementById('hc19AddPhotos').onchange=function(){if(this.files.length>6){const dt=new DataTransfer();[...this.files].slice(0,6).forEach(function(f){dt.items.add(f)});this.files=dt.files}renderPhotoPreview()}}
  async function setupAddPlaces(){const email=document.getElementById('hc16AddEmail');if(!email||document.getElementById('hc19AddReady'))return;const country=replaceInput('hc16AddCountry','single'),city=replaceInput('hc16AddCity','single'),prefs=replaceInput('hc17Countries','multi');if(!country||!city)return;country.setAttribute('aria-label','Country / region');city.setAttribute('aria-label','City / town');const marker=document.createElement('span');marker.id='hc19AddReady';marker.hidden=true;document.getElementById('modalBody').appendChild(marker);await fillCountries(country,country.dataset.current||'',false);await fillCities(city,country.value,city.dataset.current||'');country.onchange=function(){fillCities(city,country.value,'')};await fillCountries(prefs,[],true);addPhotoBox();overrideOnboard()}
  function addValue(id){return document.getElementById(id)?.value||''}
  function overrideOnboard(){const btn=document.getElementById('hc16Onboard');if(!btn||btn.dataset.hc19)return;btn.dataset.hc19='1';btn.onclick=async function(){const state=document.getElementById('hc16AddState'),photoState=document.getElementById('hc19PhotoState');if(!document.getElementById('hc16Consent')?.checked){state.textContent='Confirm member consent before continuing.';return}const country=addValue('hc16AddCountry'),city=addValue('hc16AddCity');if(!country||!city){state.textContent='Choose the member country and city/town from the lists.';return}state.textContent='Creating member profile…';btn.disabled=true;const payload={email:addValue('hc16AddEmail'),displayName:addValue('hc16AddName'),age:addValue('hc16AddAge'),gender:addValue('hc16AddGender'),country,city,relationshipIntention:addValue('hc16AddGoal'),headline:addValue('hc16AddHeadline'),bio:addValue('hc16AddBio'),occupation:addValue('hc16AddOccupation'),education:addValue('hc16AddEducation'),languages:addValue('hc16AddLanguages'),interests:addValue('hc16AddInterests'),consentConfirmed:true,confirmation:'CONSENT',reason:'Admin-assisted onboarding requested by member'};try{const d=await post('/api/admin/users/onboard-existing',payload),uid=d.userId;state.textContent='Profile created. Saving location…';const mode=document.getElementById('hc17Mode')?.value!=='local';await post('/api/admin/users/'+encodeURIComponent(uid)+'/location',{country,city,globalMode:mode,countries:multiValues(document.getElementById('hc17Countries')),maxDistanceKm:addValue('hc17Radius'),reason:'Admin-assisted onboarding location settings'});const files=photoFiles();let uploaded=0;for(const file of files){if(photoState)photoState.textContent='Uploading photo '+(uploaded+1)+' of '+files.length+'…';const fd=new FormData();fd.append('file',file);fd.append('reason','Admin-assisted onboarding profile photo');try{await rq('/api/admin/users/'+encodeURIComponent(uid)+'/media',{method:'POST',body:fd});uploaded++}catch(e){if(photoState)photoState.textContent='Profile created. '+uploaded+' photo(s) uploaded; another photo needs retry from Manage.';break}}if(photoState&&uploaded===files.length)photoState.textContent=uploaded?uploaded+' photo(s) uploaded as pending review.':'No photos selected.';if(typeof modal!=='undefined')modal.close();if(typeof say==='function')say('Member onboarded. '+uploaded+' photo(s) uploaded as pending review.');if(typeof load==='function')load('users')}catch(e){state.textContent=e.message}finally{btn.disabled=false}}
  }
  async function setupManagePlaces(){const countryOld=document.getElementById('hc17Country'),cityOld=document.getElementById('hc17City');if(!countryOld||!cityOld||document.getElementById('hc19ManageReady'))return;const currentCountry=countryOld.value||'',currentCity=cityOld.value||'',country=replaceInput('hc17Country','single'),city=replaceInput('hc17City','single'),prefs=replaceInput('hc17ManageCountries','multi');const marker=document.createElement('span');marker.id='hc19ManageReady';marker.hidden=true;document.getElementById('modalBody').appendChild(marker);await fillCountries(country,currentCountry,false);await fillCities(city,country.value,currentCity);country.onchange=function(){fillCities(city,country.value,'')};const prior=prefs?.dataset.current||'';await fillCountries(prefs,prior?prior.split(',').map(function(x){return x.trim()}).filter(Boolean):[],true);const save=document.getElementById('hc17SaveLocation');if(save&&!save.dataset.hc19){save.dataset.hc19='1';save.onclick=async function(){const state=document.getElementById('hc17LocationState');state.textContent='Saving location…';try{const d=await post('/api/admin/users/'+encodeURIComponent(activeUserId)+'/location',{country:country.value,city:city.value,globalMode:document.getElementById('hc17ManageMode')?.value!=='local',countries:multiValues(prefs),maxDistanceKm:document.getElementById('hc17ManageRadius')?.value||'',reason:'Admin updated member location and discovery preferences'});document.getElementById('hc17LocationLabel').textContent=d.locationLabel||'';state.textContent='Location saved from verified place lists.'}catch(e){state.textContent=e.message}}}}
  document.addEventListener('click',function(e){const b=e.target?.closest?.('[data-user]');if(b?.dataset?.user)activeUserId=b.dataset.user},true);
  function enhance(){setupAddPlaces();setupManagePlaces()}
  const target=document.getElementById('modalBody')||document.body;new MutationObserver(function(){setTimeout(enhance,0)}).observe(target,{childList:true,subtree:true});enhance();
})();
</script>`;
  return adminHtmlV18(version).replace('</body>',upgrade+'</body>');
}
