import {handleAdmin as handleAdminV19,runPhase7AndEarlierScheduled} from './admin-api-v19.js';
import {adminHtml} from './admin-ui-v20.js';

export {runPhase7AndEarlierScheduled};
export const VERSION='hc-admin-control-plane-v20';
const MAPBOX_GL_VERSION='3.30.0';

function text(v,n=256){return String(v??'').trim().slice(0,n)}
function j(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer','x-heart-connect-admin':VERSION}})}
function page(html,head=false){const headers={'content-type':'text/html; charset=utf-8','cache-control':'no-store, max-age=0','pragma':'no-cache','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin','x-frame-options':'DENY','permissions-policy':'camera=(), microphone=(), geolocation=(), payment=(), usb=(), serial=()','cross-origin-opener-policy':'same-origin','cross-origin-resource-policy':'same-origin','strict-transport-security':'max-age=31536000; includeSubDomains','content-security-policy':"default-src 'self'; style-src 'self' 'unsafe-inline' https://api.mapbox.com; script-src 'self' 'unsafe-inline' https://api.mapbox.com; img-src 'self' data: blob: https:; media-src 'self' blob: https:; connect-src 'self' https://api.mapbox.com https://events.mapbox.com; worker-src blob:; child-src blob:; frame-src 'self' data: blob:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; object-src 'none'",'x-heart-connect-admin':VERSION};return new Response(head?null:html,{status:200,headers})}
function sameOrigin(request){const site=request.headers.get('sec-fetch-site');if(site==='cross-site')return false;const origin=request.headers.get('origin');if(!origin)return true;try{return new URL(origin).origin===new URL(request.url).origin}catch{return false}}
async function actorFor(request,env){const u=new URL(request.url);u.pathname='/api/admin/capabilities';u.search='';const r=await handleAdminV19(new Request(u.toString(),{method:'GET',headers:request.headers}),env);if(!r)return null;let d={};try{d=await r.clone().json()}catch{}if(!r.ok)return null;const actor=d.actor||null,p=actor?.permissions||[];return actor&&(p.includes('*')||p.includes('users')||p.includes('users:read')||p.includes('users:write'))?actor:null}
function mapToken(env){const token=text(env.MAPBOX_PUBLIC_TOKEN,1200);return token.startsWith('pk.')?token:''}
async function mapFetch(url){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),9000);try{const r=await fetch(url,{signal:ctl.signal,headers:{accept:'application/json'}});if(!r.ok)return{ok:false,status:r.status,data:null};return{ok:true,status:r.status,data:await r.json()}}catch{return{ok:false,status:503,data:null}}finally{clearTimeout(timer)}}
function feature(f){const p=f?.properties||{},ctx=p.context||{},g=Array.isArray(f?.geometry?.coordinates)?f.geometry.coordinates:[],coords=p.coordinates||{};const lng=Number(coords.longitude??g[0]),lat=Number(coords.latitude??g[1]),type=text(p.feature_type||f?.feature_type||f?.place_type?.[0],40),name=text(p.name||p.name_preferred||f?.text,160);let country=text(ctx?.country?.name,120),city=text(ctx?.place?.name||ctx?.locality?.name,120);if(type==='country'&&!country)country=name;if((type==='place'||type==='locality')&&!city)city=name;return{id:text(f?.id,180),name,fullName:text(p.full_address||p.place_formatted||f?.place_name||[city,country].filter(Boolean).join(', '),280),country,city,longitude:Number.isFinite(lng)?lng:null,latitude:Number.isFinite(lat)?lat:null,placeType:type}}
async function config(request,env){const actor=await actorFor(request,env);if(!actor)return j({error:'Admin authentication required.'},401);const token=mapToken(env);return j({configured:!!token,publicToken:token||null,glJsVersion:MAPBOX_GL_VERSION,style:'mapbox://styles/mapbox/standard',storesExactCoordinates:false,note:token?'Mapbox is ready. Map clicks and search results are used to select city/country; Heart Connect Admin does not store exact coordinates from this picker.':'Add a Mapbox public access token as MAPBOX_PUBLIC_TOKEN in the Cloudflare Worker environment to enable the interactive map.'})}
async function forward(request,env){const actor=await actorFor(request,env);if(!actor)return j({error:'Admin authentication required.'},401);const token=mapToken(env);if(!token)return j({error:'Mapbox is not configured.',configured:false},503);const u=new URL(request.url),q=text(u.searchParams.get('q'),256);if(q.length<2)return j({items:[]});const api='https://api.mapbox.com/search/geocode/v6/forward?q='+encodeURIComponent(q)+'&types=place,locality,district,country&autocomplete=true&limit=8&access_token='+encodeURIComponent(token);const r=await mapFetch(api);if(!r.ok)return j({error:'Mapbox place search is temporarily unavailable.'},r.status===401||r.status===403?503:502);const items=(r.data?.features||[]).map(feature).filter(x=>x.name&&x.longitude!==null&&x.latitude!==null);return j({items,temporarySelection:true,storesExactCoordinates:false})}
async function reverse(request,env){const actor=await actorFor(request,env);if(!actor)return j({error:'Admin authentication required.'},401);const token=mapToken(env);if(!token)return j({error:'Mapbox is not configured.',configured:false},503);const u=new URL(request.url),lng=Number(u.searchParams.get('lng')),lat=Number(u.searchParams.get('lat'));if(!Number.isFinite(lng)||lng< -180||lng>180||!Number.isFinite(lat)||lat< -90||lat>90)return j({error:'Invalid map coordinates.'},400);const api='https://api.mapbox.com/search/geocode/v6/reverse?longitude='+encodeURIComponent(lng)+'&latitude='+encodeURIComponent(lat)+'&types=place,locality,district,country&limit=5&access_token='+encodeURIComponent(token);const r=await mapFetch(api);if(!r.ok)return j({error:'Mapbox reverse lookup is temporarily unavailable.'},r.status===401||r.status===403?503:502);const items=(r.data?.features||[]).map(feature).filter(x=>x.country||x.city);const best=items.find(x=>x.city&&x.country)||items.find(x=>x.country)||null;return j({item:best,temporarySelection:true,storesExactCoordinates:false})}

export async function handleAdmin(request,env){
  const u=new URL(request.url),p=u.pathname;
  if((p==='/admin'||p==='/admin/')&&(request.method==='GET'||request.method==='HEAD'))return page(adminHtml(VERSION),request.method==='HEAD');if(!p.startsWith('/api/admin/'))return handleAdminV19(request,env);
  if(!sameOrigin(request))return j({error:'Cross-site admin request blocked.'},403);
  if(p==='/api/admin/mapbox/config'&&request.method==='GET')return config(request,env);
  if(p==='/api/admin/mapbox/forward'&&request.method==='GET')return forward(request,env);
  if(p==='/api/admin/mapbox/reverse'&&request.method==='GET')return reverse(request,env);
  return handleAdminV19(request,env);
}
