import {handleAdmin as handleAdminV2} from './admin-api-v2-guard.js';
import {adminHtml} from './admin-ui-v3.js';

export const VERSION='hc-admin-control-plane-v3';
const ACCESS_COOKIE='__Host-hc_cf_access';
const DEFAULT_SUPABASE_URL='https://zzhzkikezjtbntaqiurk.supabase.co';
const DEFAULT_PUBLISHABLE_KEY='sb_publishable_HB0Irz6bxug1hHs518oPZQ_LC83i4qT';
const ROLES=['super_admin','admin','moderator','senior_moderator','safety_specialist','payment_specialist','support_agent','content_manager','verification_specialist','finance'];
const STAFF_READ=['owner','super_admin','admin'];
const STAFF_WRITE=['owner','super_admin'];
const MARKET_WRITE=['owner','super_admin','admin'];
const NOTIFICATION_READ=['owner','super_admin','admin','content_manager','support_agent'];
const NOTIFICATION_WRITE=['owner','super_admin','admin','content_manager'];
const ANALYTICS_READ=['owner','super_admin','admin','finance','content_manager'];
const SETTINGS_READ=['owner','super_admin','admin','content_manager'];
const SETTINGS_WRITE=['owner','super_admin','admin'];
const PAGES_WRITE=['owner','super_admin','admin','content_manager'];

function cfg(env){return{url:String(env.SUPABASE_URL||DEFAULT_SUPABASE_URL).replace(/\/+$/,''),publishable:String(env.SUPABASE_PUBLISHABLE_KEY||DEFAULT_PUBLISHABLE_KEY),service:String(env.SUPABASE_SERVICE_ROLE_KEY||'')}}
function cookies(request){const out={};for(const part of String(request.headers.get('cookie')||'').split(';')){const i=part.indexOf('=');if(i>0){const k=part.slice(0,i).trim();try{out[k]=decodeURIComponent(part.slice(i+1).trim())}catch{out[k]=part.slice(i+1).trim()}}}return out}
function j(data,status=200,extra={}){const h=new Headers({'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-heart-connect-admin':VERSION,...extra});return new Response(JSON.stringify(data),{status,headers:h})}
function page(html,status=200){return new Response(html,{status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'same-origin','x-frame-options':'DENY','content-security-policy':"default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'",'x-heart-connect-admin':VERSION}})}
function unsafe(request){return !['GET','HEAD','OPTIONS'].includes(request.method)}
function sameOrigin(request){if(!unsafe(request))return true;const site=request.headers.get('sec-fetch-site');if(site==='cross-site')return false;const origin=request.headers.get('origin');if(!origin)return true;try{return new URL(origin).origin===new URL(request.url).origin}catch{return false}}
function text(v,n=1000){return String(v??'').trim().slice(0,n)}
function email(v){const s=text(v,320).toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)?s:''}
function emails(v){return String(v||'').split(',').map(email).filter(Boolean)}
function uuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''))}
function slugify(v){return text(v,220).toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,180)}
function clamp(n,min,max){return Math.max(min,Math.min(max,Number(n)||min))}
function cleanValue(v){if(Array.isArray(v))return v.slice(0,100).map(cleanValue);if(v&&typeof v==='object'){const out={};for(const [k,x] of Object.entries(v)){if(/secret|password|token|authorization|api.?key|private.?key/i.test(k))continue;out[text(k,100)]=cleanValue(x)}return out}if(typeof v==='string')return v.slice(0,10000);if(typeof v==='number'||typeof v==='boolean'||v===null)return v;return String(v??'').slice(0,10000)}
async function jsonBody(request,max=200000){const len=Number(request.headers.get('content-length')||0);if(len>max)throw Object.assign(new Error('Request is too large.'),{status:413});const raw=await request.text();if(raw.length>max)throw Object.assign(new Error('Request is too large.'),{status:413});try{return raw?JSON.parse(raw):{}}catch{throw Object.assign(new Error('Valid JSON is required.'),{status:400})}}
async function userSession(request,env){const c=cfg(env),token=cookies(request)[ACCESS_COOKIE]||'';if(!token)return null;try{const r=await fetch(c.url+'/auth/v1/user',{headers:{apikey:c.publishable,authorization:'Bearer '+token,accept:'application/json'}});if(!r.ok)return null;const u=await r.json();return u?.id?{id:u.id,email:email(u.email),token}:null}catch{return null}}
async function svc(env,path,{method='GET',body,headers:extra}={}){const c=cfg(env);if(!c.service)return{ok:false,status:503,data:{message:'Admin data service is not configured.'},headers:new Headers()};const headers=new Headers({apikey:c.service,authorization:'Bearer '+c.service,accept:'application/json',...extra});if(body!==undefined)headers.set('content-type','application/json');try{const r=await fetch(c.url+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),raw=await r.text();let data=null;try{data=raw?JSON.parse(raw):null}catch{data=raw}return{ok:r.ok,status:r.status,data,headers:r.headers}}catch{return{ok:false,status:503,data:{message:'Supabase admin service is temporarily unavailable.'},headers:new Headers()}}}
async function actor(request,env){const u=await userSession(request,env);if(!u)return null;const owners=[...emails(env.HEART_CONNECT_OWNER_EMAILS),...emails(env.HEART_CONNECT_ADMIN_EMAILS)];if(owners.includes(u.email))return{...u,role:'owner',displayName:'Platform Owner'};const r=await svc(env,'/rest/v1/hc_admin_staff?select=role,status,display_name,email&user_id=eq.'+encodeURIComponent(u.id)+'&status=eq.active&limit=1'),row=r.ok&&Array.isArray(r.data)?r.data[0]:null;return row?{...u,role:String(row.role||''),displayName:text(row.display_name,100)||u.email}:null}
async function requireRoles(request,env,roles){const a=await actor(request,env);if(!a)return{error:j({error:'Admin access denied.'},403)};if(!roles.includes(a.role))return{error:j({error:'Your admin role does not allow this action.',role:a.role},403),actor:a};return{actor:a}}
async function audit(env,a,action,target='',reason='',metadata={}){await svc(env,'/rest/v1/hc_admin_audit_log',{method:'POST',body:{actor_user_id:a.id,actor_email:a.email,actor_role:a.role,action:text(action,120),target:text(target,240),reason:text(reason,1000)||null,metadata:cleanValue(metadata),created_at:new Date().toISOString()},headers:{Prefer:'return=minimal'}}).catch(()=>{})}
function missing(r){return r?.status===404||/does not exist|PGRST205/i.test(String(r?.data?.message||r?.data||''))}
async function one(env,table,select,filter){const r=await svc(env,'/rest/v1/'+table+'?select='+encodeURIComponent(select)+'&'+filter+'&limit=1');return{...r,row:r.ok&&Array.isArray(r.data)?(r.data[0]||null):null}}
async function list(env,table,select,order='created_at.desc',limit=100,filter=''){return svc(env,'/rest/v1/'+table+'?select='+encodeURIComponent(select)+(filter?'&'+filter:'')+'&order='+encodeURIComponent(order)+'&limit='+clamp(limit,1,500))}
async function count(env,table,filter=''){const key=table==='dating_profiles'?'user_id':'id';const r=await svc(env,'/rest/v1/'+table+'?select='+encodeURIComponent(key)+'&limit=1'+(filter?'&'+filter:''),{headers:{Prefer:'count=exact',Range:'0-0'}});if(!r.ok)return null;const cr=String(r.headers.get('content-range')||''),n=Number(cr.split('/')[1]);return Number.isFinite(n)?n:(Array.isArray(r.data)?r.data.length:0)}

async function phase3Status(request,env){const a=await requireRoles(request,env,['owner','super_admin','admin','moderator','senior_moderator','safety_specialist','payment_specialist','support_agent','content_manager','verification_specialist','finance']);if(a.error)return a.error;const c=cfg(env);return j({version:VERSION,actor:a.actor,serviceRoleConfigured:!!c.service,features:{analytics:true,staffRegistry:true,marketEditing:true,notificationCampaigns:true,deliveryQueue:true,pageEditor:true,siteSettings:true,socialConnectionReadiness:true},externalDelivery:{email:false,push:false,facebook:false,tiktok:false,googleBusiness:false},note:'Phase 3 can prepare and queue work, but it never claims an external provider delivered or published content unless a real provider adapter confirms it.'})}

async function analytics(request,env){const a=await requireRoles(request,env,ANALYTICS_READ);if(a.error)return a.error;const days=clamp(new URL(request.url).searchParams.get('days'),1,365),since=new Date(Date.now()-days*86400000).toISOString(),f='created_at=gte.'+encodeURIComponent(since);const [profiles,newProfiles,reports,openReports,verification,pendingVerification,matches,newMatches,messages,newMessages,publishedPosts,campaigns]=await Promise.all([count(env,'dating_profiles'),count(env,'dating_profiles',f),count(env,'reports'),count(env,'reports','status=in.(new,reviewing)'),count(env,'verification_requests'),count(env,'verification_requests','status=eq.pending'),count(env,'matches'),count(env,'matches',f),count(env,'messages'),count(env,'messages',f),count(env,'hc_cms_posts','status=eq.published'),count(env,'hc_notification_campaigns')]);await audit(env,a.actor,'admin.analytics.view','', '',{days});return j({days,since,metrics:{profiles,newProfiles,reports,openReports,verification,pendingVerification,matches,newMatches,messages,newMessages,publishedPosts,campaigns},privacy:'Only aggregate counts are returned. Message bodies and sensitive profile traits are excluded.',availability:{profiles:profiles!==null,reports:reports!==null,verification:verification!==null,matches:matches!==null,messages:messages!==null,cms:publishedPosts!==null,notifications:campaigns!==null}})}

async function staffList(request,env){const a=await requireRoles(request,env,STAFF_READ);if(a.error)return a.error;const r=await list(env,'hc_admin_staff','user_id,email,display_name,role,status,created_by,created_at,updated_at','updated_at.desc',200);if(!r.ok)return j({error:text(r.data?.message||'Staff registry could not be loaded.'),migrationRequired:missing(r)},r.status===503?503:500);await audit(env,a.actor,'admin.staff.list');return j({items:r.data||[],roles:ROLES,rule:'Only owner/super-admin can add or change admin roles in Phase 3.'})}
async function staffSave(request,env){const a=await requireRoles(request,env,STAFF_WRITE);if(a.error)return a.error;let b;try{b=await jsonBody(request)}catch(e){return j({error:e.message},e.status||400)}const userId=text(b.userId,80),mail=email(b.email),role=text(b.role,40),status=text(b.status||'active',20),name=text(b.displayName,100);if(!uuid(userId)||!mail||!ROLES.includes(role)||!['active','inactive','suspended'].includes(status))return j({error:'Provide a valid existing user ID, email, role and staff status.'},400);if(userId===a.actor.id&&status!=='active')return j({error:'You cannot deactivate your own current owner/super-admin session from this screen.'},409);const row={user_id:userId,email:mail,display_name:name||null,role,status,created_by:a.actor.id,updated_at:new Date().toISOString()};const r=await svc(env,'/rest/v1/hc_admin_staff?on_conflict=user_id',{method:'POST',body:row,headers:{Prefer:'resolution=merge-duplicates,return=representation'}});if(!r.ok)return j({error:text(r.data?.message||'Staff role could not be saved.'),migrationRequired:missing(r)},r.status===503?503:500);await audit(env,a.actor,'admin.staff.save',userId,'',{role,status,email:mail});return j({ok:true,item:Array.isArray(r.data)?r.data[0]:r.data})}

async function marketSave(request,env,code){const a=await requireRoles(request,env,MARKET_WRITE);if(a.error)return a.error;code=text(code,12).toUpperCase();if(!/^[A-Z0-9]{2,12}$/.test(code))return j({error:'Invalid market code.'},400);let b;try{b=await jsonBody(request)}catch(e){return j({error:e.message},e.status||400)}const current=await one(env,'hc_admin_markets','*','code=eq.'+encodeURIComponent(code));const old=current.row||{};const status=text(b.status??old.status??'beta',30);if(!['coming_soon','invite_only','beta','live','paused'].includes(status))return j({error:'Invalid market status.'},400);const country=text(b.country??old.country,100),currency=text(b.currency??old.currency,12).toUpperCase();if(!country||!/^[A-Z]{3}$/.test(currency))return j({error:'Country and 3-letter currency are required.'},400);const row={code,country,currency,status,registration_enabled:b.registrationEnabled??old.registration_enabled??true,discovery_enabled:b.discoveryEnabled??old.discovery_enabled??true,payments_enabled:b.paymentsEnabled??old.payments_enabled??false,legal_version:text(b.legalVersion??old.legal_version,120)||null,support_route:text(b.supportRoute??old.support_route,160)||null,default_language:text(b.defaultLanguage??old.default_language,40)||null,timezone:text(b.timezone??old.timezone,80)||null,distance_unit:['km','mi'].includes(String(b.distanceUnit??old.distance_unit))?String(b.distanceUnit??old.distance_unit):null,legal_review_status:['pending','reviewed','approved','blocked'].includes(String(b.legalReviewStatus??old.legal_review_status))?String(b.legalReviewStatus??old.legal_review_status):'pending',updated_by:a.actor.id,updated_at:new Date().toISOString()};const r=await svc(env,'/rest/v1/hc_admin_markets?on_conflict=code',{method:'POST',body:row,headers:{Prefer:'resolution=merge-duplicates,return=representation'}});if(!r.ok)return j({error:text(r.data?.message||'Market could not be saved.'),migrationRequired:missing(r)},r.status===503?503:500);await audit(env,a.actor,'admin.market.save',code,'',{status,row:{...row,updated_by:undefined}});return j({ok:true,item:Array.isArray(r.data)?r.data[0]:r.data})}

function normalizeAudience(v){const a=v&&typeof v==='object'?v:{type:'all'},type=text(a.type||'all',30);if(!['all','country','verified','inactive','tier','user_list'].includes(type))throw new Error('Unsupported audience type.');const out={type};if(type==='country'){out.country=text(a.country,100);if(!out.country)throw new Error('Audience country is required.')}if(type==='tier'){out.tier=text(a.tier,30);if(!out.tier)throw new Error('Audience tier is required.')}if(type==='inactive')out.inactiveDays=clamp(a.inactiveDays||30,7,365);if(type==='user_list'){out.userIds=(Array.isArray(a.userIds)?a.userIds:[]).filter(uuid).slice(0,100);if(!out.userIds.length)throw new Error('At least one valid user ID is required.')}return out}
function normalizeChannels(v){const x=v&&typeof v==='object'?v:{};return{in_app:x.in_app===true,email:x.email===true,push:x.push===true}}
async function campaignList(request,env){const a=await requireRoles(request,env,NOTIFICATION_READ);if(a.error)return a.error;const r=await list(env,'hc_notification_campaigns','id,title,message,audience,channels,status,scheduled_for,sent_at,result_summary,created_by,created_at,updated_at,cancelled_at,cancellation_reason','updated_at.desc',150);if(!r.ok)return j({error:text(r.data?.message||'Notification campaigns could not be loaded.'),migrationRequired:missing(r)},r.status===503?503:500);return j({items:r.data||[],deliveryAdapters:{in_app:false,email:false,push:false},note:'Campaigns can be drafted, scheduled and queued. Queueing is not proof of delivery.'})}
async function campaignSave(request,env){const a=await requireRoles(request,env,NOTIFICATION_WRITE);if(a.error)return a.error;let b;try{b=await jsonBody(request)}catch(e){return j({error:e.message},e.status||400)}const id=text(b.id,80),title=text(b.title,160),message=text(b.message,2000);if(id&&!uuid(id))return j({error:'Invalid campaign ID.'},400);if(!title||!message)return j({error:'Campaign title and message are required.'},400);let audience;try{audience=normalizeAudience(b.audience)}catch(e){return j({error:e.message},400)}const channels=normalizeChannels(b.channels);if(!channels.in_app&&!channels.email&&!channels.push)return j({error:'Choose at least one delivery channel.'},400);const status=text(b.status||'draft',20);if(!['draft','scheduled'].includes(status))return j({error:'Campaigns can be saved only as draft or scheduled from this screen.'},400);let scheduledFor=null;if(status==='scheduled'){const d=new Date(String(b.scheduledFor||''));if(Number.isNaN(d.getTime())||d.getTime()<=Date.now())return j({error:'A future schedule time is required.'},400);scheduledFor=d.toISOString()}const row={title,message,audience,channels,status,scheduled_for:scheduledFor,updated_by:a.actor.id,updated_at:new Date().toISOString()};let r;if(id)r=await svc(env,'/rest/v1/hc_notification_campaigns?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:row,headers:{Prefer:'return=representation'}});else r=await svc(env,'/rest/v1/hc_notification_campaigns',{method:'POST',body:{...row,created_by:a.actor.id,created_at:new Date().toISOString()},headers:{Prefer:'return=representation'}});if(!r.ok)return j({error:text(r.data?.message||'Campaign could not be saved.'),migrationRequired:missing(r)},r.status===503?503:500);const item=Array.isArray(r.data)?r.data[0]:r.data;await audit(env,a.actor,id?'admin.notification.update':'admin.notification.create',item?.id||id||title,'',{audience,channels,status});return j({ok:true,item})}
async function resolveRecipients(env,audience){let filter='';if(audience.type==='country')filter='country=eq.'+encodeURIComponent(audience.country);if(audience.type==='verified')filter='verification_level=neq.unverified';if(audience.type==='inactive'){const before=new Date(Date.now()-Number(audience.inactiveDays||30)*86400000).toISOString();filter='last_active_at=lt.'+encodeURIComponent(before)}if(audience.type==='tier')filter='tier=eq.'+encodeURIComponent(audience.tier);if(audience.type==='user_list')return{items:audience.userIds.map(user_id=>({user_id})),limited:false};const r=await list(env,'dating_profiles','user_id','created_at.asc',500,filter);if(!r.ok)return{error:r};return{items:r.data||[],limited:(r.data||[]).length>=500}}
async function campaignAction(request,env,id){const a=await requireRoles(request,env,NOTIFICATION_WRITE);if(a.error)return a.error;if(!uuid(id))return j({error:'Invalid campaign ID.'},400);let b;try{b=await jsonBody(request)}catch(e){return j({error:e.message},e.status||400)}const action=text(b.action,20),cur=await one(env,'hc_notification_campaigns','*','id=eq.'+encodeURIComponent(id));if(!cur.ok)return j({error:text(cur.data?.message||'Campaign could not be loaded.')},cur.status===503?503:500);if(!cur.row)return j({error:'Campaign not found.'},404);if(action==='cancel'){const reason=text(b.reason,1000);if(reason.length<3)return j({error:'Give a cancellation reason.'},400);const r=await svc(env,'/rest/v1/hc_notification_campaigns?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:{status:'cancelled',cancelled_at:new Date().toISOString(),cancellation_reason:reason,updated_by:a.actor.id,updated_at:new Date().toISOString()},headers:{Prefer:'return=representation'}});if(!r.ok)return j({error:text(r.data?.message||'Campaign could not be cancelled.')},r.status===503?503:500);await audit(env,a.actor,'admin.notification.cancel',id,reason);return j({ok:true,item:Array.isArray(r.data)?r.data[0]:r.data})}if(action!=='queue')return j({error:'Choose queue or cancel.'},400);if(text(b.confirmation,20)!=='QUEUE')return j({error:'Type QUEUE to prepare delivery records.',confirmation:'QUEUE'},409);if(['cancelled','sent','sending'].includes(String(cur.row.status)))return j({error:'This campaign cannot be queued in its current state.',status:cur.row.status},409);const channels=normalizeChannels(cur.row.channels),audience=normalizeAudience(cur.row.audience),resolved=await resolveRecipients(env,audience);if(resolved.error)return j({error:text(resolved.error.data?.message||'Audience could not be resolved.')},resolved.error.status===503?503:500);const rows=[];for(const x of resolved.items){for(const ch of ['in_app','email','push'])if(channels[ch])rows.push({campaign_id:id,recipient_user_id:x.user_id,channel:ch,status:'queued',provider:null,attempt_count:0,created_at:new Date().toISOString(),updated_at:new Date().toISOString()})}if(rows.length){const r=await svc(env,'/rest/v1/hc_notification_delivery_queue?on_conflict=campaign_id,recipient_user_id,channel',{method:'POST',body:rows,headers:{Prefer:'resolution=ignore-duplicates,return=minimal'}});if(!r.ok)return j({error:text(r.data?.message||'Delivery queue could not be prepared.'),migrationRequired:missing(r)},r.status===503?503:500)}await audit(env,a.actor,'admin.notification.queue',id,'',{recipients:resolved.items.length,deliveries:rows.length,limitedTo500:resolved.limited,channels});return j({ok:true,recipients:resolved.items.length,deliveryRows:rows.length,limitedTo500:resolved.limited,delivered:false,note:'Delivery records are queued only. No email, push, or in-app delivery is claimed until a provider/delivery worker confirms it.'})}

async function settingsGet(request,env){const a=await requireRoles(request,env,SETTINGS_READ);if(a.error)return a.error;const [settings,social]=await Promise.all([list(env,'hc_site_settings','key,value,category,is_sensitive,updated_by,updated_at','category.asc,key.asc',200,'is_sensitive=eq.false'),list(env,'hc_social_connections','provider,status,external_account_id,external_account_name,capabilities,credential_location,last_tested_at,last_error_code,updated_at','provider.asc',20)]);const providers={facebook:{credentialConfigured:!!env.FACEBOOK_PAGE_ACCESS_TOKEN},tiktok:{credentialConfigured:!!env.TIKTOK_ACCESS_TOKEN},google_business:{credentialConfigured:!!env.GOOGLE_BUSINESS_ACCESS_TOKEN}};return j({settings:settings.ok?settings.data:[],social:social.ok?social.data:[],providerReadiness:providers,rule:'Secrets/tokens are never readable or writable through the admin browser. Configure them as Cloudflare secrets.'})}
async function settingsSave(request,env){const a=await requireRoles(request,env,SETTINGS_WRITE);if(a.error)return a.error;let b;try{b=await jsonBody(request)}catch(e){return j({error:e.message},e.status||400)}const key=text(b.key,120).toLowerCase();if(!/^[a-z0-9][a-z0-9_.-]{1,119}$/.test(key)||/secret|password|token|api.?key|private.?key/i.test(key))return j({error:'Use a non-sensitive settings key. Secrets belong in Cloudflare secrets.'},400);const row={key,value:cleanValue(b.value),category:text(b.category||'general',60),is_sensitive:false,updated_by:a.actor.id,updated_at:new Date().toISOString()};const r=await svc(env,'/rest/v1/hc_site_settings?on_conflict=key',{method:'POST',body:row,headers:{Prefer:'resolution=merge-duplicates,return=representation'}});if(!r.ok)return j({error:text(r.data?.message||'Setting could not be saved.'),migrationRequired:missing(r)},r.status===503?503:500);await audit(env,a.actor,'admin.setting.save',key);return j({ok:true,item:Array.isArray(r.data)?r.data[0]:r.data})}

async function pages(request,env){const a=await requireRoles(request,env,SETTINGS_READ);if(a.error)return a.error;if(request.method==='GET'){const r=await list(env,'hc_site_pages','id,slug,title,page_type,status,content,seo_title,seo_description,published_at,created_at,updated_at','updated_at.desc',120);if(!r.ok)return j({error:text(r.data?.message||'Pages could not be loaded.'),migrationRequired:missing(r)},r.status===503?503:500);return j({items:r.data||[]})}const w=await requireRoles(request,env,PAGES_WRITE);if(w.error)return w.error;let b;try{b=await jsonBody(request)}catch(e){return j({error:e.message},e.status||400)}const id=text(b.id,80),title=text(b.title,220),slug=slugify(b.slug||title),pageType=text(b.pageType||'content',30),status=text(b.status||'draft',20);if(id&&!uuid(id))return j({error:'Invalid page ID.'},400);if(!title||!slug||!['home','content','legal','help','landing'].includes(pageType)||!['draft','published','archived'].includes(status))return j({error:'Provide a valid title, slug, page type and status.'},400);if(pageType==='legal'&&status==='published'&&text(b.publishConfirmation,40)!=='PUBLISH LEGAL')return j({error:'Legal pages require explicit typed confirmation before publication.',confirmation:'PUBLISH LEGAL'},409);const duplicate=await one(env,'hc_site_pages','id','slug=eq.'+encodeURIComponent(slug));if(duplicate.row&&duplicate.row.id!==id)return j({error:'That page slug is already in use.'},409);const row={title,slug,page_type:pageType,status,content:cleanValue(b.content&&typeof b.content==='object'?b.content:{}),seo_title:text(b.seoTitle,220)||null,seo_description:text(b.seoDescription,500)||null,published_at:status==='published'?new Date().toISOString():null,updated_by:w.actor.id,updated_at:new Date().toISOString()};let r;if(id){const current=await one(env,'hc_site_pages','*','id=eq.'+encodeURIComponent(id));if(!current.row)return j({error:'Page not found.'},404);const rev=await list(env,'hc_site_page_revisions','revision_number','revision_number.desc',1,'page_id=eq.'+encodeURIComponent(id)),next=(Number(rev.data?.[0]?.revision_number)||0)+1;await svc(env,'/rest/v1/hc_site_page_revisions',{method:'POST',body:{page_id:id,revision_number:next,snapshot:current.row,editor_user_id:w.actor.id},headers:{Prefer:'return=minimal'}});r=await svc(env,'/rest/v1/hc_site_pages?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:row,headers:{Prefer:'return=representation'}})}else r=await svc(env,'/rest/v1/hc_site_pages',{method:'POST',body:{...row,created_by:w.actor.id,created_at:new Date().toISOString()},headers:{Prefer:'return=representation'}});if(!r.ok)return j({error:text(r.data?.message||'Page could not be saved.'),migrationRequired:missing(r)},r.status===503?503:500);const item=Array.isArray(r.data)?r.data[0]:r.data;await audit(env,w.actor,id?'admin.page.update':'admin.page.create',item?.id||slug,'',{slug,pageType,status});return j({ok:true,item,revisionCaptured:!!id})}
async function pageRevisions(request,env,pageId){const a=await requireRoles(request,env,SETTINGS_READ);if(a.error)return a.error;if(!uuid(pageId))return j({error:'Invalid page ID.'},400);const page=await one(env,'hc_site_pages','id,title,slug','id=eq.'+encodeURIComponent(pageId));if(!page.row)return j({error:'Page not found.'},404);const r=await list(env,'hc_site_page_revisions','id,revision_number,editor_user_id,created_at','revision_number.desc',30,'page_id=eq.'+encodeURIComponent(pageId));if(!r.ok)return j({error:text(r.data?.message||'Page revisions could not be loaded.'),migrationRequired:missing(r)},r.status===503?503:500);return j({page:page.row,items:r.data||[],note:'Revision snapshots are server-only and are captured before each saved edit.'})}

async function socialPlan(request,env,postId){const a=await requireRoles(request,env,PAGES_WRITE);if(a.error)return a.error;if(!uuid(postId))return j({error:'Invalid CMS post ID.'},400);const post=await one(env,'hc_cms_posts','id,title,slug,status,publish_channels,channel_results','id=eq.'+encodeURIComponent(postId));if(!post.ok||!post.row)return j({error:'CMS post not found.'},404);const channels=post.row.publish_channels||{},availability={website:true,facebook:!!env.FACEBOOK_PAGE_ACCESS_TOKEN,tiktok:!!env.TIKTOK_ACCESS_TOKEN,google_business:!!env.GOOGLE_BUSINESS_ACCESS_TOKEN};await audit(env,a.actor,'admin.cms.publish_plan',postId,'',{requested:channels,availability});return j({post:post.row,availability,willPublishNow:false,note:'This route only verifies channel readiness. Phase 3 does not publish to external platforms without dedicated provider adapters and confirmed API permissions.'})}

export async function handleAdmin(request,env){const u=new URL(request.url),p=u.pathname;if(p==='/admin'||p==='/admin/')return page(adminHtml(VERSION));if(!p.startsWith('/api/admin/'))return null;if(!sameOrigin(request))return j({error:'Cross-site admin request blocked.'},403);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{allow:'GET, POST, HEAD, OPTIONS'}});
  if(p==='/api/admin/phase3/status'&&request.method==='GET')return phase3Status(request,env);
  if(p==='/api/admin/analytics'&&request.method==='GET')return analytics(request,env);
  if(p==='/api/admin/staff'&&request.method==='GET')return staffList(request,env);
  if(p==='/api/admin/staff'&&request.method==='POST')return staffSave(request,env);
  let m=p.match(/^\/api\/admin\/markets\/([^/]+)$/);if(m&&request.method==='POST')return marketSave(request,env,m[1]);
  if(p==='/api/admin/notifications/campaigns'&&request.method==='GET')return campaignList(request,env);
  if(p==='/api/admin/notifications/campaigns'&&request.method==='POST')return campaignSave(request,env);
  m=p.match(/^\/api\/admin\/notifications\/campaigns\/([^/]+)\/action$/);if(m&&request.method==='POST')return campaignAction(request,env,m[1]);
  if(p==='/api/admin/settings'&&request.method==='GET')return settingsGet(request,env);
  if(p==='/api/admin/settings'&&request.method==='POST')return settingsSave(request,env);
  if(p==='/api/admin/pages'&&(request.method==='GET'||request.method==='POST'))return pages(request,env);m=p.match(/^\/api\/admin\/pages\/([^/]+)\/revisions$/);if(m&&request.method==='GET')return pageRevisions(request,env,m[1]);
  m=p.match(/^\/api\/admin\/cms\/posts\/([^/]+)\/publish-plan$/);if(m&&request.method==='GET')return socialPlan(request,env,m[1]);
  return handleAdminV2(request,env)
}
