import {adminHtml as adminHtmlV5} from './admin-ui-v5.js';

export function adminHtml(version){
  const extra=`<script>
(()=>{
  const view6=document.getElementById('view'),nav6=document.getElementById('nav'),title6=document.getElementById('title'),notice6=document.getElementById('notice');
  function esc6(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function note6(m){if(notice6)notice6.innerHTML=m?'<div class="notice">'+esc6(m)+'</div>':''}
  async function req6(url,opt={}){const r=await fetch(url,{credentials:'same-origin',...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.error||'Request failed.'),{data:d,status:r.status});return d}
  function post6(url,b){return req6(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)})}
  function pill6(v){return '<span class="status '+esc6(v)+'">'+esc6(v||'—')+'</span>'}
  function card6(label,value,target,note=''){return '<button class="card" data-v6-open="'+esc6(target)+'"><span>'+esc6(label)+'</span><strong>'+esc6(value??'—')+'</strong><small class="muted">'+esc6(note||('Open '+target))+'</small></button>'}
  function ensureNav6(){if(!nav6||nav6.querySelector('[data-v6-command-nav]'))return;const b=document.createElement('button');b.type='button';b.dataset.v6CommandNav='1';b.textContent='Command Center';b.onclick=loadCommand6;nav6.insertBefore(b,nav6.firstChild)}
  function mark6(){document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));const b=nav6?.querySelector('[data-v6-command-nav]');if(b)b.classList.add('active')}
  function wireOpen6(){view6.querySelectorAll('[data-v6-open]').forEach(b=>b.onclick=()=>{const t=b.dataset.v6Open;if(typeof load==='function')load(t)})}
  function healthRow6(x){return '<div class="row"><div><b>'+esc6(x.label)+'</b><small>'+esc6(x.key)+'</small></div><div>'+pill6(x.status)+'</div><div>'+esc6(x.detail||'')+'</div><div>'+esc6(x.target||'')+'</div><button class="btn" data-v6-open="'+esc6(x.target||'overview')+'">Open</button></div>'}
  async function incidentAction6(id,severity,action){let note='';let confirmation='';if(action==='resolve'){note=prompt('Resolution note:')||'';if(note.trim().length<3)return;if(severity==='critical'){confirmation=prompt('Type RESOLVE to close this critical incident:')||'';if(confirmation!=='RESOLVE')return}}try{await post6('/api/admin/incidents/'+encodeURIComponent(id)+'/action',{action,note,confirmation});note6('Incident updated.');await loadCommand6()}catch(e){note6(e.message)}}
  async function createIncident6(){const title=(document.getElementById('v6IncidentTitle')?.value||'').trim(),summary=(document.getElementById('v6IncidentSummary')?.value||'').trim(),category=document.getElementById('v6IncidentCategory')?.value||'operations',severity=document.getElementById('v6IncidentSeverity')?.value||'medium';if(!title){note6('Enter an incident title.');return}try{await post6('/api/admin/incidents',{title,summary,category,severity});note6('Incident created.');await loadCommand6()}catch(e){note6(e.message)}}
  async function updateReadiness6(key,required,automatic){if(automatic){note6('This readiness item is calculated automatically from current configuration/health.');return}const status=(prompt('Set status: pending, passed, blocked'+(required?'':' or waived'),'passed')||'').trim();if(!['pending','passed','blocked','waived'].includes(status))return;const evidence=status==='passed'?(prompt('Evidence for passing this check:')||''):'';if(status==='passed'&&evidence.trim().length<3)return;const note=prompt('Optional note:')||'';try{await post6('/api/admin/readiness/'+encodeURIComponent(key),{status,evidence,note});note6('Readiness check updated.');await loadCommand6()}catch(e){note6(e.message)}}
  async function snapshot6(){if((prompt('Type RUN to capture a fresh health snapshot:')||'')!=='RUN')return;try{const d=await post6('/api/admin/health/snapshot',{confirmation:'RUN'});note6('Health snapshot captured: '+(d.health?.overallStatus||'complete')+'.');await loadCommand6()}catch(e){note6(e.message)}}
  async function loadCommand6(){mark6();if(title6)title6.textContent='Admin Command Center';if(view6)view6.innerHTML='<div class="empty">Loading operational command center…</div>';try{const [d,inc,hist]=await Promise.all([req6('/api/admin/phase6/status'),req6('/api/admin/incidents').catch(()=>({items:[]})),req6('/api/admin/health/history').catch(()=>({items:[]}))]);const health=d.health||{},m=health.metrics||{},readiness=d.readiness||{},checks=health.checks||[],incidents=inc.items||[];
      const cards=[card6('Profiles',m.profiles,'users','Open User Management'),card6('Open reports',m.openReports,'moderation','Open Moderation'),card6('Critical reports',m.criticalReports,'moderation','Human review required'),card6('Pending verification',m.pendingVerification,'verification','Open Verification'),card6('Queued in-app',m.queuedInApp,'notifications','Notification Operations'),card6('Failed in-app',m.failedInApp,'notifications','Review delivery failures'),card6('Due campaigns',m.dueCampaigns,'notifications','Campaign queue'),card6('Open incidents',m.openIncidents,'overview','Command Center incidents')].join('');
      const checkRows=checks.map(healthRow6).join('');
      const incidentRows=incidents.map(x=>'<div class="row"><div><b>'+esc6(x.title)+'</b><small>'+esc6(x.category)+' · '+esc6(x.source)+'</small></div><div>'+pill6(x.severity)+'</div><div>'+pill6(x.status)+'</div><div>'+esc6(x.last_seen_at||x.detected_at||'')+'</div><div class="actions">'+(x.status==='open'?'<button class="btn" data-v6-inc="'+esc6(x.id)+'" data-v6-sev="'+esc6(x.severity)+'" data-v6-act="acknowledge">Acknowledge</button>':'')+(x.status!=='resolved'?'<button class="btn primary" data-v6-inc="'+esc6(x.id)+'" data-v6-sev="'+esc6(x.severity)+'" data-v6-act="resolve">Resolve</button>':'<button class="btn" data-v6-inc="'+esc6(x.id)+'" data-v6-sev="'+esc6(x.severity)+'" data-v6-act="reopen">Reopen</button>')+'</div></div>').join('');
      const readyRows=(readiness.items||[]).map(x=>'<div class="row"><div><b>'+esc6(x.label)+'</b><small>'+esc6(x.category)+' · '+(x.required?'required':'optional')+(x.automatic?' · automatic':'')+'</small></div><div>'+pill6(x.effective_status||x.status)+'</div><div>'+esc6(x.evidence||x.description||'')+'</div><div>'+esc6(x.checked_at||'')+'</div><button class="btn" data-v6-ready="'+esc6(x.key)+'" data-v6-required="'+(x.required?'1':'0')+'" data-v6-auto="'+(x.automatic?'1':'0')+'">Update</button></div>').join('');
      const history=(hist.items||[]).slice(0,12).map(x=>'<div class="row"><div><b>'+esc6(x.overall_status)+'</b><small>'+esc6(x.source)+'</small></div><div>'+pill6(x.overall_status)+'</div><div>'+esc6((x.checks||[]).length+' checks')+'</div><div>'+esc6(x.captured_at||'')+'</div><button class="btn" data-v6-health="'+encodeURIComponent(JSON.stringify(x))+'">View</button></div>').join('');
      view6.innerHTML='<section class="panel"><div class="panel-head"><div><h2>Operational Command Center</h2><p class="muted">Live admin health, incidents, readiness gates and launch evidence. No user bans, verification decisions, payment actions or deletion happen automatically here.</p></div>'+pill6(health.overallStatus||'setup_required')+'</div><div class="grid">'+cards+'</div>'+(health.migrationRequired?'<div class="notice">Phase 6 database migration is not applied yet. Keep this branch isolated until security reconciliation is complete.</div>':'')+'</section><section class="panel"><div class="panel-head"><h2>Health checks</h2><button class="btn" id="v6Snapshot">Capture snapshot</button></div><div class="table">'+(checkRows||'<div class="empty">No health checks available.</div>')+'</div></section><section class="panel"><div class="panel-head"><div><h2>Launch readiness</h2><p class="muted">'+esc6((readiness.requiredPassed??0)+' of '+(readiness.requiredTotal??0)+' required gates passed')+'</p></div>'+pill6(readiness.launchReady?'ready':'not_ready')+'</div><div class="table">'+(readyRows||'<div class="empty">Phase 6 readiness migration is required.</div>')+'</div><p class="note">Required launch checks cannot be waived. Automatic checks reflect current configuration and queue health; manual gates require owner/super-admin evidence.</p></section><section class="panel"><div class="panel-head"><h2>Incidents</h2><span class="muted">Human-owned operational response</span></div><div class="table">'+(incidentRows||'<div class="empty">No incidents recorded.</div>')+'</div><div class="form-grid" style="margin-top:14px"><label class="field"><span>Title</span><input id="v6IncidentTitle" placeholder="Short incident title"></label><label class="field"><span>Category</span><select id="v6IncidentCategory"><option>operations</option><option>system</option><option>security</option><option>payments</option><option>moderation</option><option>verification</option><option>notifications</option><option>cms</option><option>integration</option></select></label><label class="field"><span>Severity</span><select id="v6IncidentSeverity"><option>low</option><option selected>medium</option><option>high</option><option>critical</option></select></label><label class="field wide"><span>Summary</span><textarea id="v6IncidentSummary" placeholder="What happened, impact, and what staff should review"></textarea></label></div><button class="btn primary" id="v6CreateIncident">Create incident</button></section><section class="panel"><div class="panel-head"><h2>Health history</h2><span class="muted">Privacy-minimized operational snapshots</span></div><div class="table">'+(history||'<div class="empty">No health snapshots recorded yet.</div>')+'</div></section>';
      wireOpen6();
      document.getElementById('v6Snapshot').onclick=snapshot6;
      document.getElementById('v6CreateIncident').onclick=createIncident6;
      view6.querySelectorAll('[data-v6-inc]').forEach(b=>b.onclick=()=>incidentAction6(b.dataset.v6Inc,b.dataset.v6Sev,b.dataset.v6Act));
      view6.querySelectorAll('[data-v6-ready]').forEach(b=>b.onclick=()=>updateReadiness6(b.dataset.v6Ready,b.dataset.v6Required==='1',b.dataset.v6Auto==='1'));
      view6.querySelectorAll('[data-v6-health]').forEach(b=>b.onclick=()=>{try{const x=JSON.parse(decodeURIComponent(b.dataset.v6Health));if(typeof open==='function')open('Health snapshot','<pre class="json">'+esc6(JSON.stringify(x,null,2))+'</pre>')}catch{}});
    }catch(e){view6.innerHTML='<div class="empty"><b>Phase 6 unavailable</b><p>'+esc6(e.message)+'</p></div>';if(e.data?.health)note6('Phase 6 setup is incomplete.')}}
  ensureNav6();setTimeout(ensureNav6,0);const obs6=new MutationObserver(ensureNav6);if(nav6)obs6.observe(nav6,{childList:true,subtree:true});
})();
</script>`;
  return adminHtmlV5(version).replaceAll('PHASE 5','PHASE 6').replace('</body>',extra+'</body>');
}
