import {adminHtml as adminHtmlV3} from './admin-ui-v3.js';

export function adminHtml(version){
  const extra=`<script>
(()=>{
  const viewEl=document.getElementById('view'),navEl=document.getElementById('nav'),titleEl=document.getElementById('title'),noticeEl=document.getElementById('notice');
  function esc4(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function note4(m){noticeEl.innerHTML=m?'<div class="notice">'+esc4(m)+'</div>':''}
  async function request4(url,opt={}){const r=await fetch(url,{credentials:'same-origin',...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.error||'Request failed.'),{data:d,status:r.status});return d}
  async function lifecycle4(type,id,action,reason='',confirmation=''){return request4('/api/admin/lifecycle/'+encodeURIComponent(type)+'/'+encodeURIComponent(id),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,reason,confirmation})})}
  function ensureTrashNav(){if(!navEl||navEl.querySelector('[data-v4-trash-nav]'))return;const b=document.createElement('button');b.type='button';b.dataset.v4TrashNav='1';b.textContent='Trash & Restore';b.onclick=loadTrash4;navEl.appendChild(b)}
  function addTrashButton(anchor,type,id){if(!id||anchor.parentElement?.querySelector('[data-v4-trash="'+CSS.escape(String(id))+'"]'))return;const b=document.createElement('button');b.type='button';b.className='btn danger';b.textContent='Trash';b.dataset.v4Trash=String(id);b.dataset.v4Type=type;b.style.marginLeft='5px';b.onclick=async e=>{e.preventDefault();e.stopPropagation();const reason=prompt('Reason for moving this item to trash:')||'';if(reason.trim().length<3)return;try{await lifecycle4(type,id,'trash',reason);note4('Moved to trash. It can be restored from Trash & Restore.');if(typeof load==='function')load(current)}catch(err){note4(err.message)}};anchor.insertAdjacentElement('afterend',b)}
  function enhance4(){ensureTrashNav();document.querySelectorAll('[data-cms]').forEach(b=>addTrashButton(b,'cms_post',b.dataset.cms));document.querySelectorAll('[data-page]').forEach(b=>addTrashButton(b,'page',b.dataset.page));document.querySelectorAll('[data-camp]').forEach(b=>addTrashButton(b,'notification_campaign',b.dataset.camp));document.querySelectorAll('[data-setting]').forEach(b=>{try{const x=JSON.parse(decodeURIComponent(b.dataset.setting));if(x?.key)addTrashButton(b,'setting',x.key)}catch{}})}
  async function loadTrash4(){try{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));const nb=navEl.querySelector('[data-v4-trash-nav]');if(nb)nb.classList.add('active');titleEl.textContent='Trash & Restore';viewEl.innerHTML='<div class="empty">Loading trash…</div>';const d=await request4('/api/admin/trash');const rows=(d.items||[]).map(x=>{const r=x.record||{},label=r.title||r.key||r.storage_path||x.entityId;return '<div class="row"><div><b>'+esc4(label)+'</b><small>'+esc4(x.entityType)+' · '+esc4(x.entityId)+'</small></div><div><span class="status">trashed</span></div><div>'+esc4(r.deleted_at||'')+'</div><div>'+esc4(r.delete_reason||'')+'</div><div class="actions"><button class="btn" data-v4-restore="'+esc4(x.entityId)+'" data-v4-type="'+esc4(x.entityType)+'">Restore</button><button class="btn danger" data-v4-purge="'+esc4(x.entityId)+'" data-v4-type="'+esc4(x.entityType)+'">Purge</button></div></div>'}).join('');viewEl.innerHTML='<section class="panel"><div class="panel-head"><h2>Trash & Restore</h2><span class="muted">7-day cooling period before eligible permanent purge</span></div><div class="table">'+(rows||'<div class="empty">Trash is empty.</div>')+'</div><p class="note">Payments, audit logs, moderation reports, verification records, user-action history, and notification delivery history are never permanently deleted here. Notification campaigns can be trashed/restored but not purged.</p></section><section class="panel"><h3>Move an eligible record to trash by ID</h3><div class="form-grid"><label class="field"><span>Type</span><select id="v4Type"><option value="cms_post">CMS post</option><option value="cms_media">CMS media</option><option value="page">Page</option><option value="setting">Setting</option><option value="notification_campaign">Notification campaign</option></select></label><label class="field"><span>ID / setting key</span><input id="v4Id" placeholder="UUID or setting key"></label><label class="field wide"><span>Reason</span><input id="v4Reason" placeholder="Why is this being removed?"></label></div><button class="btn danger" id="v4TrashNow">Move to trash</button></section>';
    viewEl.querySelectorAll('[data-v4-restore]').forEach(b=>b.onclick=async()=>{try{await lifecycle4(b.dataset.v4Type,b.dataset.v4Restore,'restore','Restored from admin trash');note4('Record restored.');loadTrash4()}catch(e){note4(e.message)}});
    viewEl.querySelectorAll('[data-v4-purge]').forEach(b=>b.onclick=async()=>{if((prompt('Permanent deletion cannot be undone. Type PURGE to continue:')||'')!=='PURGE')return;const reason=prompt('Reason for permanent purge:')||'';try{await lifecycle4(b.dataset.v4Type,b.dataset.v4Purge,'purge',reason,'PURGE');note4('Eligible content permanently purged. Audit/trash events remain.');loadTrash4()}catch(e){note4(e.message)}});
    document.getElementById('v4TrashNow').onclick=async()=>{const type=document.getElementById('v4Type').value,id=document.getElementById('v4Id').value,reason=document.getElementById('v4Reason').value;if(!id||reason.trim().length<3){note4('Enter an ID and a reason.');return}try{await lifecycle4(type,id,'trash',reason);note4('Record moved to trash.');loadTrash4()}catch(e){note4(e.message)}};
  }catch(e){viewEl.innerHTML='<div class="empty">'+esc4(e.message)+'</div>'}}
  const observer=new MutationObserver(()=>enhance4());if(viewEl)observer.observe(viewEl,{childList:true,subtree:true});if(navEl)observer.observe(navEl,{childList:true});setTimeout(enhance4,0);
})();
</script>`;
  return adminHtmlV3(version).replaceAll('PHASE 3','PHASE 4').replace('</body>',extra+'</body>');
}
