import {handleAdmin as handleAdminV16,runPhase7AndEarlierScheduled} from './admin-api-v16.js';
import {adminHtml} from './admin-ui-v17.js';

export {runPhase7AndEarlierScheduled};
export const VERSION='hc-admin-control-plane-v17';

const DEFAULT_SUPABASE_URL='https://zzhzkikezjtbntaqiurk.supabase.co';

function cfg(env){return{url:String(env.SUPABASE_URL||DEFAULT_SUPABASE_URL).replace(/\/+$/,''),service:String(env.SUPABASE_SERVICE_ROLE_KEY||'')}}
function text(v,n=1000){return String(v??'').trim().slice(0,n)}
function uuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''))}
function listText(v,maxItems=30,maxChars=120){const values=Array.isArray(v)?v:String(v||'').split(',');return [...new Set(values.map(x=>text(x,maxChars)).filter(Boolean))].slice(0,maxItems)}
function j(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer','x-heart-connect-admin':VERSION}})}
function page(html,head=false){const headers={'content-type':'text/html; charset=utf-8','cache-control':'no-store, max-age=0','pragma':'no-cache','x-content-type-options':'nosniff','referrer-policy':'no-referrer','x-frame-options':'DENY','permissions-policy':'camera=(), microphone=(), geolocation=(), payment=(), usb=(), serial=()','cross-origin-opener-policy':'same-origin','cross-origin-resource-policy':'same-origin','strict-transport-security':'max-age=31536000; includeSubDomains','content-security-policy':"default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src 'self' data: https:; media-src 'self' blob: https:; connect-src 'self'; frame-src 'self' data: blob:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; object-src 'none'",'x-heart-connect-admin':VERSION};return new Response(head?null:html,{status:200,headers})}
function sameOrigin(request){const site=request.headers.get('sec-fetch-site');if(site==='cross-site')return false;const origin=request.headers.get('origin');if(!origin)return true;try{return new URL(origin).origin===new URL(request.url).origin}catch{return false}}
async function jsonBody(request,max=100000){const raw=await request.text();if(raw.length>max)throw Object.assign(new Error('Request is too large.'),{status:413});try{return raw?JSON.parse(raw):{}}catch{throw Object.assign(new Error('Valid JSON is required.'),{status:400})}}
async function svc(env,path,{method='GET',body,headers:extra}={}){const c=cfg(env);if(!c.service)return{ok:false,status:503,data:{message:'Admin data service is not configured.'},headers:new Headers()};const headers=new Headers({apikey:c.service,authorization:'Bearer '+c.service,accept:'application/json',...(extra||{})});if(body!==undefined)headers.set('content-type','application/json');try{const r=await fetch(c.url+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),raw=await r.text();let data=null;try{data=raw?JSON.parse(raw):null}catch{data=raw}return{ok:r.ok,status:r.status,data,headers:r.headers}}catch{return{ok:false,status:503,data:{message:'Admin data service is temporarily unavailable.'},headers:new Headers()}}}
function hasPerm(actor,permission){const p=actor?.permissions||[],base=permission.split(':')[0];return p.includes('*')||p.includes(permission)||p.includes(base)||p.includes(base+':read')}
async function actorFor(request,env,permission){const u=new URL(request.url);u.pathname='/api/admin/capabilities';u.search='';const r=await handleAdminV16(new Request(u.toString(),{method:'GET',headers:request.headers}),env);if(!r)return{error:j({error:'Admin authentication could not be verified.'},401)};let d={};try{d=await r.clone().json()}catch{}if(!r.ok)return{error:j({error:d.error||'Admin authentication required.'},r.status)};const actor=d.actor||null;if(!actor||!hasPerm(actor,permission))return{error:j({error:'You do not have permission for this location-management action.'},403)};return{actor}}
async function audit(env,actor,action,target='',reason='',metadata={}){await svc(env,'/rest/v1/hc_admin_audit_log',{method:'POST',body:{actor_user_id:actor.userId||actor.id,actor_email:actor.email,actor_role:actor.role,action:text(action,120),target:text(target,240),reason:text(reason,1000)||null,metadata,created_at:new Date().toISOString()},headers:{Prefer:'return=minimal'}}).catch(()=>{})}
async function one(env,table,select,filter){const r=await svc(env,'/rest/v1/'+table+'?select='+encodeURIComponent(select)+'&'+filter+'&limit=1');return{...r,row:r.ok&&Array.isArray(r.data)?(r.data[0]||null):null}}

async function getLocation(request,env,userId){const a=await actorFor(request,env,'users:read');if(a.error)return a.error;if(!uuid(userId))return j({error:'Invalid user ID.'},400);const [profile,prefs]=await Promise.all([one(env,'dating_profiles','user_id,country,city,is_discoverable','user_id=eq.'+encodeURIComponent(userId)),one(env,'discovery_preferences','user_id,min_age,max_age,genders,countries,relationship_intentions,max_distance_km,global_mode,updated_at','user_id=eq.'+encodeURIComponent(userId))]);if(!profile.ok)return j({error:text(profile.data?.message||'Profile location could not be loaded.')},profile.status===503?503:500);if(!profile.row)return j({error:'Dating profile not found.'},404);const p=prefs.row||{};return j({userId,country:profile.row.country||'',city:profile.row.city||'',locationLabel:[profile.row.city,profile.row.country].filter(Boolean).join(', '),isDiscoverable:profile.row.is_discoverable===true,globalMode:prefs.row?p.global_mode!==false:true,countries:Array.isArray(p.countries)?p.countries:[],maxDistanceKm:p.max_distance_km??null,exactAddressStored:false,exactCoordinatesStored:false,note:'Admin location controls use the member’s city/country and discovery preferences. Heart Connect does not expose a home address or exact GPS coordinates from this Admin screen.'})}

async function saveLocation(request,env,userId){const a=await actorFor(request,env,'users:write');if(a.error)return a.error;if(!uuid(userId))return j({error:'Invalid user ID.'},400);let b;try{b=await jsonBody(request)}catch(e){return j({error:e.message},e.status||400)}const country=text(b.country,120),city=text(b.city,120),reason=text(b.reason,500);if(!country||!city)return j({error:'Country and city/town are required for profile location.'},400);if(reason.length<3)return j({error:'Add a short reason for the location change.'},400);const globalMode=b.globalMode!==false,countries=listText(b.countries);let maxDistanceKm=null;if(b.maxDistanceKm!==null&&b.maxDistanceKm!==undefined&&String(b.maxDistanceKm).trim()!==''){maxDistanceKm=Number(b.maxDistanceKm);if(!Number.isInteger(maxDistanceKm)||maxDistanceKm<1||maxDistanceKm>20000)return j({error:'Preferred distance must be between 1 and 20,000 km, or left blank.'},400)}const current=await one(env,'dating_profiles','user_id','user_id=eq.'+encodeURIComponent(userId));if(!current.ok)return j({error:text(current.data?.message||'Profile could not be checked.')},current.status===503?503:500);if(!current.row)return j({error:'Dating profile not found.'},404);const profile=await svc(env,'/rest/v1/dating_profiles?user_id=eq.'+encodeURIComponent(userId),{method:'PATCH',body:{country,city,updated_at:new Date().toISOString()},headers:{Prefer:'return=representation'}});if(!profile.ok)return j({error:text(profile.data?.message||'Profile location could not be saved.')},profile.status===503?503:500);const existing=await one(env,'discovery_preferences','user_id,min_age,max_age,genders,countries,relationship_intentions,max_distance_km,global_mode','user_id=eq.'+encodeURIComponent(userId));let pref;if(existing.row){pref=await svc(env,'/rest/v1/discovery_preferences?user_id=eq.'+encodeURIComponent(userId),{method:'PATCH',body:{countries,global_mode:globalMode,max_distance_km:maxDistanceKm,updated_at:new Date().toISOString()},headers:{Prefer:'return=representation'}})}else{pref=await svc(env,'/rest/v1/discovery_preferences',{method:'POST',body:{user_id:userId,min_age:18,max_age:99,genders:[],countries,relationship_intentions:[],max_distance_km:maxDistanceKm,global_mode:globalMode,updated_at:new Date().toISOString()},headers:{Prefer:'return=representation'}})}if(!pref.ok)return j({error:text(pref.data?.message||'Discovery location preferences could not be saved.')},pref.status===503?503:500);await audit(env,a.actor,'admin.user.location_update',userId,reason,{country,city,globalMode,preferredCountries:countries,maxDistanceKm,exactCoordinatesStored:false});return j({ok:true,country,city,locationLabel:city+', '+country,globalMode,countries,maxDistanceKm,note:'Location and discovery preferences saved. Exact address/GPS is not stored by this Admin control.'})}

export async function handleAdmin(request,env){const u=new URL(request.url),p=u.pathname;if((p==='/admin'||p==='/admin/')&&(request.method==='GET'||request.method==='HEAD'))return page(adminHtml(VERSION),request.method==='HEAD');if(!sameOrigin(request))return j({error:'Cross-site admin request blocked.'},403);const m=p.match(/^\/api\/admin\/users\/([^/]+)\/location$/);if(m&&request.method==='GET')return getLocation(request,env,m[1]);if(m&&request.method==='POST')return saveLocation(request,env,m[1]);return handleAdminV16(request,env)}
