import {handleAdmin as handleAdminV5,runPhase5Scheduled} from './admin-api-v5.js';
import {adminHtml} from './admin-ui-v6.js';

export const VERSION='hc-admin-control-plane-v6';
const ACCESS_COOKIE='__Host-hc_cf_access';
const DEFAULT_SUPABASE_URL='https://zzhzkikezjtbntaqiurk.supabase.co';
const DEFAULT_PUBLISHABLE_KEY='sb_publishable_HB0Irz6bxug1hHs518oPZQ_LC83i4qT';
const ALL_ADMIN_ROLES=['owner','super_admin','admin','moderator','senior_moderator','safety_specialist','payment_specialist','support_agent','content_manager','verification_specialist','finance'];
const INCIDENT_WRITE_ROLES=['owner','super_admin','admin','senior_moderator','safety_specialist','payment_specialist'];
const READINESS_WRITE_ROLES=['owner','super_admin'];
const HEALTH_RUN_ROLES=['owner','super_admin','admin'];
const INCIDENT_CATEGORIES=['system','security','payments','moderation','verification','notifications','cms','integration','operations'];
const INCIDENT_SEVERITIES=['low','medium','high','critical'];
const READINESS_STATUSES=['pending','passed','blocked','waived'];

function cfg(env){return{url:String(env.SUPABASE_URL||DEFAULT_SUPABASE_URL).replace(/\/+$/,''),publishable:String(env.SUPABASE_PUBLISHABLE_KEY||DEFAULT_PUBLISHABLE_KEY),service:String(env.SUPABASE_SERVICE_ROLE_KEY||'')}}
function cookies(request){const out={};for(const part of String(request.headers.get('cookie')||'').split(';')){const i=part.indexOf('=');if(i>0){const k=part.slice(0,i).trim();try{out[k]=decodeURIComponent(part.slice(i+1).trim())}catch{out[k]=part.slice(i+1).trim()}}}return out}
function j(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-heart-connect-admin':VERSION}})}
function page(html,status=200){return new Response(html,{status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'same-origin','x-frame-options':'DENY','content-security-policy':"default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'",'x-heart-connect-admin':VERSION}})}
function unsafe(request){return !['GET','HEAD','OPTIONS'].includes(request.method)}
function sameOrigin(request){if(!unsafe(request))return true;const site=request.headers.get('sec-fetch-site');if(site==='cross-site')return false;const origin=request.headers.get('origin');if(!origin)return true;try{return new URL(origin).origin===new URL(request.url).origin}catch{return false}}
function text(v,n=1000){return String(v??'').trim().slice(0,n)}
function email(v){const s=text(v,320).toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)?s:''}
function emails(v){return String(v||'').split(',').map(email).filter(Boolean)}
function uuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''))}
function clean(v){if(Array.isArray(v))return v.slice(0,100).map(clean);if(v&&typeof v==='object'){const out={};for(const [k,x] of Object.entries(v)){if(/secret|password|token|authorization|api.?key|private.?key|credential/i.test(k))continue;out[text(k,100)]=clean(x)}return out}if(typeof v==='string')return v.slice(0,12000);if(typeof v==='number'||typeof v==='boolean'||v===null)return v;return String(v??'').slice(0,12000)}
function missing(r){return r?.status===404||/does not exist|relation .* does not exist|PGRST205/i.test(String(r?.data?.message||r?.data?.error||r?.data||''))}
async function jsonBody(request,max=50000){const raw=await request.text();if(raw.length>max)throw Object.assign(new Error('Request is too large.'),{status:413});try{return raw?JSON.parse(raw):{}}catch{throw Object.assign(new Error('Valid JSON is required.'),{status:400})}}
async function session(request,env){const c=cfg(env),token=cookies(request)[ACCESS_COOKIE]||'';if(!token)return null;try{const r=await fetch(c.url+'/auth/v1/user',{headers:{apikey:c.publishable,authorization:'Bearer '+token,accept:'application/json'}});if(!r.ok)return null;const u=await r.json();return u?.id?{id:u.id,email:email(u.email)}:null}catch{return null}}
async function svc(env,path,{method='GET',body,headers:extra}={}){const c=cfg(env);if(!c.service)return{ok:false,status:503,data:{message:'Admin data service is not configured.'},headers:new Headers()};const headers=new Headers({apikey:c.service,authorization:'Bearer '+c.service,accept:'application/json',...(extra||{})});if(body!==undefined)headers.set('content-type','application/json');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(c.url+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body),signal:controller.signal});const raw=await r.text();let data=null;try{data=raw?JSON.parse(raw):null}catch{data=raw}return{ok:r.ok,status:r.status,data,headers:r.headers}}catch(e){return{ok:false,status:503,data:{message:e?.name==='AbortError'?'Supabase admin request timed out.':'Supabase admin service is temporarily unavailable.'},headers:new Headers()}}finally{clearTimeout(timer)}}
async function actor(request,env){const u=await session(request,env);if(!u)return null;const owners=[...emails(env.HEART_CONNECT_OWNER_EMAILS),...emails(env.HEART_CONNECT_ADMIN_EMAILS)];if(owners.includes(u.email))return{...u,role:'owner',displayName:'Platform Owner'};const r=await svc(env,'/rest/v1/hc_admin_staff?select=role,status,display_name&user_id=eq.'+encodeURIComponent(u.id)+'&status=eq.active&limit=1'),row=r.ok&&Array.isArray(r.data)?r.data[0]:null;return row?{...u,role:String(row.role||''),displayName:text(row.display_name,100)||u.email}:null}
async function requireRoles(request,env,roles){const a=await actor(request,env);if(!a)return{error:j({error:'Admin access denied.'},403)};if(!roles.includes(a.role))return{error:j({error:'Your admin role does not allow this Phase 6 action.',role:a.role},403),actor:a};return{actor:a}}
async function audit(env,a,action,target='',reason='',metadata={}){if(!a)return;await svc(env,'/rest/v1/hc_admin_audit_log',{method:'POST',body:{actor_user_id:a.id,actor_email:a.email,actor_role:a.role,action:text(action,120),target:text(target,240),reason:text(reason,1000)||null,metadata:clean(metadata),created_at:new Date().toISOString()},headers:{Prefer:'return=minimal'}}).catch(()=>{})}
async function count(env,table,column='id',filter=''){const r=await svc(env,'/rest/v1/'+table+'?select='+encodeURIComponent(column)+'&limit=1'+(filter?'&'+filter:''),{headers:{Prefer:'count=exact',Range:'0-0'}});if(!r.ok)return{ok:false,value:null,missing:missing(r),response:r};const cr=String(r.headers.get('content-range')||''),n=Number(cr.split('/')[1]);return{ok:true,value:Number.isFinite(n)?n:(Array.isArray(r.data)?r.data.length:0),missing:false,response:r}}
async function latest(env,table,select,order='created_at.desc',filter=''){const r=await svc(env,'/rest/v1/'+table+'?select='+encodeURIComponent(select)+(filter?'&'+filter:'')+'&order='+encodeURIComponent(order)+'&limit=1');return{ok:r.ok,row:r.ok&&Array.isArray(r.data)?(r.data[0]||null):null,missing:missing(r),response:r}}
function check(key,label,status,detail,target){return{key,label,status,detail,target}}

async function healthData(env){
  const configured=!!cfg(env).service;
  if(!configured)return{overallStatus:'setup_required',checks:[check('service_role','Admin data service','setup','SUPABASE_SERVICE_ROLE_KEY is not configured.','settings')],metrics:{},migrationRequired:true,serviceRoleConfigured:false};
  const now=new Date().toISOString();
  const [profiles,openReports,criticalReports,pendingVerification,queuedInApp,failedInApp,dueCampaigns,openIncidents,lastAutomation,phase6Probe]=await Promise.all([
    count(env,'dating_profiles','user_id'),
    count(env,'reports','id','status=in.(new,reviewing)'),
    count(env,'reports','id','priority=eq.critical&status=in.(new,reviewing)'),
    count(env,'verification_requests','id','status=eq.pending'),
    count(env,'hc_notification_delivery_queue','id','channel=eq.in_app&status=eq.queued'),
    count(env,'hc_notification_delivery_queue','id','channel=eq.in_app&status=eq.failed'),
    count(env,'hc_notification_campaigns','id','status=eq.scheduled&scheduled_for=lte.'+encodeURIComponent(now)+'&deleted_at=is.null'),
    count(env,'hc_admin_incidents','id','status=in.(open,acknowledged)'),
    latest(env,'hc_admin_automation_runs','automation_key,status,started_at,finished_at','started_at.desc'),
    count(env,'hc_admin_readiness_checks','key')
  ]);
  const phase6Ready=phase6Probe.ok&&!phase6Probe.missing;
  const checks=[];
  checks.push(check('service_role','Admin data service','pass','Server-side admin access is configured.','settings'));
  checks.push(check('phase6_schema','Phase 6 database schema',phase6Ready?'pass':'setup',phase6Ready?'Command-center tables are available.':'Phase 6 migration is not applied yet.','settings'));
  if(criticalReports.ok){const n=criticalReports.value||0;checks.push(check('critical_moderation','Critical moderation queue',n>0?'critical':'pass',n?`${n} critical report(s) require human review.`:'No critical reports waiting.','moderation'))}
  else checks.push(check('critical_moderation','Critical moderation queue',criticalReports.missing?'setup':'warn','Moderation queue could not be measured.','moderation'));
  if(failedInApp.ok){const n=failedInApp.value||0;checks.push(check('notification_failures','In-app delivery failures',n>20?'critical':n>0?'warn':'pass',n?`${n} failed in-app delivery row(s).`:'No failed in-app deliveries.','notifications'))}
  else checks.push(check('notification_failures','In-app delivery failures',failedInApp.missing?'setup':'warn','Notification delivery queue could not be measured.','notifications'));
  if(openReports.ok){const n=openReports.value||0;checks.push(check('moderation_backlog','Open moderation backlog',n>50?'warn':'pass',`${n} open report(s).`,'moderation'))}
  if(pendingVerification.ok){const n=pendingVerification.value||0;checks.push(check('verification_backlog','Pending verification backlog',n>100?'warn':'pass',`${n} verification request(s) pending.`,'verification'))}
  if(dueCampaigns.ok){const n=dueCampaigns.value||0;checks.push(check('due_campaigns','Due notification campaigns',n>10?'warn':'pass',`${n} campaign(s) currently due.`,'notifications'))}
  if(lastAutomation.ok){const row=lastAutomation.row;if(!row)checks.push(check('automation_recency','Automation heartbeat','warn','No Phase 5 automation run has been recorded yet.','notifications'));else{const t=Date.parse(row.finished_at||row.started_at||'');const age=Number.isFinite(t)?Date.now()-t:Infinity;checks.push(check('automation_recency','Automation heartbeat',age>20*60*1000?'warn':'pass',Number.isFinite(age)?`Latest run is about ${Math.round(age/60000)} minute(s) old.`:'Latest automation time is invalid.','notifications'))}}
  else checks.push(check('automation_recency','Automation heartbeat',lastAutomation.missing?'setup':'warn','Automation run evidence is unavailable.','notifications'));
  const statuses=checks.map(x=>x.status);
  const overallStatus=statuses.includes('setup')?'setup_required':statuses.includes('critical')?'critical':statuses.includes('warn')?'degraded':'healthy';
  return{overallStatus,checks,metrics:{profiles:profiles.value,openReports:openReports.value,criticalReports:criticalReports.value,pendingVerification:pendingVerification.value,queuedInApp:queuedInApp.value,failedInApp:failedInApp.value,dueCampaigns:dueCampaigns.value,openIncidents:openIncidents.value,lastAutomation:lastAutomation.row||null},migrationRequired:!phase6Ready,serviceRoleConfigured:true};
}

async function readinessData(env,health){
  const r=await svc(env,'/rest/v1/hc_admin_readiness_checks?select=key,category,label,description,required,status,evidence,note,checked_by,checked_at,updated_at&order=category.asc,key.asc');
  if(!r.ok)return{items:[],migrationRequired:missing(r),launchReady:false};
  const ownerConfigured=[...emails(env.HEART_CONNECT_OWNER_EMAILS),...emails(env.HEART_CONNECT_ADMIN_EMAILS)].length>0;
  const overrides={
    admin_service_role:health.serviceRoleConfigured?'passed':'blocked',
    owner_allowlist:ownerConfigured?'passed':'blocked',
    workers_ai_binding:env.AI?'passed':'pending',
    operational_queues_healthy:health.overallStatus==='healthy'?'passed':health.overallStatus==='critical'?'blocked':'pending'
  };
  const items=(r.data||[]).map(x=>({...x,effective_status:overrides[x.key]||x.status,automatic:Object.prototype.hasOwnProperty.call(overrides,x.key)}));
  const required=items.filter(x=>x.required),launchReady=required.length>0&&required.every(x=>x.effective_status==='passed');
  return{items,launchReady,migrationRequired:false,requiredTotal:required.length,requiredPassed:required.filter(x=>x.effective_status==='passed').length};
}

async function phase6Status(request,env){const a=await requireRoles(request,env,ALL_ADMIN_ROLES);if(a.error)return a.error;const health=await healthData(env),readiness=health.serviceRoleConfigured?await readinessData(env,health):{items:[],launchReady:false,migrationRequired:true};return j({version:VERSION,actor:a.actor,phase6:{commandCenter:true,healthChecks:true,incidentManagement:true,readinessGates:true,healthSnapshots:true,automatedIncidentDetection:true},health,readiness,configuration:{serviceRoleConfigured:!!cfg(env).service,ownerAccessConfigured:[...emails(env.HEART_CONNECT_OWNER_EMAILS),...emails(env.HEART_CONNECT_ADMIN_EMAILS)].length>0,workersAiConfigured:!!env.AI,cronExpected:'*/5 * * * *'},safety:{noAutomaticBans:true,noAutomaticVerificationDecisions:true,noAutomaticPaymentActions:true,noAutomaticDeletion:true,noPrivateMessageBodiesInHealth:true,requiredLaunchChecksCannotBeWaived:true}})}

async function incidentList(request,env){const a=await requireRoles(request,env,ALL_ADMIN_ROLES);if(a.error)return a.error;const u=new URL(request.url),status=text(u.searchParams.get('status'),30),filter=status&&['open','acknowledged','resolved'].includes(status)?'status=eq.'+encodeURIComponent(status):'';const r=await svc(env,'/rest/v1/hc_admin_incidents?select=id,incident_key,category,severity,status,source,title,summary,metadata,detected_at,last_seen_at,acknowledged_at,resolution_note,resolved_at,updated_at'+(filter?'&'+filter:'')+'&order=last_seen_at.desc&limit=150');if(!r.ok)return j({error:text(r.data?.message||'Incidents could not be loaded.'),migrationRequired:missing(r)},r.status===503?503:500);return j({items:r.data||[]})}
async function incidentCreate(request,env){const a=await requireRoles(request,env,INCIDENT_WRITE_ROLES);if(a.error)return a.error;let b;try{b=await jsonBody(request)}catch(e){return j({error:e.message},e.status||400)}const title=text(b.title,220),summary=text(b.summary,4000),category=text(b.category,40),severity=text(b.severity||'medium',20);if(!title||!INCIDENT_CATEGORIES.includes(category)||!INCIDENT_SEVERITIES.includes(severity))return j({error:'Provide a title, supported category and severity.'},400);const row={incident_key:null,category,severity,status:'open',source:'manual',title,summary,metadata:clean(b.metadata||{}),detected_at:new Date().toISOString(),last_seen_at:new Date().toISOString(),created_by:a.actor.id,updated_at:new Date().toISOString()};const r=await svc(env,'/rest/v1/hc_admin_incidents',{method:'POST',body:row,headers:{Prefer:'return=representation'}});if(!r.ok)return j({error:text(r.data?.message||'Incident could not be created.'),migrationRequired:missing(r)},r.status===503?503:500);const item=Array.isArray(r.data)?r.data[0]:r.data;await audit(env,a.actor,'admin.phase6.incident.create',item?.id||title,'',{category,severity});return j({ok:true,item})}
async function incidentAction(request,env,id){const a=await requireRoles(request,env,INCIDENT_WRITE_ROLES);if(a.error)return a.error;if(!uuid(id))return j({error:'Invalid incident ID.'},400);let b;try{b=await jsonBody(request)}catch(e){return j({error:e.message},e.status||400)}const action=text(b.action,20),note=text(b.note,2000);if(!['acknowledge','resolve','reopen'].includes(action))return j({error:'Choose acknowledge, resolve, or reopen.'},400);const cur=await latest(env,'hc_admin_incidents','id,severity,status,title','updated_at.desc','id=eq.'+encodeURIComponent(id));if(!cur.ok||!cur.row)return j({error:'Incident not found.'},404);if(action==='resolve'&&note.length<3)return j({error:'Give a resolution note.'},400);if(action==='resolve'&&cur.row.severity==='critical'&&text(b.confirmation,20)!=='RESOLVE')return j({error:'Type RESOLVE to close a critical incident.',confirmation:'RESOLVE'},409);const now=new Date().toISOString(),patch=action==='acknowledge'?{status:'acknowledged',acknowledged_by:a.actor.id,acknowledged_at:now,updated_at:now}:action==='resolve'?{status:'resolved',resolution_note:note,resolved_by:a.actor.id,resolved_at:now,updated_at:now}:{status:'open',acknowledged_by:null,acknowledged_at:null,resolution_note:null,resolved_by:null,resolved_at:null,last_seen_at:now,updated_at:now};const r=await svc(env,'/rest/v1/hc_admin_incidents?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:patch,headers:{Prefer:'return=representation'}});if(!r.ok)return j({error:text(r.data?.message||'Incident could not be updated.')},r.status===503?503:500);await audit(env,a.actor,'admin.phase6.incident.'+action,id,note,{severity:cur.row.severity});return j({ok:true,item:Array.isArray(r.data)?r.data[0]:r.data})}

async function readinessList(request,env){const a=await requireRoles(request,env,ALL_ADMIN_ROLES);if(a.error)return a.error;const health=await healthData(env),data=await readinessData(env,health);return j({...data,healthStatus:health.overallStatus})}
async function readinessSave(request,env,key){const a=await requireRoles(request,env,READINESS_WRITE_ROLES);if(a.error)return a.error;if(!/^[a-z0-9_]{3,80}$/.test(key))return j({error:'Invalid readiness key.'},400);let b;try{b=await jsonBody(request)}catch(e){return j({error:e.message},e.status||400)}const status=text(b.status,20),evidence=text(b.evidence,2000),note=text(b.note,2000);if(!READINESS_STATUSES.includes(status))return j({error:'Invalid readiness status.'},400);const cur=await latest(env,'hc_admin_readiness_checks','key,required,status,label','updated_at.desc','key=eq.'+encodeURIComponent(key));if(!cur.ok||!cur.row)return j({error:'Readiness check not found.'},404);if(cur.row.required&&status==='waived')return j({error:'Required launch checks cannot be waived.'},409);if(status==='passed'&&evidence.length<3)return j({error:'Provide evidence before marking a readiness check passed.'},400);const r=await svc(env,'/rest/v1/hc_admin_readiness_checks?key=eq.'+encodeURIComponent(key),{method:'PATCH',body:{status,evidence:evidence||null,note:note||null,checked_by:a.actor.id,checked_at:new Date().toISOString(),updated_at:new Date().toISOString()},headers:{Prefer:'return=representation'}});if(!r.ok)return j({error:text(r.data?.message||'Readiness check could not be updated.')},r.status===503?503:500);await audit(env,a.actor,'admin.phase6.readiness.update',key,note,{status,evidence:evidence.slice(0,300)});return j({ok:true,item:Array.isArray(r.data)?r.data[0]:r.data})}

async function saveHealthSnapshot(env,health,source='system',a=null){const r=await svc(env,'/rest/v1/hc_admin_health_snapshots',{method:'POST',body:{overall_status:health.overallStatus,source,checks:clean(health.checks),metrics:clean(health.metrics),metadata:{phase:6,privacyMinimized:true},actor_user_id:a?.id||null,captured_at:new Date().toISOString()},headers:{Prefer:'return=representation'}});return{...r,item:r.ok?(Array.isArray(r.data)?r.data[0]:r.data):null}}
async function manualHealthSnapshot(request,env){const a=await requireRoles(request,env,HEALTH_RUN_ROLES);if(a.error)return a.error;let b;try{b=await jsonBody(request)}catch(e){return j({error:e.message},e.status||400)}if(text(b.confirmation,20)!=='RUN')return j({error:'Type RUN to capture a fresh operational health snapshot.',confirmation:'RUN'},409);const health=await healthData(env);if(health.migrationRequired)return j({error:'Phase 6 database migration is required before snapshots can be saved.',health},409);const r=await saveHealthSnapshot(env,health,'admin',a.actor);if(!r.ok)return j({error:text(r.data?.message||'Health snapshot could not be saved.')},r.status===503?503:500);await audit(env,a.actor,'admin.phase6.health.snapshot',r.item?.id||'', '',{overallStatus:health.overallStatus});return j({ok:true,health,snapshot:r.item})}
async function snapshotList(request,env){const a=await requireRoles(request,env,ALL_ADMIN_ROLES);if(a.error)return a.error;const r=await svc(env,'/rest/v1/hc_admin_health_snapshots?select=id,overall_status,source,checks,metrics,metadata,captured_at&order=captured_at.desc&limit=50');if(!r.ok)return j({error:text(r.data?.message||'Health history could not be loaded.'),migrationRequired:missing(r)},r.status===503?503:500);return j({items:r.data||[]})}

async function upsertAutomatedIncident(env,key,category,severity,title,summary,metadata){const existing=await latest(env,'hc_admin_incidents','id,status,severity','last_seen_at.desc','incident_key=eq.'+encodeURIComponent(key));const now=new Date().toISOString();if(existing.ok&&existing.row){const reopen=existing.row.status==='resolved';return svc(env,'/rest/v1/hc_admin_incidents?id=eq.'+encodeURIComponent(existing.row.id),{method:'PATCH',body:{category,severity,title,summary,metadata:clean(metadata),last_seen_at:now,updated_at:now,...(reopen?{status:'open',acknowledged_by:null,acknowledged_at:null,resolution_note:null,resolved_by:null,resolved_at:null,detected_at:now}:{})},headers:{Prefer:'return=minimal'}})}return svc(env,'/rest/v1/hc_admin_incidents',{method:'POST',body:{incident_key:key,category,severity,status:'open',source:'health_check',title,summary,metadata:clean(metadata),detected_at:now,last_seen_at:now,updated_at:now},headers:{Prefer:'return=minimal'}})}
async function syncCriticalIncidents(env,health){for(const c of health.checks.filter(x=>x.status==='critical')){const map={critical_moderation:['moderation','critical','Critical moderation cases waiting','Critical safety/moderation reports require human review.'],notification_failures:['notifications','high','High notification delivery failure volume','Native in-app delivery failures exceeded the operational threshold.']},m=map[c.key]||['operations','high',c.label,c.detail];await upsertAutomatedIncident(env,'phase6:'+c.key,m[0],m[1],m[2],c.detail,{checkKey:c.key,target:c.target}).catch(()=>{})}}

export async function runPhase6Scheduled(env){if(!cfg(env).service)return{ok:false,skipped:true,reason:'service_role_not_configured'};const health=await healthData(env);if(health.migrationRequired)return{ok:false,skipped:true,reason:'phase6_migration_required',healthStatus:health.overallStatus};const last=await latest(env,'hc_admin_health_snapshots','id,overall_status,captured_at','captured_at.desc');const age=last.row?Date.now()-Date.parse(last.row.captured_at||''):Infinity,changed=last.row?.overall_status!==health.overallStatus;let snapshot=null;if(!last.row||changed||!Number.isFinite(age)||age>=55*60*1000)snapshot=await saveHealthSnapshot(env,health,'cron',null);await syncCriticalIncidents(env,health);return{ok:true,healthStatus:health.overallStatus,snapshotSaved:!!snapshot?.ok,criticalChecks:health.checks.filter(x=>x.status==='critical').length}}

export async function runPhase6AndPhase5Scheduled(env){const phase5=await runPhase5Scheduled(env),phase6=await runPhase6Scheduled(env);return{ok:phase5?.ok!==false&&phase6?.ok!==false,phase5,phase6}}

export async function handleAdmin(request,env){const u=new URL(request.url),p=u.pathname;if(p==='/admin'||p==='/admin/')return page(adminHtml(VERSION));if(!p.startsWith('/api/admin/'))return handleAdminV5(request,env);if(!sameOrigin(request))return j({error:'Cross-site admin request blocked.'},403);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{allow:'GET, POST, HEAD, OPTIONS'}});
  if(p==='/api/admin/phase6/status'&&request.method==='GET')return phase6Status(request,env);
  if(p==='/api/admin/incidents'&&request.method==='GET')return incidentList(request,env);
  if(p==='/api/admin/incidents'&&request.method==='POST')return incidentCreate(request,env);
  let m=p.match(/^\/api\/admin\/incidents\/([^/]+)\/action$/);if(m&&request.method==='POST')return incidentAction(request,env,m[1]);
  if(p==='/api/admin/readiness'&&request.method==='GET')return readinessList(request,env);
  m=p.match(/^\/api\/admin\/readiness\/([^/]+)$/);if(m&&request.method==='POST')return readinessSave(request,env,decodeURIComponent(m[1]));
  if(p==='/api/admin/health/snapshot'&&request.method==='POST')return manualHealthSnapshot(request,env);
  if(p==='/api/admin/health/history'&&request.method==='GET')return snapshotList(request,env);
  return handleAdminV5(request,env)
}
