import {adminHtml as adminHtmlV17} from './admin-ui-v17.js';

export function adminHtml(version){
  const upgrade=`<style>
.hc18-ai-launch{position:fixed;right:22px;bottom:22px;z-index:80;border:1px solid #ff6b9a55;background:linear-gradient(135deg,#d72b63,#7b4dff);color:#fff;border-radius:999px;padding:12px 16px;font-weight:800;box-shadow:0 16px 45px #0008;cursor:pointer}.hc18-ai-launch:hover{filter:brightness(1.08)}.hc18-ai-panel{position:fixed;right:22px;bottom:78px;z-index:81;width:min(420px,calc(100vw - 28px));max-height:min(720px,calc(100vh - 105px));display:none;overflow:auto;border:1px solid #ffffff1c;background:#0b1019f7;backdrop-filter:blur(16px);border-radius:20px;box-shadow:0 30px 90px #000c}.hc18-ai-panel.open{display:block}.hc18-ai-head{position:sticky;top:0;z-index:2;display:flex;justify-content:space-between;gap:12px;align-items:flex-start;padding:16px;border-bottom:1px solid #ffffff12;background:#0b1019f2}.hc18-ai-head h3{margin:0;font-size:17px}.hc18-ai-head p{margin:4px 0 0;color:#93a0b5;font-size:11px;line-height:1.45}.hc18-ai-close{border:0;background:transparent;color:#fff;font-size:22px;cursor:pointer}.hc18-ai-body{padding:14px}.hc18-ai-context{display:flex;justify-content:space-between;gap:8px;align-items:center;border:1px solid #ffffff12;background:#080d14;border-radius:12px;padding:10px;margin-bottom:10px}.hc18-ai-context small{display:block;color:#8794a8}.hc18-ai-context b{font-size:13px}.hc18-ai-badge{border:1px solid #56d69a40;background:#56d69a14;color:#70e6ad;border-radius:999px;padding:4px 8px;font-size:10px;font-weight:800}.hc18-ai-presets{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.hc18-ai-presets button{border:1px solid #ffffff16;background:#111823;color:#dbe3ef;border-radius:999px;padding:7px 10px;font-size:11px;cursor:pointer}.hc18-ai-presets button:hover{background:#182231}.hc18-ai-input{width:100%;min-height:112px;resize:vertical;background:#070b11;border:1px solid #ffffff18;color:#fff;border-radius:12px;padding:11px}.hc18-ai-actions{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-top:9px}.hc18-ai-run{border:1px solid #ee5a8a;background:#d72b63;color:#fff;border-radius:10px;padding:9px 13px;font-weight:700;cursor:pointer}.hc18-ai-run:disabled{opacity:.5;cursor:not-allowed}.hc18-ai-clear{border:1px solid #ffffff15;background:#ffffff08;color:#d9e1ed;border-radius:10px;padding:9px 11px;cursor:pointer}.hc18-ai-answer{margin-top:12px;white-space:pre-wrap;line-height:1.58;border:1px solid #ffffff12;background:#070c13;border-radius:13px;padding:12px;min-height:86px;color:#dce4ef}.hc18-ai-note{margin-top:9px;color:#8391a6;font-size:10px;line-height:1.5}.hc18-ai-error{color:#ff9aab}.hc18-ai-top{border-color:#8d6bff45!important;background:#8d6bff12!important}.hc18-ai-dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:#63dfa7;margin-right:5px}
@media(max-width:650px){.hc18-ai-launch{right:14px;bottom:14px}.hc18-ai-panel{right:14px;bottom:68px;width:calc(100vw - 28px);max-height:calc(100vh - 90px)}}
</style><button class="hc18-ai-launch" id="hc18AiLaunch" type="button">✦ AI Help</button><aside class="hc18-ai-panel" id="hc18AiPanel" aria-label="Admin AI help"><div class="hc18-ai-head"><div><h3>Heart Connect Admin AI</h3><p>Ask for explanations, checks, summaries, drafts and recommended next steps.</p></div><button class="hc18-ai-close" id="hc18AiClose" type="button" aria-label="Close AI help">×</button></div><div class="hc18-ai-body"><div class="hc18-ai-context"><div><small>Working in</small><b id="hc18AiSection">Overview</b></div><span class="hc18-ai-badge" id="hc18AiStatus"><span class="hc18-ai-dot"></span>Advisory</span></div><div class="hc18-ai-presets" id="hc18AiPresets"></div><textarea class="hc18-ai-input" id="hc18AiPrompt" placeholder="Ask AI for help with this Admin section…"></textarea><div class="hc18-ai-actions"><button class="hc18-ai-clear" id="hc18AiClear" type="button">Clear</button><button class="hc18-ai-run" id="hc18AiRun" type="button">Ask Admin AI</button></div><div class="hc18-ai-answer" id="hc18AiAnswer">AI can help you understand this screen and suggest what to review. It cannot execute high-impact actions.</div><div class="hc18-ai-note">Human review remains required for bans, suspensions, verification decisions, payments/refunds, deletions, publishing and other high-impact actions. Do not paste passwords, tokens, private messages or identity evidence.</div></div></aside><script>
(()=>{
  const panel=document.getElementById('hc18AiPanel'),launch=document.getElementById('hc18AiLaunch'),close=document.getElementById('hc18AiClose'),sectionEl=document.getElementById('hc18AiSection'),prompt=document.getElementById('hc18AiPrompt'),answer=document.getElementById('hc18AiAnswer'),presets=document.getElementById('hc18AiPresets'),run=document.getElementById('hc18AiRun'),status=document.getElementById('hc18AiStatus');
  let selectedUserId='';
  function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
  function section(){const t=(document.getElementById('title')?.textContent||'Overview').trim();return t||'Overview'}
  function key(){return section().toLowerCase().replace(/[^a-z0-9]+/g,'_')}
  function workspace(){const k=key();if(k.includes('moderation'))return'moderation';if(k.includes('verification'))return'verification';if(k.includes('payment'))return'payments';if(k.includes('content')||k.includes('cms')||k.includes('page'))return'cms';return'overview'}
  const common=['What should I review here?','Explain this screen','Find risks or missing items','Suggest next steps'];
  const userPrompts=['Check Discover readiness','Suggest profile improvements','Summarize safety signals','What should Admin review next?'];
  const sectionPrompts={moderation:['Summarize open moderation risks','Prioritize what needs human review','Explain the safest next steps','Draft a neutral case note'],verification:['Summarize pending verification work','What needs human verification?','Explain rejection risks','Draft a review note'],payments:['Summarize payment issues','Flag transactions needing review','Explain unusual statuses','Draft a customer-safe explanation'],cms:['Review content quality','Suggest SEO improvements','Check publishing risks','Draft improved content'],analytics:['Explain the key metrics','Spot unusual trends','What should management watch?','Suggest useful reports'],security_review:['Summarize security concerns','Prioritize unresolved risks','Explain this security status','Suggest safe next checks'],staff_roles:['Review permission risks','Explain role access','Spot excessive permissions','Suggest safer role setup']};
  function renderPresets(){const k=key(),arr=(k==='users'&&selectedUserId)?userPrompts:(sectionPrompts[k]||common);presets.innerHTML=arr.map(x=>'<button type="button" data-prompt="'+esc(x)+'">'+esc(x)+'</button>').join('');presets.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{prompt.value=b.dataset.prompt;prompt.focus()})}
  function refresh(){sectionEl.textContent=section()+(key()==='users'&&selectedUserId?' · selected member':'');renderPresets()}
  async function req(url,opt={}){const r=await fetch(url,{credentials:'same-origin',...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Admin AI request failed.');return d}
  async function ask(){const q=prompt.value.trim();if(q.length<3){answer.textContent='Enter a question or choose one of the quick-help buttons.';return}run.disabled=true;answer.classList.remove('hc18-ai-error');answer.textContent='Thinking…';try{let d;if(key()==='users'&&selectedUserId){d=await req('/api/admin/users/'+encodeURIComponent(selectedUserId)+'/ai',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt:q})})}else{const contextual='Admin section: '+section()+'. '+q;d=await req('/api/admin/ai/ask',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({workspace:workspace(),prompt:contextual})})}answer.textContent=d.answer||'AI returned no text.'}catch(e){answer.textContent=e.message;answer.classList.add('hc18-ai-error')}finally{run.disabled=false}}
  launch.onclick=()=>{panel.classList.toggle('open');refresh();if(panel.classList.contains('open'))prompt.focus()};close.onclick=()=>panel.classList.remove('open');document.getElementById('hc18AiClear').onclick=()=>{prompt.value='';answer.textContent='Ready. Ask me for help with the current Admin section.';answer.classList.remove('hc18-ai-error')};run.onclick=ask;prompt.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')ask()});
  document.addEventListener('click',e=>{const b=e.target?.closest?.('[data-user]');if(b?.dataset?.user){selectedUserId=b.dataset.user;setTimeout(refresh,50)}const nav=e.target?.closest?.('[data-tab]');if(nav)setTimeout(()=>{selectedUserId='';refresh()},80)},true);
  new MutationObserver(()=>refresh()).observe(document.getElementById('title')||document.body,{childList:true,subtree:true});
  req('/api/admin/ai/status').then(d=>{if(!d.configured){status.textContent='AI not configured';run.disabled=true;answer.textContent='AI is not configured on this preview Worker yet.'}}).catch(()=>{});refresh();
})();
</script>`;
  return adminHtmlV17(version).replace('</body>',upgrade+'</body>');
}
