const VERSION='hc-cloudflare-native-v1';
const ACCESS_COOKIE='__Host-hc_cf_access';
const REFRESH_COOKIE='__Host-hc_cf_refresh';
const DEFAULT_SUPABASE_URL='https://zzhzkikezjtbntaqiurk.supabase.co';
const DEFAULT_PUBLISHABLE_KEY='sb_publishable_HB0Irz6bxug1hHs518oPZQ_LC83i4qT';

function config(env){return{url:String(env.SUPABASE_URL||DEFAULT_SUPABASE_URL).replace(/\/+$/,''),key:String(env.SUPABASE_PUBLISHABLE_KEY||DEFAULT_PUBLISHABLE_KEY)}}
function cookies(request){const out={};for(const part of String(request.headers.get('cookie')||'').split(';')){const i=part.indexOf('=');if(i>0){const k=part.slice(0,i).trim();try{out[k]=decodeURIComponent(part.slice(i+1).trim())}catch{out[k]=part.slice(i+1).trim()}}}return out}
function cookie(name,value,maxAge){return `${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${Math.max(0,Math.floor(maxAge))}`}
function clearCookie(name){return `${name}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`}
function j(data,status=200,extra={}){const headers=new Headers({'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...extra});return new Response(JSON.stringify(data),{status,headers})}
function messageOf(data,fallback='Request failed.'){return String(data?.msg||data?.message||data?.error_description||data?.error||fallback).slice(0,500)}
function securityHeaders(response){const h=new Headers(response.headers);h.set('x-content-type-options','nosniff');h.set('referrer-policy','strict-origin-when-cross-origin');h.set('permissions-policy','camera=(self), microphone=(self), geolocation=(self), payment=(self), interest-cohort=()');h.set('strict-transport-security','max-age=31536000; includeSubDomains');h.set('cross-origin-opener-policy','same-origin-allow-popups');h.set('x-heart-connect-native',VERSION);const ct=h.get('content-type')||'';if(ct.includes('text/html')){h.set('x-frame-options','SAMEORIGIN');h.set('content-security-policy',"frame-ancestors 'self'; object-src 'none'; base-uri 'self'")}return new Response(response.body,{status:response.status,statusText:response.statusText,headers:h})}
function unsafe(request){return !['GET','HEAD','OPTIONS'].includes(request.method)}
function sameOrigin(request){if(!unsafe(request))return true;const site=request.headers.get('sec-fetch-site');if(site==='cross-site')return false;const origin=request.headers.get('origin');if(!origin)return true;try{return new URL(origin).origin===new URL(request.url).origin}catch{return false}}
async function body(request,max=100000){const len=Number(request.headers.get('content-length')||0);if(len>max)throw Object.assign(new Error('request_too_large'),{status:413});const ct=request.headers.get('content-type')||'';if(!ct.toLowerCase().includes('application/json'))throw Object.assign(new Error('json_required'),{status:415});try{return await request.json()}catch{throw Object.assign(new Error('invalid_json'),{status:400})}}
async function sb(env,path,{method='GET',token,body:payload,headers:extra}={}){const c=config(env),headers=new Headers({'apikey':c.key,'accept':'application/json',...extra});if(token)headers.set('authorization','Bearer '+token);if(payload!==undefined)headers.set('content-type','application/json');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(c.url+path,{method,headers,body:payload===undefined?undefined:JSON.stringify(payload),signal:controller.signal});let data=null;const text=await r.text();if(text){try{data=JSON.parse(text)}catch{data=text}}return{ok:r.ok,status:r.status,data,headers:r.headers}}catch(e){return{ok:false,status:503,data:{message:e?.name==='AbortError'?'Upstream timeout.':'Supabase is temporarily unavailable.'},headers:new Headers()}}finally{clearTimeout(timer)}}
function appendSessionCookies(response,data){const h=new Headers(response.headers),expires=Number(data?.expires_in)||3600;h.append('set-cookie',cookie(ACCESS_COOKIE,String(data?.access_token||''),Math.min(Math.max(expires,60),7200)));if(data?.refresh_token)h.append('set-cookie',cookie(REFRESH_COOKIE,String(data.refresh_token),30*24*60*60));return new Response(response.body,{status:response.status,statusText:response.statusText,headers:h})}
async function refresh(request,env){const c=cookies(request),rt=c[REFRESH_COOKIE];if(!rt)return null;const r=await sb(env,'/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:rt}});if(!r.ok||!r.data?.access_token)return null;return r.data}
async function session(request,env,{refreshIfNeeded=true}={}){const c=cookies(request);let token=c[ACCESS_COOKIE]||'';let userRes=token?await sb(env,'/auth/v1/user',{token}):null;let refreshed=null;if((!userRes||!userRes.ok)&&refreshIfNeeded){refreshed=await refresh(request,env);if(refreshed?.access_token){token=refreshed.access_token;userRes=await sb(env,'/auth/v1/user',{token})}}if(!userRes?.ok||!userRes.data?.id)return{ok:false,status:401};return{ok:true,status:200,token,user:userRes.data,refreshed}}
function withRefresh(response,s){return s?.refreshed?appendSessionCookies(response,s.refreshed):response}
function email(v){const s=String(v||'').trim().toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)?s:''}
function strongPassword(v){const s=String(v||'');return s.length>=8&&/[a-z]/.test(s)&&/[A-Z]/.test(s)&&/[0-9]/.test(s)&&/[^A-Za-z0-9]/.test(s)}
function adult(dob){const d=new Date(String(dob||''));if(Number.isNaN(d.getTime()))return false;const n=new Date();let a=n.getUTCFullYear()-d.getUTCFullYear();const m=n.getUTCMonth()-d.getUTCMonth();if(m<0||(m===0&&n.getUTCDate()<d.getUTCDate()))a--;return a>=18}
function uuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''))}
function text(v,n){return String(v||'').trim().slice(0,n)}
function arr(v,n=30){return Array.isArray(v)?v.map(x=>text(x,80)).filter(Boolean).slice(0,n):String(v||'').split(',').map(x=>text(x,80)).filter(Boolean).slice(0,n)}
function profilePayload(b,uid){const age=Number(b.age);if(!Number.isInteger(age)||age<18||age>100)throw Object.assign(new Error('age_invalid'),{status:400});const name=text(b.name||b.display_name,80),city=text(b.city,120),country=text(b.country,120);if(!name||!city||!country)throw Object.assign(new Error('profile_required_fields'),{status:400});return{user_id:uid,display_name:name,headline:text(b.headline,160)||null,bio:text(b.bio,2000)||null,age,gender:text(b.gender,80)||null,meet_gender:text(b.meetGender||b.meet_gender,80)||'Everyone',country,city,relationship_intention:text(b.relationshipGoal||b.relationship_intention,120)||null,occupation:text(b.occupation,160)||null,education:text(b.education,160)||null,languages:arr(b.languages),interests:arr(b.interests),smoking:text(b.smoking,40)||null,drinking:text(b.drinking,40)||null,children:text(b.children,60)||null,wants_children:text(b.wantsChildren||b.wants_children,60)||null,personality:text(b.personality,500)||null,profile_prompt:text(b.prompt||b.profile_prompt,500)||null,travel:(b.travel&&typeof b.travel==='object')?b.travel:{},is_discoverable:b.is_discoverable!==false,profile_completion:Math.max(0,Math.min(100,Number(b.completion||b.profile_completion)||0)),last_active_at:new Date().toISOString(),updated_at:new Date().toISOString()}}
function safety(textValue){const v=String(textValue||'');const critical=/\b(kill you|hurt you|i will harm|blackmail|sextortion|nudes? for money|threaten you)\b/i.test(v);const money=/\b(send|transfer|wire|pay|deposit|remit).{0,45}\b(money|cash|mpesa|m-pesa|airtime|funds|fee|payment)\b/i.test(v)||/\b(crypto|bitcoin|btc|usdt|ethereum|gift card|bank transfer|password|otp|verification code|pin|passcode)\b/i.test(v);return{critical,warning:money?'Safety reminder: never send money, crypto, gift cards, banking credentials, passwords, PINs or verification codes to someone you have not independently verified.':''}}

async function authSignIn(request,env){const b=await body(request),e=email(b.email),p=String(b.password||'');if(!e||!p)return j({error:'Enter a valid email and password.'},400);const r=await sb(env,'/auth/v1/token?grant_type=password',{method:'POST',body:{email:e,password:p}});if(!r.ok)return j({error:r.status===400||r.status===401?'Email or password is incorrect.':messageOf(r.data)},r.status===429?429:r.status>=500?503:401);return appendSessionCookies(j({ok:true,signedIn:true,emailVerified:!!(r.data?.user?.email_confirmed_at||r.data?.user?.confirmed_at)}),r.data)}
async function authRegister(request,env){const b=await body(request),e=email(b.email),p=String(b.password||''),dob=String(b.dob||'');if(!e||!text(b.firstName,80)||!text(b.city,120)||!text(b.country,120))return j({error:'Complete your name, email, country and city.'},400);if(!adult(dob)||b.ageConfirm!==true)return j({error:'Heart Connect is available only to adults aged 18 or older.'},400);if(b.terms!==true||b.privacy!==true)return j({error:'Terms and Privacy Policy acceptance are required.'},400);if(!strongPassword(p))return j({error:'Use 8+ characters with uppercase, lowercase, a number and a special character.'},400);const now=new Date().toISOString(),r=await sb(env,'/auth/v1/signup?redirect_to='+encodeURIComponent(new URL(request.url).origin),{method:'POST',body:{email:e,password:p,data:{first_name:text(b.firstName,80),name:text(b.firstName,80),dob,date_of_birth:dob,gender:text(b.gender,80),country:text(b.country,120),city:text(b.city,120),relationship_intention:text(b.intention,120),signup_phone:text(b.phone,30),age_confirmed:true,terms_accepted:true,privacy_accepted:true,terms_accepted_at:now,privacy_accepted_at:now}}});if(!r.ok)return j({error:messageOf(r.data,'Account registration could not be completed.')},r.status===429?429:r.status>=500?503:400);if(r.data?.access_token)return appendSessionCookies(j({ok:true,signedIn:true,requiresConfirmation:false}),r.data);return j({ok:true,signedIn:false,requiresConfirmation:true})}
async function authSession(request,env){const s=await session(request,env);if(!s.ok)return j({authenticated:false},401);const r=j({authenticated:true,provider:'supabase-cloudflare',user:{id:s.user.id,email:s.user.email||'',phone:s.user.phone||'',emailVerified:!!(s.user.email_confirmed_at||s.user.confirmed_at)}});return withRefresh(r,s)}
async function authRefresh(request,env){const data=await refresh(request,env);if(!data)return j({error:'Session refresh is unavailable. Sign in again.'},401);return appendSessionCookies(j({ok:true}),data)}
async function authLogout(request,env){const c=cookies(request),token=c[ACCESS_COOKIE]||'';if(token)await sb(env,'/auth/v1/logout?scope=local',{method:'POST',token});const r=j({ok:true}),h=new Headers(r.headers);h.append('set-cookie',clearCookie(ACCESS_COOKIE));h.append('set-cookie',clearCookie(REFRESH_COOKIE));return new Response(r.body,{status:r.status,headers:h})}
async function getMe(request,env){const s=await session(request,env);if(!s.ok)return j({error:'Authentication required.'},401);const q='/rest/v1/dating_profiles?select=user_id,display_name,headline,bio,age,gender,meet_gender,country,city,relationship_intention,occupation,education,languages,interests,smoking,drinking,children,wants_children,personality,profile_prompt,travel,tier,profile_completion,verification_level,is_discoverable,last_active_at&user_id=eq.'+encodeURIComponent(s.user.id)+'&limit=1',r=await sb(env,q,{token:s.token});if(!r.ok)return withRefresh(j({error:messageOf(r.data,'Profile could not be loaded.')},r.status>=500?503:r.status),s);return withRefresh(j(Array.isArray(r.data)?(r.data[0]||null):null),s)}
async function saveMe(request,env){const s=await session(request,env);if(!s.ok)return j({error:'Authentication required.'},401);const b=await body(request);let record;try{record=profilePayload(b,s.user.id)}catch(e){return j({error:e.message==='age_invalid'?'Age must be between 18 and 100.':'Complete your name, city and country.'},e.status||400)}const r=await sb(env,'/rest/v1/dating_profiles?on_conflict=user_id',{method:'POST',token:s.token,body:record,headers:{Prefer:'resolution=merge-duplicates,return=representation'}});if(!r.ok)return withRefresh(j({error:messageOf(r.data,'Profile could not be saved.')},r.status>=500?503:r.status),s);return withRefresh(j({ok:true,profile:Array.isArray(r.data)?r.data[0]:r.data}),s)}
async function discover(request,env){const s=await session(request,env);if(!s.ok)return j({error:'Authentication required.'},401);const u=new URL(request.url),limit=Math.max(1,Math.min(50,Number(u.searchParams.get('limit'))||20)),offset=Math.max(0,Number(u.searchParams.get('offset'))||0),r=await sb(env,'/rest/v1/rpc/hc_discover_v1',{method:'POST',token:s.token,body:{p_limit:limit,p_offset:offset}});if(!r.ok)return withRefresh(j({error:messageOf(r.data,'Discovery could not be loaded.')},r.status>=500?503:r.status),s);return withRefresh(j(r.data),s)}
async function connect(request,env,target){const s=await session(request,env);if(!s.ok)return j({error:'Authentication required.'},401);if(!uuid(target))return j({error:'Invalid profile.'},400);const b=await body(request),action=text(b.action,20).toLowerCase(),allowed=new Set(['like','superlike','pass','unlike','save','unsave','block','unblock']);if(!allowed.has(action))return j({error:'Invalid connection action.'},400);const r=await sb(env,'/rest/v1/rpc/hc_connect_v1',{method:'POST',token:s.token,body:{p_target:target,p_action:action}});if(!r.ok)return withRefresh(j({error:messageOf(r.data,'Connection could not be updated.')},r.status>=500?503:400),s);return withRefresh(j(r.data),s)}
async function signMedia(request,env){const s=await session(request,env);if(!s.ok)return j({error:'Authentication required.'},401);const b=await body(request),paths=Array.isArray(b.paths)?b.paths.map(x=>String(x||'')).filter(x=>x&&x.length<500).slice(0,12):[];if(!paths.length)return withRefresh(j({items:[]}),s);const items=[];for(const path of paths){const r=await sb(env,'/storage/v1/object/sign/profile-media/'+path.split('/').map(encodeURIComponent).join('/'),{method:'POST',token:s.token,body:{expiresIn:600}});if(r.ok&&r.data?.signedURL)items.push({path,url:config(env).url+'/storage/v1'+r.data.signedURL})}return withRefresh(j({items}),s)}
async function messages(request,env,matchId){const s=await session(request,env);if(!s.ok)return j({error:'Authentication required.'},401);if(!uuid(matchId))return j({error:'Invalid conversation.'},400);if(request.method==='GET'){const u=new URL(request.url),limit=Math.max(1,Math.min(80,Number(u.searchParams.get('limit'))||50)),r=await sb(env,'/rest/v1/messages?select=id,match_id,sender_id,body,message_type,media_path,reply_to_id,edited_at,deleted_at,created_at&match_id=eq.'+encodeURIComponent(matchId)+'&order=created_at.asc&limit='+limit,{token:s.token});if(!r.ok)return withRefresh(j({error:messageOf(r.data,'Conversation could not be loaded.')},r.status===401||r.status===403?403:r.status>=500?503:r.status),s);return withRefresh(j({items:r.data||[]}),s)}const b=await body(request),textValue=text(b.text||b.body,1000);if(!textValue)return withRefresh(j({error:'Message must contain 1–1000 characters.'},400),s);const check=safety(textValue);if(check.critical)return withRefresh(j({error:'This message cannot be delivered because it contains a severe safety risk.'},403),s);const reply=String(b.replyToId||b.reply_to_id||'');if(reply&&!uuid(reply))return withRefresh(j({error:'Invalid reply target.'},400),s);const payload={match_id:matchId,sender_id:s.user.id,body:textValue,message_type:'text',reply_to_id:reply||null},r=await sb(env,'/rest/v1/messages',{method:'POST',token:s.token,body:payload,headers:{Prefer:'return=representation'}});if(!r.ok)return withRefresh(j({error:messageOf(r.data,'Message could not be sent.')},r.status===401||r.status===403?403:r.status>=500?503:r.status),s);return withRefresh(j({ok:true,message:Array.isArray(r.data)?r.data[0]:r.data,warning:check.warning}),s)}

export async function handleNativeApi(request,env){const u=new URL(request.url),p=u.pathname;if(!p.startsWith('/api/_cf/'))return null;if(!sameOrigin(request))return securityHeaders(j({error:'Cross-site request blocked.'},403));try{
  if(p==='/api/_cf/health'&&request.method==='GET')return securityHeaders(j({ok:true,version:VERSION,mode:'shadow',supabase:true,time:new Date().toISOString()}));
  if(p==='/api/_cf/auth/signin'&&request.method==='POST')return securityHeaders(await authSignIn(request,env));
  if(p==='/api/_cf/auth/register'&&request.method==='POST')return securityHeaders(await authRegister(request,env));
  if(p==='/api/_cf/auth/session'&&request.method==='GET')return securityHeaders(await authSession(request,env));
  if(p==='/api/_cf/auth/refresh'&&request.method==='POST')return securityHeaders(await authRefresh(request,env));
  if(p==='/api/_cf/auth/logout'&&request.method==='POST')return securityHeaders(await authLogout(request,env));
  if(p==='/api/_cf/me'&&request.method==='GET')return securityHeaders(await getMe(request,env));
  if(p==='/api/_cf/me'&&request.method==='POST')return securityHeaders(await saveMe(request,env));
  if(p==='/api/_cf/discover'&&request.method==='GET')return securityHeaders(await discover(request,env));
  if(p==='/api/_cf/media/sign'&&request.method==='POST')return securityHeaders(await signMedia(request,env));
  const cm=p.match(/^\/api\/_cf\/connect\/([^/]+)$/);if(cm&&request.method==='POST')return securityHeaders(await connect(request,env,cm[1]));
  const mm=p.match(/^\/api\/_cf\/messages\/([^/]+)$/);if(mm&&(request.method==='GET'||request.method==='POST'))return securityHeaders(await messages(request,env,mm[1]));
  return securityHeaders(j({error:'Native API route not found.'},404));
}catch(e){const status=Number(e?.status)||500;return securityHeaders(j({error:status===413?'Request too large.':status===415?'JSON request required.':status===400?'Invalid request.':'Native API error.'},status))}}

export {securityHeaders,VERSION};
