import {handleNativeApi as handleNativeApiV1,securityHeaders} from './native-api-v1.js';

const VERSION='hc-cloudflare-native-v2';
const ACCESS_COOKIE='__Host-hc_cf_access';
const REFRESH_COOKIE='__Host-hc_cf_refresh';
const DEFAULT_SUPABASE_URL='https://zzhzkikezjtbntaqiurk.supabase.co';
const DEFAULT_PUBLISHABLE_KEY='sb_publishable_HB0Irz6bxug1hHs518oPZQ_LC83i4qT';
const PRIVACY_DEFAULT={discoverable:true,profileVisibility:'standard',photoVisibility:'everyone',showOnline:true,showDistance:true,showLastSeen:true,readReceipts:true,showTravel:true,searchIndexing:false,verifiedOnlyMessaging:false};

function config(env){return{url:String(env.SUPABASE_URL||DEFAULT_SUPABASE_URL).replace(/\/+$/,''),key:String(env.SUPABASE_PUBLISHABLE_KEY||DEFAULT_PUBLISHABLE_KEY)}}
function parseCookies(request){const out={};for(const part of String(request.headers.get('cookie')||'').split(';')){const i=part.indexOf('=');if(i>0){const key=part.slice(0,i).trim();try{out[key]=decodeURIComponent(part.slice(i+1).trim())}catch{out[key]=part.slice(i+1).trim()}}}return out}
function cookie(name,value,maxAge){return `${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${Math.max(0,Math.floor(maxAge))}`}
function j(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}})}
function msg(data,fallback='Request failed.'){return String(data?.msg||data?.message||data?.error_description||data?.error||fallback).slice(0,500)}
function unsafe(request){return !['GET','HEAD','OPTIONS'].includes(request.method)}
function sameOrigin(request){if(!unsafe(request))return true;const site=request.headers.get('sec-fetch-site');if(site==='cross-site')return false;const origin=request.headers.get('origin');if(!origin)return true;try{return new URL(origin).origin===new URL(request.url).origin}catch{return false}}
async function jsonBody(request,max=100000){const len=Number(request.headers.get('content-length')||0);if(len>max)throw Object.assign(new Error('request_too_large'),{status:413});if(!String(request.headers.get('content-type')||'').toLowerCase().includes('application/json'))throw Object.assign(new Error('json_required'),{status:415});try{return await request.json()}catch{throw Object.assign(new Error('invalid_json'),{status:400})}}
async function sb(env,path,{method='GET',token,body,headers:extra}={}){const c=config(env),headers=new Headers({'apikey':c.key,'accept':'application/json',...(extra||{})});if(token)headers.set('authorization','Bearer '+token);if(body!==undefined)headers.set('content-type','application/json');const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),12000);try{const r=await fetch(c.url+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body),signal:ctl.signal});const raw=await r.text();let data=null;if(raw){try{data=JSON.parse(raw)}catch{data=raw}}return{ok:r.ok,status:r.status,data,headers:r.headers}}catch(e){return{ok:false,status:503,data:{message:e?.name==='AbortError'?'Upstream timeout.':'Supabase is temporarily unavailable.'},headers:new Headers()}}finally{clearTimeout(timer)}}
async function refresh(request,env){const rt=parseCookies(request)[REFRESH_COOKIE];if(!rt)return null;const r=await sb(env,'/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:rt}});return r.ok&&r.data?.access_token?r.data:null}
async function session(request,env){const c=parseCookies(request);let token=c[ACCESS_COOKIE]||'',user=token?await sb(env,'/auth/v1/user',{token}):null,refreshed=null;if(!user?.ok){refreshed=await refresh(request,env);if(refreshed?.access_token){token=refreshed.access_token;user=await sb(env,'/auth/v1/user',{token})}}if(!user?.ok||!user.data?.id)return{ok:false,status:401};return{ok:true,token,user:user.data,refreshed}}
function withRefresh(response,s){if(!s?.refreshed)return response;const h=new Headers(response.headers),ttl=Math.min(Math.max(Number(s.refreshed.expires_in)||3600,60),7200);h.append('set-cookie',cookie(ACCESS_COOKIE,String(s.refreshed.access_token||''),ttl));if(s.refreshed.refresh_token)h.append('set-cookie',cookie(REFRESH_COOKIE,String(s.refreshed.refresh_token),30*24*60*60));return new Response(response.body,{status:response.status,statusText:response.statusText,headers:h})}
function uuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''))}
function privacyView(x){if(!x)return{...PRIVACY_DEFAULT};return{discoverable:x.discoverable!==false,profileVisibility:String(x.profile_visibility||'standard'),photoVisibility:String(x.photo_visibility||'everyone'),showOnline:x.show_online!==false,showDistance:x.show_distance!==false,showLastSeen:x.show_last_seen!==false,readReceipts:x.read_receipts!==false,showTravel:x.show_travel!==false,searchIndexing:x.search_indexing===true,verifiedOnlyMessaging:x.verified_only_messaging===true,updatedAt:x.updated_at||null}}
async function getPrivacy(request,env){const s=await session(request,env);if(!s.ok)return j({error:'Authentication required.'},401);const r=await sb(env,'/rest/v1/privacy_preferences?select=*&user_id=eq.'+encodeURIComponent(s.user.id)+'&limit=1',{token:s.token});if(!r.ok)return withRefresh(j({error:msg(r.data,'Privacy settings could not be loaded.')},r.status>=500?503:r.status),s);return withRefresh(j(privacyView(Array.isArray(r.data)?r.data[0]:null)),s)}
async function savePrivacy(request,env){const s=await session(request,env);if(!s.ok)return j({error:'Authentication required.'},401);const patch=await jsonBody(request);const r=await sb(env,'/rest/v1/rpc/hc_privacy_update_v1',{method:'POST',token:s.token,body:{p_patch:patch}});if(!r.ok)return withRefresh(j({error:msg(r.data,'Privacy settings could not be saved.')},r.status===401||r.status===403?403:r.status>=500?503:400),s);return withRefresh(j({ok:true,privacy:privacyView(r.data)}),s)}
async function inbox(request,env){const s=await session(request,env);if(!s.ok)return j({error:'Authentication required.'},401);const u=new URL(request.url),limit=Math.max(1,Math.min(100,Number(u.searchParams.get('limit'))||50));const r=await sb(env,'/rest/v1/rpc/hc_inbox_v1',{method:'POST',token:s.token,body:{p_limit:limit}});if(!r.ok)return withRefresh(j({error:msg(r.data,'Inbox could not be loaded.')},r.status===401||r.status===403?403:r.status>=500?503:r.status),s);return withRefresh(j(r.data||{items:[],unreadTotal:0}),s)}
async function notifications(request,env){const s=await session(request,env);if(!s.ok)return j({error:'Authentication required.'},401);const u=new URL(request.url),limit=Math.max(1,Math.min(100,Number(u.searchParams.get('limit'))||50));const r=await sb(env,'/rest/v1/notifications?select=id,event_type,body,actor_id,profile_id,is_read,created_at,read_at&user_id=eq.'+encodeURIComponent(s.user.id)+'&order=created_at.desc&limit='+limit,{token:s.token});if(!r.ok)return withRefresh(j({error:msg(r.data,'Notifications could not be loaded.')},r.status>=500?503:r.status),s);const items=Array.isArray(r.data)?r.data:[];return withRefresh(j({items,unread:items.reduce((n,x)=>n+(x.is_read?0:1),0)}),s)}
async function notificationRead(request,env,id){const s=await session(request,env);if(!s.ok)return j({error:'Authentication required.'},401);if(!uuid(id))return j({error:'Invalid notification.'},400);const r=await sb(env,'/rest/v1/notifications?id=eq.'+encodeURIComponent(id)+'&user_id=eq.'+encodeURIComponent(s.user.id),{method:'PATCH',token:s.token,body:{is_read:true,read_at:new Date().toISOString()},headers:{Prefer:'return=representation'}});if(!r.ok)return withRefresh(j({error:msg(r.data,'Notification could not be updated.')},r.status>=500?503:r.status),s);if(!Array.isArray(r.data)||!r.data.length)return withRefresh(j({error:'Notification unavailable.'},404),s);return withRefresh(j({ok:true,notification:r.data[0]}),s)}
async function enforcements(request,env){const s=await session(request,env);if(!s.ok)return j({error:'Authentication required.'},401);const r=await sb(env,'/rest/v1/account_enforcements?select=id,action,reason_code,reason_summary,starts_at,ends_at,active,created_at,lifted_at&user_id=eq.'+encodeURIComponent(s.user.id)+'&order=created_at.desc&limit=50',{token:s.token});if(!r.ok)return withRefresh(j({error:msg(r.data,'Account enforcement history could not be loaded.')},r.status>=500?503:r.status),s);const items=Array.isArray(r.data)?r.data:[];const now=Date.now(),active=items.filter(x=>x.active&&(!x.ends_at||Date.parse(x.ends_at)>now)&&!x.lifted_at);return withRefresh(j({items,restricted:active.some(x=>['temporary_suspension','permanent_suspension','visibility_restriction','feature_restriction'].includes(String(x.action))),active}),s)}
async function peerMessages(request,env,peer){if(!uuid(peer))return j({error:'Invalid conversation member.'},400);const s=await session(request,env);if(!s.ok)return j({error:'Authentication required.'},401);const r=await sb(env,'/rest/v1/rpc/hc_match_for_peer_v1',{method:'POST',token:s.token,body:{p_peer:peer}});const matchId=typeof r.data==='string'?r.data:'';if(!r.ok||!uuid(matchId))return withRefresh(j({error:'Conversation requires an active mutual match.'},403),s);const u=new URL(request.url);u.pathname='/api/_cf/messages/'+matchId;const delegated=await handleNativeApiV1(new Request(u.toString(),request),env);return withRefresh(delegated||j({error:'Conversation unavailable.'},404),s)}

export async function handleNativeApi(request,env){const u=new URL(request.url),p=u.pathname;if(!p.startsWith('/api/_cf/'))return null;if(!sameOrigin(request))return securityHeaders(j({error:'Cross-site request blocked.'},403));try{
  if(p==='/api/_cf/privacy'&&request.method==='GET')return securityHeaders(await getPrivacy(request,env));
  if(p==='/api/_cf/privacy'&&request.method==='POST')return securityHeaders(await savePrivacy(request,env));
  if(p==='/api/_cf/inbox'&&request.method==='GET')return securityHeaders(await inbox(request,env));
  if(p==='/api/_cf/notifications'&&request.method==='GET')return securityHeaders(await notifications(request,env));
  if(p==='/api/_cf/enforcements'&&request.method==='GET')return securityHeaders(await enforcements(request,env));
  const nr=p.match(/^\/api\/_cf\/notifications\/([^/]+)\/read$/);if(nr&&request.method==='POST')return securityHeaders(await notificationRead(request,env,nr[1]));
  const pm=p.match(/^\/api\/_cf\/conversations\/([^/]+)\/messages$/);if(pm&&(request.method==='GET'||request.method==='POST'))return securityHeaders(await peerMessages(request,env,pm[1]));
  return await handleNativeApiV1(request,env);
}catch(e){const status=Number(e?.status)||500;return securityHeaders(j({error:status===413?'Request too large.':status===415?'JSON request required.':status===400?'Invalid request.':'Native API error.'},status))}}

export {securityHeaders,VERSION};
