const VERSION='hc-edge-performance-v1';
const STATIC_EXT=/\.(?:js|mjs|css|png|jpe?g|webp|avif|gif|svg|ico|woff2?|ttf|otf)$/i;
const HASHED=/[-._][A-Za-z0-9_-]{8,}\.(?:js|mjs|css|png|jpe?g|webp|avif|woff2?)$/i;
function eligible(request){if(request.method!=='GET')return false;const u=new URL(request.url);if(u.pathname.startsWith('/api/')||u.pathname==='/sw.js'||u.pathname.endsWith('/service-worker.js'))return false;return u.pathname.startsWith('/assets/')||u.pathname.startsWith('/resources/')||STATIC_EXT.test(u.pathname)}
function cacheKey(request){const u=new URL(request.url);u.hash='';return new Request(u.toString(),{method:'GET',headers:{accept:request.headers.get('accept')||'*/*'}})}
function decorate(response,{hit=false,duration=0,immutable=false}={}){const h=new Headers(response.headers);h.set('x-heart-connect-performance',VERSION);h.set('x-heart-connect-cache',hit?'HIT':'MISS');if(duration>0)h.set('server-timing','origin;dur='+duration.toFixed(1));if(immutable)h.set('cache-control','public, max-age=31536000, immutable');else if(!h.has('cache-control'))h.set('cache-control','public, max-age=3600, stale-while-revalidate=86400');h.delete('set-cookie');return new Response(response.body,{status:response.status,statusText:response.statusText,headers:h})}
export async function staticResponse(request,ctx,fetcher){if(!eligible(request))return null;const cache=caches.default,key=cacheKey(request),cached=await cache.match(key);if(cached)return decorate(cached,{hit:true,immutable:HASHED.test(new URL(request.url).pathname)});const start=performance.now(),origin=await fetcher(),duration=performance.now()-start;if(!origin.ok)return decorate(origin,{duration});const ct=String(origin.headers.get('content-type')||'').toLowerCase();if(ct.includes('text/html')||ct.includes('application/json'))return decorate(origin,{duration});const response=decorate(origin,{duration,immutable:HASHED.test(new URL(request.url).pathname)});ctx.waitUntil(cache.put(key,response.clone()));return response}
export function timed(response,duration){const h=new Headers(response.headers);h.set('x-heart-connect-performance',VERSION);if(duration>=0)h.append('server-timing','edge-upstream;dur='+duration.toFixed(1));return new Response(response.body,{status:response.status,statusText:response.statusText,headers:h})}
export {VERSION};
