import previousWorker from './worker-v6.js';

const EDGE_VERSION='cloudflare-router-v7';
function isNavigation(request){if(request.method!=='GET'&&request.method!=='HEAD')return false;const mode=request.headers.get('sec-fetch-mode')||'',accept=request.headers.get('accept')||'';return mode==='navigate'||accept.includes('text/html')}

function bookingPolishClient(){
  let scheduled=false;
  const DAY=86400000;
  const text=el=>String(el&&el.textContent||'').trim();
  const label=prefix=>Array.from(document.querySelectorAll('label')).find(l=>text(l).startsWith(prefix))||null;
  function setNative(input,value){const d=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value');if(d&&d.set)d.set.call(input,value);else input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))}
  function ymd(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
  function parseDate(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(v||''))return null;const p=v.split('-').map(Number),x=new Date(p[0],p[1]-1,p[2]);return x.getFullYear()===p[0]&&x.getMonth()===p[1]-1&&x.getDate()===p[2]?x:null}
  function nights(a,b){const x=parseDate(a),y=parseDate(b);return x&&y?Math.round((y.getTime()-x.getTime())/DAY):0}
  const money=n=>'KES '+Number(n||0).toLocaleString();
  function style(){if(document.getElementById('hc-booking-polish-style'))return;const s=document.createElement('style');s.id='hc-booking-polish-style';s.textContent='.hc-stay-auto{margin:12px 0 18px;padding:14px 16px;border-radius:16px;border:1px solid rgba(236,72,117,.22);background:linear-gradient(135deg,rgba(236,72,117,.08),rgba(255,255,255,.92));display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.hc-stay-auto div{padding:9px 10px;border-radius:12px;background:rgba(255,255,255,.82)}.hc-stay-auto small,.hc-stay-auto b{display:block}.hc-stay-auto small{font-size:10px;color:#76636b}.hc-stay-auto b{font-size:15px;margin-top:3px}.hc-stay-auto .total b{color:#ed174f;font-size:19px}.hc-stay-help{display:block;margin-top:5px;font-size:11px;color:#76636b;line-height:1.4}.hc-nok-card{margin:16px 0;padding:17px;border:1px solid rgba(89,65,78,.16);border-radius:18px;background:#fff}.hc-nok-head{display:flex;gap:10px;align-items:flex-start;margin-bottom:12px}.hc-nok-icon{width:36px;height:36px;border-radius:50%;display:grid;place-items:center;background:rgba(236,72,117,.1);font-weight:900;color:#ed174f}.hc-nok-head b,.hc-nok-head small{display:block}.hc-nok-head small{color:#76636b;font-size:11px;margin-top:2px}.hc-nok-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.hc-nok-grid label{font-size:12px}.hc-nok-grid input,.hc-nok-grid select{width:100%}.hc-nok-privacy{margin:10px 0 0;font-size:10px;color:#76636b}.hc-edge-booking-error{margin:10px 0;padding:11px 13px;border-radius:12px;background:#fff1f3;color:#9f1239;border:1px solid #fecdd3;font-size:12px;font-weight:700}@media(max-width:680px){.hc-stay-auto{grid-template-columns:1fr}.hc-nok-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
  function notice(message){let n=document.querySelector('.hc-edge-booking-error');if(!n){n=document.createElement('div');n.className='hc-edge-booking-error';const btn=document.querySelector('.submit-booking');if(btn&&btn.parentElement)btn.parentElement.insertBefore(n,btn)}if(n)n.textContent=message}
  function stayInputs(){return{checkIn:label('Check-in')&&label('Check-in').querySelector('input[type="date"]'),checkOut:label('Check-out')&&label('Check-out').querySelector('input[type="date"]'),rate:(label('Preferred nightly rate')||label('Nightly budget / preferred rate'))&&((label('Preferred nightly rate')||label('Nightly budget / preferred rate')).querySelector('select'))}}
  function enhanceStay(){if(!Array.from(document.querySelectorAll('h2')).some(h=>text(h).includes('One-guest BnB reservation')))return;const f=stayInputs(),checkIn=f.checkIn,checkOut=f.checkOut,rate=f.rate;if(!checkIn||!checkOut||!rate)return;checkIn.min=ymd(new Date());const rateLabel=label('Preferred nightly rate')||label('Nightly budget / preferred rate');if(rateLabel&&!rateLabel.dataset.hcHelp){rateLabel.dataset.hcHelp='1';const h=document.createElement('small');h.className='hc-stay-help';h.textContent='Your stay total is calculated automatically from check-in, check-out and the selected nightly budget.';rateLabel.appendChild(h)}function render(auto){const a=parseDate(checkIn.value);if(a){const minOut=new Date(a.getTime()+DAY),maxOut=new Date(a.getTime()+60*DAY);checkOut.min=ymd(minOut);checkOut.max=ymd(maxOut);const current=parseDate(checkOut.value);if(auto&&(!current||current<=a||current>maxOut))setNative(checkOut,ymd(minOut))}const n=nights(checkIn.value,checkOut.value),r=Number(rate.value||0),total=n>=1&&n<=60&&r>=2500&&r<=10000?n*r:0;let box=document.querySelector('.hc-stay-auto');if(!box){box=document.createElement('div');box.className='hc-stay-auto';const estimate=document.querySelector('.estimate');if(estimate&&estimate.parentElement)estimate.parentElement.insertBefore(box,estimate)}if(box)box.innerHTML='<div><small>Stay length</small><b>'+(n>=1&&n<=60?n+' night'+(n===1?'':'s'):'Choose valid dates')+'</b></div><div><small>Nightly budget</small><b>'+money(r)+'</b></div><div class="total"><small>Automatic requested total</small><b>'+(total?money(total):'—')+'</b></div>';const estimate=document.querySelector('.estimate');if(estimate&&total){const b=estimate.querySelector('b'),s=estimate.querySelector('span');if(b)b.textContent='1 guest · '+n+' night'+(n===1?'':'s');if(s)s.textContent='Automatic estimate: '+n+' × '+money(r)+' = '+money(total)}}if(checkIn.dataset.hcBound!=='1'){checkIn.dataset.hcBound='1';checkIn.addEventListener('change',()=>render(true));checkIn.addEventListener('input',()=>render(true))}if(checkOut.dataset.hcBound!=='1'){checkOut.dataset.hcBound='1';checkOut.addEventListener('change',()=>render(false));checkOut.addEventListener('input',()=>render(false))}if(rate.dataset.hcBound!=='1'){rate.dataset.hcBound='1';rate.addEventListener('change',()=>render(false))}render(false)}
  function enhanceKin(){const originalLabel=label('Emergency contact'),original=originalLabel&&originalLabel.querySelector('input');if(!original||document.querySelector('.hc-nok-card'))return;originalLabel.style.display='none';const card=document.createElement('section');card.className='hc-nok-card';card.innerHTML='<div class="hc-nok-head"><span class="hc-nok-icon">☎</span><div><b>Emergency / Next of Kin Contact</b><small>Recommended for accommodation safety and urgent reservation communication.</small></div></div><div class="hc-nok-grid"><label>Full name<input class="hc-nok-name" placeholder="e.g. Jane Doe"></label><label>Relationship<select class="hc-nok-rel"><option value="">Choose relationship</option><option>Parent</option><option>Spouse / Partner</option><option>Sibling</option><option>Child</option><option>Relative</option><option>Friend</option><option>Guardian</option><option>Colleague</option><option>Other</option></select></label><label>Phone number<input class="hc-nok-phone" inputmode="tel" placeholder="+2547XXXXXXXX"></label><label>Email <small>(optional)</small><input class="hc-nok-email" type="email" placeholder="contact@example.com"></label></div><p class="hc-nok-privacy">This contact is used only for the reservation and urgent safety/operational needs. It is not shown on the dating profile.</p>';if(originalLabel.parentElement)originalLabel.parentElement.insertBefore(card,originalLabel);const name=card.querySelector('.hc-nok-name'),rel=card.querySelector('.hc-nok-rel'),phone=card.querySelector('.hc-nok-phone'),email=card.querySelector('.hc-nok-email');function sync(){const p=[];if(name.value.trim())p.push('Name: '+name.value.trim());if(rel.value)p.push('Relationship: '+rel.value);if(phone.value.trim())p.push('Phone: '+phone.value.trim());if(email.value.trim())p.push('Email: '+email.value.trim());setNative(original,p.join(' | '))}Array.from([name,rel,phone,email]).forEach(x=>{x.addEventListener('input',sync);x.addEventListener('change',sync)})}
  function enhanceRefresh(){Array.from(document.querySelectorAll('button.refresh')).forEach(b=>{if(!text(b).includes('Refresh reservations')||b.dataset.hcRefresh==='1')return;b.dataset.hcRefresh='1';b.addEventListener('click',()=>{const old=b.textContent;b.textContent='Refreshing reservations…';b.setAttribute('aria-busy','true');setTimeout(()=>{b.textContent='Reservations refreshed ✓';b.removeAttribute('aria-busy');setTimeout(()=>{b.textContent=old},1200)},900)})})}
  function validate(){const btn=document.querySelector('.submit-booking');if(!btn||btn.dataset.hcValidate==='1')return;btn.dataset.hcValidate='1';btn.addEventListener('click',e=>{if(!Array.from(document.querySelectorAll('h2')).some(h=>text(h).includes('One-guest BnB reservation')))return;document.querySelector('.hc-edge-booking-error')&&document.querySelector('.hc-edge-booking-error').remove();const f=stayInputs(),n=nights(f.checkIn&&f.checkIn.value||'',f.checkOut&&f.checkOut.value||''),r=Number(f.rate&&f.rate.value||0);if(!f.checkIn||!f.checkIn.value||!f.checkOut||!f.checkOut.value){e.preventDefault();e.stopImmediatePropagation();notice('Choose check-in and check-out dates. Nights and total are calculated automatically.');return}if(n<1||n>60){e.preventDefault();e.stopImmediatePropagation();notice('Choose a stay between 1 and 60 nights. Check-out must be after check-in.');return}if(!Number.isInteger(r)||r<2500||r>10000){e.preventDefault();e.stopImmediatePropagation();notice('Choose a nightly budget from KES 2,500 to KES 10,000.');return}const c=document.querySelector('.hc-nok-card');if(c){const name=c.querySelector('.hc-nok-name').value.trim(),phone=c.querySelector('.hc-nok-phone').value.trim(),rel=c.querySelector('.hc-nok-rel').value,email=c.querySelector('.hc-nok-email').value.trim();if((name||phone||rel||email)&&(!name||!phone)){e.preventDefault();e.stopImmediatePropagation();notice('For Next of Kin, enter at least the full name and phone number, or leave the section blank.')}}},{capture:true})}
  function enhance(){if(location.pathname!=='/bookings'&&!location.pathname.startsWith('/bookings/'))return;style();enhanceStay();enhanceKin();enhanceRefresh();validate()}
  new MutationObserver(()=>{if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;enhance()})}).observe(document.documentElement,{childList:true,subtree:true});
  addEventListener('DOMContentLoaded',enhance);enhance();
}

function edgeResponse(response){const headers=new Headers(response.headers);headers.set('x-heart-connect-edge',EDGE_VERSION);return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}

export default {async fetch(request,env,ctx){const incoming=new URL(request.url);if(incoming.pathname==='/_hc/booking-polish.js')return new Response('('+bookingPolishClient.toString()+')();',{headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'public, max-age=180','x-content-type-options':'nosniff','x-heart-connect-edge':EDGE_VERSION}});let response=await previousWorker.fetch(request,env,ctx);const navigation=isNavigation(request)&&!incoming.pathname.startsWith('/api/');if(navigation&&response.ok&&(response.headers.get('content-type')||'').includes('text/html')&&(incoming.pathname==='/bookings'||incoming.pathname.startsWith('/bookings/'))){response=new HTMLRewriter().on('head',{element(element){element.append('<script src="/_hc/booking-polish.js" defer></script>',{html:true})}}).transform(response)}return edgeResponse(response)}};
