import previousWorker from './worker-v6.js';
import BOOKING_FIX_JS from './booking-fix-v8.txt';
import SAFE_SW_JS from './sw-v8.txt';

const EDGE_VERSION='cloudflare-router-v9';
const BOOKING_FIX_PATH='/_hc/booking-fix-v9.js';
const API='https://api-v2.appdeploy.ai/app/heart-connect-n8dpuu';
function isNavigation(request){if(request.method!=='GET'&&request.method!=='HEAD')return false;const mode=request.headers.get('sec-fetch-mode')||'',accept=request.headers.get('accept')||'';return mode==='navigate'||accept.includes('text/html')}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-heart-connect-edge':EDGE_VERSION}})}
function clean(v,max=220){return String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max)}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||'').trim())}
async function sendResend(env,to,subject,text,key,replyTo=''){const apiKey=String(env.RESEND_API_KEY||'').trim();if(!apiKey||!validEmail(to))return false;const body={from:'Heart Connect Bookings <noreply@royal-heart.com>',to:[to],subject,text};if(validEmail(replyTo))body.reply_to=replyTo;try{const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+apiKey,'Content-Type':'application/json','Idempotency-Key':'hc-booking-v9-'+key},body:JSON.stringify(body)});return r.ok}catch{return false}}
async function fallbackAdminAlert(booking,id,text){const sender=validEmail(booking?.email)?booking.email:'noreply@royal-heart.com';try{const r=await fetch(API+'/api/contact',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:clean(booking?.guestName,80)||'Heart Connect Booking System',email:sender,department:'admin',subject:'New booking request '+id,message:text,website:''})});return r.ok}catch{return false}}
async function verifiedGuestBooking(id,accessKey){if(!/^[A-Za-z0-9_-]{1,180}$/.test(id)||!/^[a-f0-9]{48}$/i.test(accessKey))return null;try{const r=await fetch(API+'/api/bookings/guest/'+encodeURIComponent(id)+'/status',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({accessKey})});if(!r.ok)return null;const data=await r.json();return data?.booking?.ownerType==='guest'?data.booking:null}catch{return null}}
async function bookingAlert(request,env){const size=Number(request.headers.get('content-length')||0);if(size>25000)return json({ok:false,error:'payload_too_large'},413);let body=null;try{body=await request.json()}catch{return json({ok:false,error:'invalid_json'},400)}const id=clean(body?.result?.id,180),accessKey=clean(body?.result?.accessKey,80),booking=await verifiedGuestBooking(id,accessKey);if(!booking)return json({ok:false,error:'booking_access_invalid'},403);const where=clean(booking.locationDisplay||booking.destination||booking.city||'Location pending',240),when=[clean(booking.checkIn,20),clean(booking.checkOut,20)].filter(Boolean).join(' → ')+(booking.nights?' · '+booking.nights+' night(s)':''),amount='KES '+Number(booking.amountKes||0).toLocaleString(),customer=clean(booking.email,254),guest=clean(booking.guestName,100)||'Guest',admin=clean(env.BOOKING_ADMIN_EMAIL||'admin@royal-heart.com',254);const customerText=['Hi '+guest+',','','We received your Heart Connect BnB booking request.','Reference: '+id,'Location: '+where,when?'Stay: '+when:'','Requested amount: '+amount,'Status: REQUESTED — awaiting availability review.','','Your booking is saved in Your reservations. Do not make payment until Heart Connect approves the property/provider.','Manage your booking: https://royal-heart.com/bookings/'].filter(Boolean).join('\n');const adminText=['New Heart Connect BnB booking request','','Reference: '+id,'Customer: '+guest,validEmail(customer)?'Email: '+customer:'',booking.guestPhone?'Phone: '+clean(booking.guestPhone,60):'','Location: '+where,when?'Stay: '+when:'','Requested amount: '+amount,'Status: REQUESTED — not yet confirmed','','Review: https://royal-heart.com/admin/#/bookings'].filter(Boolean).join('\n');const emailConfigured=!!String(env.RESEND_API_KEY||'').trim();let customerEmailSent=false,adminAlerted=false;if(emailConfigured){[customerEmailSent,adminAlerted]=await Promise.all([sendResend(env,customer,'Heart Connect booking request received — '+id,customerText,id+'-customer'),sendResend(env,admin,'[Heart Connect Bookings] New BnB request '+id,adminText,id+'-admin',customer)])}if(!adminAlerted)adminAlerted=await fallbackAdminAlert(booking,id,adminText);return json({ok:true,emailConfigured,customerEmailSent,adminAlerted})}
function edgeResponse(response){const headers=new Headers(response.headers);headers.set('x-heart-connect-edge',EDGE_VERSION);return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
export default {async fetch(request,env,ctx){const incoming=new URL(request.url);if(incoming.pathname===BOOKING_FIX_PATH)return new Response(BOOKING_FIX_JS,{headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'public, max-age=604800, immutable','x-content-type-options':'nosniff','x-heart-connect-edge':EDGE_VERSION}});if(incoming.pathname==='/_hc/booking-fix.js'||incoming.pathname==='/_hc/booking-polish.js')return new Response('/* superseded by booking-fix v9 */',{headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-heart-connect-edge':EDGE_VERSION}});if(incoming.pathname==='/_hc/booking-email-status')return json({resendConfigured:!!String(env.RESEND_API_KEY||'').trim(),adminFallback:true});if(incoming.pathname==='/_hc/booking-alert'&&request.method==='POST')return bookingAlert(request,env);if(incoming.pathname==='/sw.js'&&request.method==='GET')return new Response(SAFE_SW_JS,{headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-cache, no-store, must-revalidate','service-worker-allowed':'/','x-content-type-options':'nosniff','x-heart-connect-edge':EDGE_VERSION}});let response=await previousWorker.fetch(request,env,ctx),navigation=isNavigation(request)&&!incoming.pathname.startsWith('/api/');if(navigation&&response.ok&&(response.headers.get('content-type')||'').includes('text/html')&&(incoming.pathname==='/bookings'||incoming.pathname.startsWith('/bookings/')))response=new HTMLRewriter().on('head',{element(element){element.append('<script src="'+BOOKING_FIX_PATH+'" defer></script>',{html:true})}}).transform(response);return edgeResponse(response)}};