const DEFAULT_ORIGIN='https://heart-connect-n8dpuu.v2.appdeploy.ai';

function upstreamUrl(request,origin,rewriteNavigation){const incoming=new URL(request.url);const target=new URL(rewriteNavigation?'/':incoming.pathname,origin);target.search=incoming.search;return target}
function isNavigation(request){if(request.method!=='GET'&&request.method!=='HEAD')return false;const mode=request.headers.get('sec-fetch-mode')||'';const accept=request.headers.get('accept')||'';return mode==='navigate'||accept.includes('text/html')}
function forwardedRequest(request,target){const headers=new Headers(request.headers);const incoming=new URL(request.url);headers.set('x-forwarded-host',incoming.host);headers.set('x-forwarded-proto',incoming.protocol.replace(':',''));headers.set('x-heart-connect-edge','cloudflare-router-v1');return new Request(target.toString(),{method:request.method,headers,body:['GET','HEAD'].includes(request.method)?undefined:request.body,redirect:'manual'})}
function rewriteLocation(response,request,origin){const location=response.headers.get('location');if(!location)return response;let next;try{next=new URL(location,origin)}catch{return response}const upstream=new URL(origin),incoming=new URL(request.url);if(next.host!==upstream.host)return response;next.protocol=incoming.protocol;next.host=incoming.host;const headers=new Headers(response.headers);headers.set('location',next.toString());return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
function withEdgeHeader(response){const headers=new Headers(response.headers);headers.set('x-heart-connect-edge','cloudflare-router-v1');return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}

export default {async fetch(request,env){const origin=String(env.APPDEPLOY_ORIGIN||DEFAULT_ORIGIN).replace(/\/+$/,'');const navigation=isNavigation(request)&&!new URL(request.url).pathname.startsWith('/api/');const target=upstreamUrl(request,origin,navigation);let response=await fetch(forwardedRequest(request,target));response=rewriteLocation(response,request,origin);if(navigation&&response.ok&&(response.headers.get('content-type')||'').includes('text/html')){const transformed=new HTMLRewriter().on('head',{element(element){element.prepend('<base href="/">',{html:true})}}).transform(response);return withEdgeHeader(transformed)}return withEdgeHeader(response)}};

export {isNavigation,upstreamUrl};
